/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Billing.V20180709.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeAllocationBillConditionsResponse : AbstractModel
    {
        
        /// <summary>
        /// Product filter list
        /// </summary>
        [JsonProperty("Business")]
        public BillBusiness[] Business{ get; set; }

        /// <summary>
        /// Subproduct filter list
        /// </summary>
        [JsonProperty("Product")]
        public BillProduct[] Product{ get; set; }

        /// <summary>
        /// Component name filter list
        /// </summary>
        [JsonProperty("Item")]
        public BillItem[] Item{ get; set; }

        /// <summary>
        /// Region filter list
        /// </summary>
        [JsonProperty("Region")]
        public BillRegion[] Region{ get; set; }

        /// <summary>
        /// Instance type filter list
        /// </summary>
        [JsonProperty("InstanceType")]
        public BillInstanceType[] InstanceType{ get; set; }

        /// <summary>
        /// Billing mode filter list
        /// </summary>
        [JsonProperty("PayMode")]
        public BillPayMode[] PayMode{ get; set; }

        /// <summary>
        /// Project filter list
        /// </summary>
        [JsonProperty("Project")]
        public BillProject[] Project{ get; set; }

        /// <summary>
        /// Tag filter list
        /// </summary>
        [JsonProperty("Tag")]
        public BillTag[] Tag{ get; set; }

        /// <summary>
        /// User UIN filter list
        /// </summary>
        [JsonProperty("OwnerUin")]
        public BillOwnerUin[] OwnerUin{ get; set; }

        /// <summary>
        /// Operator UIN filter list
        /// </summary>
        [JsonProperty("OperateUin")]
        public BillOperateUin[] OperateUin{ get; set; }

        /// <summary>
        /// Date filter list
        /// </summary>
        [JsonProperty("BillDay")]
        public BillDays[] BillDay{ get; set; }

        /// <summary>
        /// Transaction type filter list
        /// </summary>
        [JsonProperty("ActionType")]
        public BillActionType[] ActionType{ get; set; }

        /// <summary>
        /// Component type filter list
        /// </summary>
        [JsonProperty("Component")]
        public BillComponent[] Component{ get; set; }

        /// <summary>
        /// Availability zone filter list
        /// </summary>
        [JsonProperty("Zone")]
        public BillZoneId[] Zone{ get; set; }

        /// <summary>
        /// Cost allocation unit filter list
        /// </summary>
        [JsonProperty("AllocationTreeNode")]
        public AllocationTreeNode[] AllocationTreeNode{ get; set; }

        /// <summary>
        /// Cost allocation tag key
        /// </summary>
        [JsonProperty("TagKey")]
        public string[] TagKey{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamArrayObj(map, prefix + "Business.", this.Business);
            this.SetParamArrayObj(map, prefix + "Product.", this.Product);
            this.SetParamArrayObj(map, prefix + "Item.", this.Item);
            this.SetParamArrayObj(map, prefix + "Region.", this.Region);
            this.SetParamArrayObj(map, prefix + "InstanceType.", this.InstanceType);
            this.SetParamArrayObj(map, prefix + "PayMode.", this.PayMode);
            this.SetParamArrayObj(map, prefix + "Project.", this.Project);
            this.SetParamArrayObj(map, prefix + "Tag.", this.Tag);
            this.SetParamArrayObj(map, prefix + "OwnerUin.", this.OwnerUin);
            this.SetParamArrayObj(map, prefix + "OperateUin.", this.OperateUin);
            this.SetParamArrayObj(map, prefix + "BillDay.", this.BillDay);
            this.SetParamArrayObj(map, prefix + "ActionType.", this.ActionType);
            this.SetParamArrayObj(map, prefix + "Component.", this.Component);
            this.SetParamArrayObj(map, prefix + "Zone.", this.Zone);
            this.SetParamArrayObj(map, prefix + "AllocationTreeNode.", this.AllocationTreeNode);
            this.SetParamArraySimple(map, prefix + "TagKey.", this.TagKey);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

