/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Trocket.V20230308.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DoHealthCheckOnMigratingTopicResponse : AbstractModel
    {
        
        /// <summary>
        /// Whether to Pass		
        /// </summary>
        [JsonProperty("Passed")]
        public bool? Passed{ get; set; }

        /// <summary>
        /// Error information returned by health check.
        /// NotChecked indicates the check is not executed. 
        /// Unknown error. 
        /// TopicNotImported. specifies the topic is not imported.
        /// TopicNotExistsInSourceCluster specifies the topic does not exist in the source cluster. 
        /// Topic does not exist in the target cluster. 
        /// ConsumerConnectedOnTarget specifies whether consumer connections exist on the target cluster. 
        /// SourceTopicHasNewMessagesIn5Minutes indicates that new messages were written to the source cluster topic in the last 5 minutes. 
        /// TargetTopicHasNewMessagesIn5Minutes specifies whether new messages were written to the target cluster topic in the last 5 minutes. 
        /// SourceTopicHasNoMessagesIn5Minutes specifies no new messages were written to the source cluster in the last 5 minutes. 
        /// TargetTopicHasNoMessagesIn5Minutes specifies that no new messages were written to the source cluster in the last 5 minutes. 
        /// Inconsistent number of subscription groups. 
        /// SourceTopicHasUnconsumedMessages specifies that unconsumed messages exist in the source cluster topic.
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("Reason")]
        public string Reason{ get; set; }

        /// <summary>
        /// List of error information returned by health check.
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("ReasonList")]
        public string[] ReasonList{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "Passed", this.Passed);
            this.SetParamSimple(map, prefix + "Reason", this.Reason);
            this.SetParamArraySimple(map, prefix + "ReasonList.", this.ReasonList);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

