/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Live.V20180801.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribePushBandwidthAndFluxListResponse : AbstractModel
    {
        
        /// <summary>
        /// Peak bandwidth timestamp, using UTC time format, e.g., 2019-01-08T10:00:00Z. Note: Beijing time value equals UTC time value + 8 hours, expressed in ISO 8601 standard format. For details, refer to ISO Date Format Description.(https://cloud.tencent.com/document/product/266/11732#I)
        /// </summary>
        [JsonProperty("PeakBandwidthTime")]
        public string PeakBandwidthTime{ get; set; }

        /// <summary>
        /// Peak bandwidth, measured in Mbps.
        /// </summary>
        [JsonProperty("PeakBandwidth")]
        public float? PeakBandwidth{ get; set; }

        /// <summary>
        /// 95th percentile peak bandwidth timestamp, using UTC time format, e.g., 2019-01-08T10:00:00Z. Note: Beijing time value equals UTC time value + 8 hours, expressed in ISO 8601 standard format. For details, refer to ISO Date Format Description.(https://cloud.tencent.com/document/product/266/11732#I).
        /// </summary>
        [JsonProperty("P95PeakBandwidthTime")]
        public string P95PeakBandwidthTime{ get; set; }

        /// <summary>
        /// 95th percentile peak bandwidth, measured in Mbps.
        /// </summary>
        [JsonProperty("P95PeakBandwidth")]
        public float? P95PeakBandwidth{ get; set; }

        /// <summary>
        /// Total traffic, measured in MB.
        /// </summary>
        [JsonProperty("SumFlux")]
        public float? SumFlux{ get; set; }

        /// <summary>
        /// Detailed data information.
        /// </summary>
        [JsonProperty("DataInfoList")]
        public BillDataInfo[] DataInfoList{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "PeakBandwidthTime", this.PeakBandwidthTime);
            this.SetParamSimple(map, prefix + "PeakBandwidth", this.PeakBandwidth);
            this.SetParamSimple(map, prefix + "P95PeakBandwidthTime", this.P95PeakBandwidthTime);
            this.SetParamSimple(map, prefix + "P95PeakBandwidth", this.P95PeakBandwidth);
            this.SetParamSimple(map, prefix + "SumFlux", this.SumFlux);
            this.SetParamArrayObj(map, prefix + "DataInfoList.", this.DataInfoList);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

