/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Ocr.V20181119.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class ExtractDocMultiResponse : AbstractModel
    {
        
        /// <summary>
        /// Image rotation angle (angle system). the text's horizontal direction is 0. clockwise is positive; counterclockwise is negative.
        /// </summary>
        [JsonProperty("Angle")]
        public float? Angle{ get; set; }

        /// <summary>
        /// Configures the structured text info.
        /// </summary>
        [JsonProperty("StructuralList")]
        public GroupInfo[] StructuralList{ get; set; }

        /// <summary>
        /// Restore text information.
        /// </summary>
        [JsonProperty("WordList")]
        public WordItem[] WordList{ get; set; }

        /// <summary>
        /// Number of sample identification fields.
        /// </summary>
        [JsonProperty("TokenNum")]
        public long? TokenNum{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "Angle", this.Angle);
            this.SetParamArrayObj(map, prefix + "StructuralList.", this.StructuralList);
            this.SetParamArrayObj(map, prefix + "WordList.", this.WordList);
            this.SetParamSimple(map, prefix + "TokenNum", this.TokenNum);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

