/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Ocr.V20181119.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class GetCardVerificationExternalResultResponse : AbstractModel
    {
        
        /// <summary>
        /// Verification status. Valid values: 
        /// PROCESSING
        /// ABNORMAL
        /// COMPLETED
        /// </summary>
        [JsonProperty("Status")]
        public string Status{ get; set; }

        /// <summary>
        /// Anti-counterfeiting information. 
        /// - ScreenshotSuspected: The image is a screenshot.
        /// - RetakeSuspected: The image is taken from another screen.
        /// - PaperCopy: The image is a black and white, or color photocopy.
        /// - FakeSuspected: The image of the card, or the information on the card has been edited or altered.
        /// - PoorImageQuality: The image is bad quality.
        /// - InformationVerificationFailed: Information verification failed based on OCR recognition results
        /// - TooManyCards: Multiple cards present in the frame.
        /// - IncompleteCard: Captured document is incomplete.
        /// - OtherWarning: Document's authenticity is not verified for various reasons.
        /// 
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("WarnInfo")]
        public string[] WarnInfo{ get; set; }

        /// <summary>
        /// Country or region of the document.
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("Nationality")]
        [System.Obsolete]
        public string Nationality{ get; set; }

        /// <summary>
        /// Front-side document recognition results. 
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("CardInfo")]
        public GeneralCard CardInfo{ get; set; }

        /// <summary>
        /// Back-side document recognition results.
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("BackCardInfo")]
        public GeneralCard BackCardInfo{ get; set; }

        /// <summary>
        /// The token passed in the input parameters.
        /// </summary>
        [JsonProperty("CardVerificationToken")]
        public string CardVerificationToken{ get; set; }

        /// <summary>
        /// Base64-encoded head image from the document. If ReturnHeadImage was set to false or not provided in the request, this field returns an empty string. If ReturnHeadImage was set to true and this field returns an empty string, indicating a failure to extract the head image extraction failed. Please check the input document photo.
        /// </summary>
        [JsonProperty("HeadImageBase64")]
        public string HeadImageBase64{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "Status", this.Status);
            this.SetParamArraySimple(map, prefix + "WarnInfo.", this.WarnInfo);
            this.SetParamSimple(map, prefix + "Nationality", this.Nationality);
            this.SetParamObj(map, prefix + "CardInfo.", this.CardInfo);
            this.SetParamObj(map, prefix + "BackCardInfo.", this.BackCardInfo);
            this.SetParamSimple(map, prefix + "CardVerificationToken", this.CardVerificationToken);
            this.SetParamSimple(map, prefix + "HeadImageBase64", this.HeadImageBase64);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

