/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Ocr.V20181119.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class HmtResidentPermitOCRResponse : AbstractModel
    {
        
        /// <summary>
        /// <p>Name on the document</p>
        /// </summary>
        [JsonProperty("Name")]
        public string Name{ get; set; }

        /// <summary>
        /// <p>Gender</p>
        /// </summary>
        [JsonProperty("Sex")]
        public string Sex{ get; set; }

        /// <summary>
        /// <p>Date of birth</p>
        /// </summary>
        [JsonProperty("Birth")]
        public string Birth{ get; set; }

        /// <summary>
        /// <p>Address</p>
        /// </summary>
        [JsonProperty("Address")]
        public string Address{ get; set; }

        /// <summary>
        /// <p>Identity card number</p>
        /// </summary>
        [JsonProperty("IdCardNo")]
        public string IdCardNo{ get; set; }

        /// <summary>
        /// <p>0-Front<br>1-Back</p>
        /// </summary>
        [JsonProperty("CardType")]
        public long? CardType{ get; set; }

        /// <summary>
        /// <p>Document validity period</p>
        /// </summary>
        [JsonProperty("ValidDate")]
        public string ValidDate{ get; set; }

        /// <summary>
        /// <p>Issuing authority</p>
        /// </summary>
        [JsonProperty("Authority")]
        public string Authority{ get; set; }

        /// <summary>
        /// <p>Number of issuances</p>
        /// </summary>
        [JsonProperty("VisaNum")]
        public string VisaNum{ get; set; }

        /// <summary>
        /// Travel permit number
        /// </summary>
        [JsonProperty("PassNo")]
        public string PassNo{ get; set; }

        /// <summary>
        /// Portrait image and coordinate information
        /// </summary>
        [JsonProperty("PortraitImageInfo")]
        public PortraitImageInfo PortraitImageInfo{ get; set; }

        /// <summary>
        /// Card Warning Information
        /// 
        /// -9102 Alarm for photocopied certificate
        /// -9103 Alarm for photographed certificate
        /// -9104 Alarm for tamper certificate
        /// -9109 This capability is not enabled. Please contact customer support to activate the alert service
        /// </summary>
        [JsonProperty("WarnCardInfos")]
        public long?[] WarnCardInfos{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "Name", this.Name);
            this.SetParamSimple(map, prefix + "Sex", this.Sex);
            this.SetParamSimple(map, prefix + "Birth", this.Birth);
            this.SetParamSimple(map, prefix + "Address", this.Address);
            this.SetParamSimple(map, prefix + "IdCardNo", this.IdCardNo);
            this.SetParamSimple(map, prefix + "CardType", this.CardType);
            this.SetParamSimple(map, prefix + "ValidDate", this.ValidDate);
            this.SetParamSimple(map, prefix + "Authority", this.Authority);
            this.SetParamSimple(map, prefix + "VisaNum", this.VisaNum);
            this.SetParamSimple(map, prefix + "PassNo", this.PassNo);
            this.SetParamObj(map, prefix + "PortraitImageInfo.", this.PortraitImageInfo);
            this.SetParamArraySimple(map, prefix + "WarnCardInfos.", this.WarnCardInfos);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

