/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Ocr.V20181119.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class PODAuditAIResponse : AbstractModel
    {
        
        /// <summary>
        /// <p>0 means non-compliance 1 means compliance</p>
        /// </summary>
        [JsonProperty("AuditorDecision")]
        public long? AuditorDecision{ get; set; }

        /// <summary>
        /// <p>Non-compliance reason code. If there are multiple, return a list of multiple codes</p><p>Enumeration values:</p><ul><li>-2: Not supported currently or internal logic error</li><li>100: Delivered to the wrong address</li><li>104: No shipping label</li><li>105: Shipping label number not the same as the system</li><li>200: Package delivery location unclear</li><li>202: Acknowledgment contains personal privacy</li></ul>
        /// </summary>
        [JsonProperty("FailCode")]
        public string[] FailCode{ get; set; }

        /// <summary>
        /// <p>Entire approval result analysis content</p>
        /// </summary>
        [JsonProperty("ResultAnalysis")]
        public string ResultAnalysis{ get; set; }

        /// <summary>
        /// <p>Analysis result logs of each layer, including time taken, judgment reason, and judgment conclusion</p>
        /// </summary>
        [JsonProperty("AnalyzedLogs")]
        public AnalyzedLog[] AnalyzedLogs{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "AuditorDecision", this.AuditorDecision);
            this.SetParamArraySimple(map, prefix + "FailCode.", this.FailCode);
            this.SetParamSimple(map, prefix + "ResultAnalysis", this.ResultAnalysis);
            this.SetParamArrayObj(map, prefix + "AnalyzedLogs.", this.AnalyzedLogs);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

