/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Ocr.V20181119.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class RecognizeBrazilDriverLicenseOCRResponse : AbstractModel
    {
        
        /// <summary>
        /// Name of the license holder.
        /// </summary>
        [JsonProperty("NOME")]
        public string NOME{ get; set; }

        /// <summary>
        /// Driver's license category.
        /// </summary>
        [JsonProperty("CatHab")]
        public string CatHab{ get; set; }

        /// <summary>
        /// Driver's license number (CNH).
        /// </summary>
        [JsonProperty("CNHNumber")]
        public string CNHNumber{ get; set; }

        /// <summary>
        /// Validity date (valid until).
        /// </summary>
        [JsonProperty("VALIDADE")]
        public string VALIDADE{ get; set; }

        /// <summary>
        /// Qualification information.
        /// </summary>
        [JsonProperty("QUALIFICATION")]
        public string QUALIFICATION{ get; set; }

        /// <summary>
        /// ID number (Identity document number).
        /// </summary>
        [JsonProperty("IDENTIDADE")]
        public string IDENTIDADE{ get; set; }

        /// <summary>
        /// CPF
        /// </summary>
        [JsonProperty("CPF")]
        public string CPF{ get; set; }

        /// <summary>
        /// Date of birth.
        /// </summary>
        [JsonProperty("NASCIMENTO")]
        public string NASCIMENTO{ get; set; }

        /// <summary>
        /// Membership
        /// </summary>
        [JsonProperty("MEMBERSHIP")]
        public string MEMBERSHIP{ get; set; }

        /// <summary>
        /// Registration number
        /// </summary>
        [JsonProperty("REGISTRO")]
        public string REGISTRO{ get; set; }

        /// <summary>
        /// Remarks
        /// </summary>
        [JsonProperty("OBSERVATIONS")]
        public string OBSERVATIONS{ get; set; }

        /// <summary>
        /// Date of issue.
        /// </summary>
        [JsonProperty("IssueDate")]
        public string IssueDate{ get; set; }

        /// <summary>
        /// Place of issue.
        /// </summary>
        [JsonProperty("LOCAL")]
        public string LOCAL{ get; set; }

        /// <summary>
        /// Registration number on the back of the card.
        /// </summary>
        [JsonProperty("BackNumber")]
        public string BackNumber{ get; set; }

        /// <summary>
        /// This field is deprecated and will always return "1". Usage is not recommended.
        /// </summary>
        [JsonProperty("AdvancedInfo")]
        [System.Obsolete]
        public string AdvancedInfo{ get; set; }

        /// <summary>
        /// PortraitImage base64
        /// </summary>
        [JsonProperty("PortraitImage")]
        public string PortraitImage{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "NOME", this.NOME);
            this.SetParamSimple(map, prefix + "CatHab", this.CatHab);
            this.SetParamSimple(map, prefix + "CNHNumber", this.CNHNumber);
            this.SetParamSimple(map, prefix + "VALIDADE", this.VALIDADE);
            this.SetParamSimple(map, prefix + "QUALIFICATION", this.QUALIFICATION);
            this.SetParamSimple(map, prefix + "IDENTIDADE", this.IDENTIDADE);
            this.SetParamSimple(map, prefix + "CPF", this.CPF);
            this.SetParamSimple(map, prefix + "NASCIMENTO", this.NASCIMENTO);
            this.SetParamSimple(map, prefix + "MEMBERSHIP", this.MEMBERSHIP);
            this.SetParamSimple(map, prefix + "REGISTRO", this.REGISTRO);
            this.SetParamSimple(map, prefix + "OBSERVATIONS", this.OBSERVATIONS);
            this.SetParamSimple(map, prefix + "IssueDate", this.IssueDate);
            this.SetParamSimple(map, prefix + "LOCAL", this.LOCAL);
            this.SetParamSimple(map, prefix + "BackNumber", this.BackNumber);
            this.SetParamSimple(map, prefix + "AdvancedInfo", this.AdvancedInfo);
            this.SetParamSimple(map, prefix + "PortraitImage", this.PortraitImage);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

