/*
 * Copyright (c) 2018 THL A29 Limited, a Tencent company. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Ocr.V20181119.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class RecognizeThaiPinkCardResponse : AbstractModel
    {
        
        /// <summary>
        /// Country
        /// </summary>
        [JsonProperty("Country")]
        public string Country{ get; set; }

        /// <summary>
        /// ID number
        /// </summary>
        [JsonProperty("IDNumber")]
        public string IDNumber{ get; set; }

        /// <summary>
        /// Name in Thai
        /// </summary>
        [JsonProperty("ThaiName")]
        public string ThaiName{ get; set; }

        /// <summary>
        /// Name in English
        /// </summary>
        [JsonProperty("EnName")]
        public string EnName{ get; set; }

        /// <summary>
        /// Date of birth in Thai
        /// </summary>
        [JsonProperty("ThaiDOB")]
        public string ThaiDOB{ get; set; }

        /// <summary>
        /// Date of birth in English
        /// </summary>
        [JsonProperty("EnDOB")]
        public string EnDOB{ get; set; }

        /// <summary>
        /// Photo number
        /// </summary>
        [JsonProperty("PhotoNumber")]
        public string PhotoNumber{ get; set; }

        /// <summary>
        /// Address in Thai
        /// </summary>
        [JsonProperty("ThaiAddress")]
        public string ThaiAddress{ get; set; }

        /// <summary>
        /// Date of issue in Thai
        /// </summary>
        [JsonProperty("ThaiDateOfIssue")]
        public string ThaiDateOfIssue{ get; set; }

        /// <summary>
        /// Date of issue in English
        /// </summary>
        [JsonProperty("DateOfIssue")]
        public string DateOfIssue{ get; set; }

        /// <summary>
        /// Expiration date in Thai
        /// </summary>
        [JsonProperty("ThaiDateOfExpiry")]
        public string ThaiDateOfExpiry{ get; set; }

        /// <summary>
        /// Expiration date in English
        /// </summary>
        [JsonProperty("DateOfExpiry")]
        public string DateOfExpiry{ get; set; }

        /// <summary>
        /// Issuing agency
        /// </summary>
        [JsonProperty("IssuingAgency")]
        public string IssuingAgency{ get; set; }

        /// <summary>
        /// Ref number
        /// </summary>
        [JsonProperty("RefNumber")]
        public string RefNumber{ get; set; }

        /// <summary>
        /// Field confidence:
        ///  { "ID": { "Confidence": 0.9999 }, "ThaiName": { "Confidence": 0.9996 } }
        /// </summary>
        [JsonProperty("AdvancedInfo")]
        public string AdvancedInfo{ get; set; }

        /// <summary>
        /// Identity photo
        /// </summary>
        [JsonProperty("PortraitImage")]
        public string PortraitImage{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "Country", this.Country);
            this.SetParamSimple(map, prefix + "IDNumber", this.IDNumber);
            this.SetParamSimple(map, prefix + "ThaiName", this.ThaiName);
            this.SetParamSimple(map, prefix + "EnName", this.EnName);
            this.SetParamSimple(map, prefix + "ThaiDOB", this.ThaiDOB);
            this.SetParamSimple(map, prefix + "EnDOB", this.EnDOB);
            this.SetParamSimple(map, prefix + "PhotoNumber", this.PhotoNumber);
            this.SetParamSimple(map, prefix + "ThaiAddress", this.ThaiAddress);
            this.SetParamSimple(map, prefix + "ThaiDateOfIssue", this.ThaiDateOfIssue);
            this.SetParamSimple(map, prefix + "DateOfIssue", this.DateOfIssue);
            this.SetParamSimple(map, prefix + "ThaiDateOfExpiry", this.ThaiDateOfExpiry);
            this.SetParamSimple(map, prefix + "DateOfExpiry", this.DateOfExpiry);
            this.SetParamSimple(map, prefix + "IssuingAgency", this.IssuingAgency);
            this.SetParamSimple(map, prefix + "RefNumber", this.RefNumber);
            this.SetParamSimple(map, prefix + "AdvancedInfo", this.AdvancedInfo);
            this.SetParamSimple(map, prefix + "PortraitImage", this.PortraitImage);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

