/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Ocr.V20181119.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class RecognizeBrazilIDCardOCRResponse : AbstractModel
    {
        
        /// <summary>
        /// Name
        /// </summary>
        [JsonProperty("Nome")]
        public string Nome{ get; set; }

        /// <summary>
        /// Family information
        /// </summary>
        [JsonProperty("MemberShip")]
        public string MemberShip{ get; set; }

        /// <summary>
        /// Birthday
        /// </summary>
        [JsonProperty("DataNascimento")]
        public string DataNascimento{ get; set; }

        /// <summary>
        /// Issuing agency
        /// </summary>
        [JsonProperty("IssuingAgency")]
        public string IssuingAgency{ get; set; }

        /// <summary>
        /// blood type
        /// </summary>
        [JsonProperty("Fatorrh")]
        public string Fatorrh{ get; set; }

        /// <summary>
        /// Birth place
        /// </summary>
        [JsonProperty("NaturalIDade")]
        public string NaturalIDade{ get; set; }

        /// <summary>
        /// Additional information 
        /// </summary>
        [JsonProperty("Observations")]
        public string Observations{ get; set; }

        /// <summary>
        /// CPF
        /// </summary>
        [JsonProperty("CPF")]
        public string CPF{ get; set; }

        /// <summary>
        /// DNI
        /// </summary>
        [JsonProperty("DNI")]
        public string DNI{ get; set; }

        /// <summary>
        /// universal registration
        /// </summary>
        [JsonProperty("RegistroGeral")]
        public string RegistroGeral{ get; set; }

        /// <summary>
        /// Issue date
        /// </summary>
        [JsonProperty("DispatchDate")]
        public string DispatchDate{ get; set; }

        /// <summary>
        /// address
        /// </summary>
        [JsonProperty("Registro")]
        public string Registro{ get; set; }

        /// <summary>
        /// Portrait image
        /// </summary>
        [JsonProperty("PortraitImage")]
        public string PortraitImage{ get; set; }

        /// <summary>
        /// Original identity information
        /// </summary>
        [JsonProperty("DocOrigem")]
        public string DocOrigem{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "Nome", this.Nome);
            this.SetParamSimple(map, prefix + "MemberShip", this.MemberShip);
            this.SetParamSimple(map, prefix + "DataNascimento", this.DataNascimento);
            this.SetParamSimple(map, prefix + "IssuingAgency", this.IssuingAgency);
            this.SetParamSimple(map, prefix + "Fatorrh", this.Fatorrh);
            this.SetParamSimple(map, prefix + "NaturalIDade", this.NaturalIDade);
            this.SetParamSimple(map, prefix + "Observations", this.Observations);
            this.SetParamSimple(map, prefix + "CPF", this.CPF);
            this.SetParamSimple(map, prefix + "DNI", this.DNI);
            this.SetParamSimple(map, prefix + "RegistroGeral", this.RegistroGeral);
            this.SetParamSimple(map, prefix + "DispatchDate", this.DispatchDate);
            this.SetParamSimple(map, prefix + "Registro", this.Registro);
            this.SetParamSimple(map, prefix + "PortraitImage", this.PortraitImage);
            this.SetParamSimple(map, prefix + "DocOrigem", this.DocOrigem);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

