/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Ocr.V20181119.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class RecognizePhilippinesDrivingLicenseOCRResponse : AbstractModel
    {
        
        /// <summary>
        /// The Base64-encoded identity photo.
        /// </summary>
        [JsonProperty("HeadPortrait")]
        public TextDetectionResult HeadPortrait{ get; set; }

        /// <summary>
        /// Full name of the license holder.
        /// </summary>
        [JsonProperty("Name")]
        public TextDetectionResult Name{ get; set; }

        /// <summary>
        /// Last name / surname of the license holder.
        /// </summary>
        [JsonProperty("LastName")]
        public TextDetectionResult LastName{ get; set; }

        /// <summary>
        /// First name of the license holder.
        /// </summary>
        [JsonProperty("FirstName")]
        public TextDetectionResult FirstName{ get; set; }

        /// <summary>
        /// Middle name of the license holder.
        /// </summary>
        [JsonProperty("MiddleName")]
        public TextDetectionResult MiddleName{ get; set; }

        /// <summary>
        /// Nationality of the license holder.
        /// </summary>
        [JsonProperty("Nationality")]
        public TextDetectionResult Nationality{ get; set; }

        /// <summary>
        /// Gender
        /// </summary>
        [JsonProperty("Sex")]
        public TextDetectionResult Sex{ get; set; }

        /// <summary>
        /// Address of the license holder.
        /// </summary>
        [JsonProperty("Address")]
        public TextDetectionResult Address{ get; set; }

        /// <summary>
        /// Driver's license number.
        /// </summary>
        [JsonProperty("LicenseNo")]
        public TextDetectionResult LicenseNo{ get; set; }

        /// <summary>
        /// Expiration date of the driver's license.
        /// </summary>
        [JsonProperty("ExpiresDate")]
        public TextDetectionResult ExpiresDate{ get; set; }

        /// <summary>
        /// Code of the issuing agency.
        /// </summary>
        [JsonProperty("AgencyCode")]
        public TextDetectionResult AgencyCode{ get; set; }

        /// <summary>
        /// Date of birth of the license holder.
        /// </summary>
        [JsonProperty("Birthday")]
        public TextDetectionResult Birthday{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamObj(map, prefix + "HeadPortrait.", this.HeadPortrait);
            this.SetParamObj(map, prefix + "Name.", this.Name);
            this.SetParamObj(map, prefix + "LastName.", this.LastName);
            this.SetParamObj(map, prefix + "FirstName.", this.FirstName);
            this.SetParamObj(map, prefix + "MiddleName.", this.MiddleName);
            this.SetParamObj(map, prefix + "Nationality.", this.Nationality);
            this.SetParamObj(map, prefix + "Sex.", this.Sex);
            this.SetParamObj(map, prefix + "Address.", this.Address);
            this.SetParamObj(map, prefix + "LicenseNo.", this.LicenseNo);
            this.SetParamObj(map, prefix + "ExpiresDate.", this.ExpiresDate);
            this.SetParamObj(map, prefix + "AgencyCode.", this.AgencyCode);
            this.SetParamObj(map, prefix + "Birthday.", this.Birthday);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

