/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Faceid.V20180301.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class ApplyCardVerificationResponse : AbstractModel
    {
        
        /// <summary>
        /// The token used to identify an verification process. It can be used to get the verification result after the process is completed.
        /// </summary>
        [JsonProperty("CardVerificationToken")]
        public string CardVerificationToken{ get; set; }

        /// <summary>
        /// The maximum number of polls for calling the pull result interface polling.
        /// </summary>
        [JsonProperty("AsyncCardVerificationMaxPollingTimes")]
        public ulong? AsyncCardVerificationMaxPollingTimes{ get; set; }

        /// <summary>
        /// The interval for polling when calling the pull result interface (in seconds).
        /// </summary>
        [JsonProperty("AsyncCardVerificationPollingWaitTime")]
        public ulong? AsyncCardVerificationPollingWaitTime{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "CardVerificationToken", this.CardVerificationToken);
            this.SetParamSimple(map, prefix + "AsyncCardVerificationMaxPollingTimes", this.AsyncCardVerificationMaxPollingTimes);
            this.SetParamSimple(map, prefix + "AsyncCardVerificationPollingWaitTime", this.AsyncCardVerificationPollingWaitTime);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

