/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Faceid.V20180301.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class BankCard4EVerificationResponse : AbstractModel
    {
        
        /// <summary>
        /// Verification result code.
        /// -Result code for charges
        /// '0': 'Authentication passed'.
        /// '-1': 'Authentication failed'.
        /// '-6': 'Cardholder information is incorrect'.
        /// '-7': 'Cardless payment not enabled'.
        /// '-8': 'Card confiscated'.
        /// '-9': 'Invalid card number'.
        /// '-10': 'No corresponding issuing bank for this card'.
        /// '-11': 'The card is uninitialized or a Sleep Card'.
        /// '-12': 'Cheat card, card confiscation'.
        /// '-13': 'Reported lost'.
        /// '-14': 'The card has expired.'
        /// '-15': 'Restricted card'.
        /// '-16': 'Exceeded the number of password errors'.
        /// '-17': 'Issuer does not support this transaction'.
        /// '-21': 'Card status exception or card number error'.
        /// 
        /// -Result code with no charge
        /// '-2': 'Name verification failed'.
        /// '-3': 'Identity number error'.
        /// '-4': 'Incorrect bank card number format'.
        /// '-5': 'Invalid phone number'.
        /// '-18': 'Verification Center Service busy'.
        /// '-19': 'Exceeded maximum verification attempts. Please retry the next day.'
        /// '-20': 'The ID number is not currently supported for verification. Currently only support second-generation resident identity card.'
        /// </summary>
        [JsonProperty("Result")]
        public string Result{ get; set; }

        /// <summary>
        /// Business result description.
        /// </summary>
        [JsonProperty("Description")]
        public string Description{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "Result", this.Result);
            this.SetParamSimple(map, prefix + "Description", this.Description);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

