/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Faceid.V20180301.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class BankCard2EVerificationResponse : AbstractModel
    {
        
        /// <summary>
        /// Verification result code.
        /// -Billing result code:
        /// '0': 'Authentication passed'.
        /// '-1': 'Authentication failed'.
        /// '-4': 'Cardholder information is incorrect'.
        /// '-5': 'Cardless payment not enabled'.
        /// '-6': 'Card confiscated'.
        /// '-7': 'Invalid card number'.
        /// '-8': 'No corresponding issuing bank for this card'.
        /// '-9': 'The card is uninitialized or a Sleep Card'.
        /// '-10': 'Cheat card, card confiscation'.
        /// '-11': 'Reported lost'.
        /// '-12': 'The card has expired'.
        /// '-13': 'Restricted card'.
        /// '-14': 'Number of password errors exceeds the limit'.
        /// '-15': 'Issuer does not support this transaction'.
        /// '-18': 'Card status exception or card number error'.
        /// 
        /// -Non-billing Result Code:
        /// '-2': 'Name verification failed'.
        /// '-3': 'Incorrect bank card number format'.
        /// '-16': 'Verification Center Service busy'.
        /// '-17': 'Verification attempts exceeded. Please retry the next day.'
        /// </summary>
        [JsonProperty("Result")]
        public string Result{ get; set; }

        /// <summary>
        /// Business result description.
        /// </summary>
        [JsonProperty("Description")]
        public string Description{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "Result", this.Result);
            this.SetParamSimple(map, prefix + "Description", this.Description);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

