/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Faceid.V20180301.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class CheckBankCardInformationResponse : AbstractModel
    {
        
        /// <summary>
        /// Verification result code. Billing is as follows.
        /// -Result code for charges
        /// Query succeeded
        /// -1: Not found
        /// -5: Invalid card number
        /// 
        /// -Result code with no charge
        /// -Verification Center Service is busy.
        /// -3: Bank card not found.
        /// -4: Authentication attempts exceeded the daily limit. Retry the next day.
        /// -6: This bank card type is not currently supported
        /// </summary>
        [JsonProperty("Result")]
        public string Result{ get; set; }

        /// <summary>
        /// Business result description.
        /// </summary>
        [JsonProperty("Description")]
        public string Description{ get; set; }

        /// <summary>
        /// Account opening bank.
        /// </summary>
        [JsonProperty("AccountBank")]
        public string AccountBank{ get; set; }

        /// <summary>
        /// Card type.
        /// -Value range:
        /// 1: Debit card.
        /// 2: Credit card.
        /// 3: Prepaid card.
        /// 4: Credit card
        /// </summary>
        [JsonProperty("AccountType")]
        public long? AccountType{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "Result", this.Result);
            this.SetParamSimple(map, prefix + "Description", this.Description);
            this.SetParamSimple(map, prefix + "AccountBank", this.AccountBank);
            this.SetParamSimple(map, prefix + "AccountType", this.AccountType);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

