/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Faceid.V20180301.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class CreateEKYCWebhookResponse : AbstractModel
    {
        
        /// <summary>
        /// <p>Returned results</p>
        /// </summary>
        [JsonProperty("Result")]
        public string Result{ get; set; }

        /// <summary>
        /// <p>ID of the created Webhook configuration</p>
        /// </summary>
        [JsonProperty("WebhookId")]
        public long? WebhookId{ get; set; }

        /// <summary>
        /// <p>Whether to add a callback signature key</p><p>Default value: false</p>
        /// </summary>
        [JsonProperty("HasSignatureKey")]
        public bool? HasSignatureKey{ get; set; }

        /// <summary>
        /// <p>Callback signature key</p>
        /// </summary>
        [JsonProperty("SignatureKey")]
        public string SignatureKey{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "Result", this.Result);
            this.SetParamSimple(map, prefix + "WebhookId", this.WebhookId);
            this.SetParamSimple(map, prefix + "HasSignatureKey", this.HasSignatureKey);
            this.SetParamSimple(map, prefix + "SignatureKey", this.SignatureKey);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

