/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Faceid.V20180301.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DetectReflectLivenessAndCompareRequest : AbstractModel
    {
        
        /// <summary>
        /// URL of the liveness detection data package generated by the SDK
        /// </summary>
        [JsonProperty("LiveDataUrl")]
        public string LiveDataUrl{ get; set; }

        /// <summary>
        /// MD5 hash value (32-bit) of the liveness detection data package generated by the SDK, which is used to verify the LiveData consistency.
        /// </summary>
        [JsonProperty("LiveDataMd5")]
        public string LiveDataMd5{ get; set; }

        /// <summary>
        /// URL of the target image for comparison
        /// </summary>
        [JsonProperty("ImageUrl")]
        public string ImageUrl{ get; set; }

        /// <summary>
        /// MD5 hash value (32-bit) of the target image for comparison, which is used to verify the `Image` consistency.
        /// </summary>
        [JsonProperty("ImageMd5")]
        public string ImageMd5{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "LiveDataUrl", this.LiveDataUrl);
            this.SetParamSimple(map, prefix + "LiveDataMd5", this.LiveDataMd5);
            this.SetParamSimple(map, prefix + "ImageUrl", this.ImageUrl);
            this.SetParamSimple(map, prefix + "ImageMd5", this.ImageMd5);
        }
    }
}

