/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Faceid.V20180301.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class GetAMLScreeningResultResponse : AbstractModel
    {
        
        /// <summary>
        /// <p>Filtering results: NO-HITS (not hit) / HAS-HITS (hit)</p>
        /// </summary>
        [JsonProperty("ScreeningResult")]
        public string ScreeningResult{ get; set; }

        /// <summary>
        /// <p>Whether continuous monitoring screening is enabled. false by default</p><p>Default value: false</p>
        /// </summary>
        [JsonProperty("EnableOngoingScreening")]
        public bool? EnableOngoingScreening{ get; set; }

        /// <summary>
        /// <p>Description of results returned</p>
        /// </summary>
        [JsonProperty("Description")]
        public string Description{ get; set; }

        /// <summary>
        /// <p>Returned results</p>
        /// </summary>
        [JsonProperty("Result")]
        public string Result{ get; set; }

        /// <summary>
        /// <p>The unique identifier of the case generated by a hit screening</p>
        /// </summary>
        [JsonProperty("ScreeningId")]
        public string ScreeningId{ get; set; }

        /// <summary>
        /// <p>Filtering result time</p>
        /// </summary>
        [JsonProperty("ResultTime")]
        public string ResultTime{ get; set; }

        /// <summary>
        /// <p>Return on hit, the hit AML type list (deduplicated)</p>
        /// </summary>
        [JsonProperty("AMLTypes")]
        public string[] AMLTypes{ get; set; }

        /// <summary>
        /// <p>Return on hit, hit risk detail list</p>
        /// </summary>
        [JsonProperty("HitDetail")]
        public string HitDetail{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "ScreeningResult", this.ScreeningResult);
            this.SetParamSimple(map, prefix + "EnableOngoingScreening", this.EnableOngoingScreening);
            this.SetParamSimple(map, prefix + "Description", this.Description);
            this.SetParamSimple(map, prefix + "Result", this.Result);
            this.SetParamSimple(map, prefix + "ScreeningId", this.ScreeningId);
            this.SetParamSimple(map, prefix + "ResultTime", this.ResultTime);
            this.SetParamArraySimple(map, prefix + "AMLTypes.", this.AMLTypes);
            this.SetParamSimple(map, prefix + "HitDetail", this.HitDetail);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

