/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Trro.V20220325.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeSessionStatisticsResponse : AbstractModel
    {
        
        /// <summary>
        /// Number of sessions.
        /// </summary>
        [JsonProperty("SessionNum")]
        public ulong? SessionNum{ get; set; }

        /// <summary>
        /// Call duration, unit: minutes.
        /// </summary>
        [JsonProperty("TotalDuration")]
        public ulong? TotalDuration{ get; set; }

        /// <summary>
        /// Number of active on-site devices.
        /// </summary>
        [JsonProperty("ActiveFieldDeviceNum")]
        public ulong? ActiveFieldDeviceNum{ get; set; }

        /// <summary>
        /// Number of active remote devices.
        /// </summary>
        [JsonProperty("ActiveRemoteDeviceNum")]
        public ulong? ActiveRemoteDeviceNum{ get; set; }

        /// <summary>
        /// Proportion of excellent sessions, unit: %.
        /// </summary>
        [JsonProperty("NotBadSessionRatio")]
        public ulong? NotBadSessionRatio{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "SessionNum", this.SessionNum);
            this.SetParamSimple(map, prefix + "TotalDuration", this.TotalDuration);
            this.SetParamSimple(map, prefix + "ActiveFieldDeviceNum", this.ActiveFieldDeviceNum);
            this.SetParamSimple(map, prefix + "ActiveRemoteDeviceNum", this.ActiveRemoteDeviceNum);
            this.SetParamSimple(map, prefix + "NotBadSessionRatio", this.NotBadSessionRatio);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

