/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Alb.V20251030.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeSecurityPolicyCapabilitiesResponse : AbstractModel
    {
        
        /// <summary>
        /// List of security policy configuration capabilities. Return all supported TLS versions and their corresponding encryption suite information in the current region.
        /// 
        /// **Return content includes:**
        /// -Supported TLS protocol versions (for example, TLSv1.0, TLSv1.1, TLSv1.2, TLSv1.3).
        /// -List of cipher suites supported by each TLS version.
        /// 
        /// **Usage scenario:**
        /// -Get optional encryption suites by calling this API before creating a security policy (CreateSecurityPolicy).
        /// -Before modifying the security policy (ModifySecurityPolicyAttributes), confirm the validity of the new configuration.
        /// </summary>
        [JsonProperty("SecurityPolicyCapabilities")]
        public SecurityPolicyCapability[] SecurityPolicyCapabilities{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamArrayObj(map, prefix + "SecurityPolicyCapabilities.", this.SecurityPolicyCapabilities);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

