/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Alb.V20251030.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeSecurityPoliciesResponse : AbstractModel
    {
        
        /// <summary>
        /// Token for the next query.
        /// 
        /// -If the return value is not empty, it means there is more data. You can use this value as the NextToken parameter in the next request to continue querying.
        /// -If the return value is empty or this field is not returned, it means the current page is the last page.
        /// </summary>
        [JsonProperty("NextToken")]
        public string NextToken{ get; set; }

        /// <summary>
        /// Information list of security policies. Contains detailed configuration of each security policy, such as policy ID, name, TLS version, and encryption suite.
        /// </summary>
        [JsonProperty("SecurityPolicies")]
        public SecurityPolicyInfo[] SecurityPolicies{ get; set; }

        /// <summary>
        /// Total number of security policies that meet filtering criteria.
        /// 
        /// **Description:** This value indicates the total record count that meets the query condition, not the number of records returned this time. It can be used to calculate pagination information.
        /// </summary>
        [JsonProperty("TotalCount")]
        public long? TotalCount{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "NextToken", this.NextToken);
            this.SetParamArrayObj(map, prefix + "SecurityPolicies.", this.SecurityPolicies);
            this.SetParamSimple(map, prefix + "TotalCount", this.TotalCount);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

