/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Tcr.V20190924.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeReplicationInstanceSyncStatusResponse : AbstractModel
    {
        
        /// <summary>
        /// Synchronization status
        /// </summary>
        [JsonProperty("ReplicationStatus")]
        public string ReplicationStatus{ get; set; }

        /// <summary>
        /// Synchronization completion time
        /// </summary>
        [JsonProperty("ReplicationTime")]
        public string ReplicationTime{ get; set; }

        /// <summary>
        /// Synchronization log
        /// Note: this field may return `null`, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("ReplicationLog")]
        public ReplicationLog ReplicationLog{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "ReplicationStatus", this.ReplicationStatus);
            this.SetParamSimple(map, prefix + "ReplicationTime", this.ReplicationTime);
            this.SetParamObj(map, prefix + "ReplicationLog.", this.ReplicationLog);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

