/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Cls.V20201016.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class CreateMachineGroupRequest : AbstractModel
    {
        
        /// <summary>
        /// Machine group name.
        /// Input limit:
        /// -Supports up to 255 characters and cannot be an empty string
        /// -Cannot contain character '|'
        /// </summary>
        [JsonProperty("GroupName")]
        public string GroupName{ get; set; }

        /// <summary>
        /// Create machine group type. Values are as follows:
        /// -Type: ip. Create a machine group with a string list of IPs in Values.
        /// -Type: label. Create a machine group with a string list of tags in Values.
        /// </summary>
        [JsonProperty("MachineGroupType")]
        public MachineGroupTypeInfo MachineGroupType{ get; set; }

        /// <summary>
        /// Tag description list. This parameter is used to bind a tag to a machine group. Up to 10 tag key-value pairs are supported, and a resource can be bound to only one tag key.
        /// </summary>
        [JsonProperty("Tags")]
        public Tag[] Tags{ get; set; }

        /// <summary>
        /// Whether to enable machine group auto-update. Default false.
        /// </summary>
        [JsonProperty("AutoUpdate")]
        public bool? AutoUpdate{ get; set; }

        /// <summary>
        /// Start time of upgrade. It is suggested to upgrade LogListener in the off-peak period of the business.
        /// Time format: HH:mm:ss.
        /// </summary>
        [JsonProperty("UpdateStartTime")]
        public string UpdateStartTime{ get; set; }

        /// <summary>
        /// End time of upgrade. It is suggested to upgrade LogListener in the off-peak period of the business.
        /// Time format: HH:mm:ss.
        /// </summary>
        [JsonProperty("UpdateEndTime")]
        public string UpdateEndTime{ get; set; }

        /// <summary>
        /// Whether to enable service logs, which is used to record logs generated by the Loglistener service itself. After enabling, it will create an internal logset named cls_service_logging and log topics named loglistener_status, loglistener_alarm, and loglistener_business, without incurring charges. The default value is false.
        /// </summary>
        [JsonProperty("ServiceLogging")]
        public bool? ServiceLogging{ get; set; }

        /// <summary>
        /// Offline cleanup time for machines in the machine group, in days.
        /// 
        /// -This parameter is valid only when larger than 0.
        /// </summary>
        [JsonProperty("DelayCleanupTime")]
        public long? DelayCleanupTime{ get; set; }

        /// <summary>
        /// Metadata information list of a machine group
        /// </summary>
        [JsonProperty("MetaTags")]
        public MetaTagInfo[] MetaTags{ get; set; }

        /// <summary>
        /// System type. Values as follows:
        /// -0: Linux (default value)
        /// - 1:Windows
        /// </summary>
        [JsonProperty("OSType")]
        public ulong? OSType{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "GroupName", this.GroupName);
            this.SetParamObj(map, prefix + "MachineGroupType.", this.MachineGroupType);
            this.SetParamArrayObj(map, prefix + "Tags.", this.Tags);
            this.SetParamSimple(map, prefix + "AutoUpdate", this.AutoUpdate);
            this.SetParamSimple(map, prefix + "UpdateStartTime", this.UpdateStartTime);
            this.SetParamSimple(map, prefix + "UpdateEndTime", this.UpdateEndTime);
            this.SetParamSimple(map, prefix + "ServiceLogging", this.ServiceLogging);
            this.SetParamSimple(map, prefix + "DelayCleanupTime", this.DelayCleanupTime);
            this.SetParamArrayObj(map, prefix + "MetaTags.", this.MetaTags);
            this.SetParamSimple(map, prefix + "OSType", this.OSType);
        }
    }
}

