/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Cls.V20201016.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeKafkaConsumerGroupDetailResponse : AbstractModel
    {
        
        /// <summary>
        /// Logset id
        /// </summary>
        [JsonProperty("LogsetId")]
        public string LogsetId{ get; set; }

        /// <summary>
        /// Consumer group name
        /// </summary>
        [JsonProperty("Group")]
        public string Group{ get; set; }

        /// <summary>
        /// List of consumer group information
        /// </summary>
        [JsonProperty("PartitionInfos")]
        public GroupPartitionInfo[] PartitionInfos{ get; set; }

        /// <summary>
        /// Empty: The group has no members but has submitted offsets. All consumers have left but retained offsets.
        /// Dead: No members in the group and no submitted offset. The group is deleted or has long-term inactivity.
        /// Stable: Members in the group consume normally, and partition allocation is balanced. Normal operating status.
        /// PreparingRebalance: The group is preparing to rebalance. A new member joins or an existing member leaves.
        /// CompletingRebalance: The group is preparing to rebalance. New members join or existing members leave.
        /// </summary>
        [JsonProperty("State")]
        public string State{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "LogsetId", this.LogsetId);
            this.SetParamSimple(map, prefix + "Group", this.Group);
            this.SetParamArrayObj(map, prefix + "PartitionInfos.", this.PartitionInfos);
            this.SetParamSimple(map, prefix + "State", this.State);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

