/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Cls.V20201016.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class OpenClawServiceResponse : AbstractModel
    {
        
        /// <summary>
        /// <p>Logset id</p><p><a href="https://www.tencentcloud.com/document/product/614/41034?from_cn_redirect=1">Logset document</a></p>
        /// </summary>
        [JsonProperty("LogsetId")]
        public string LogsetId{ get; set; }

        /// <summary>
        /// <p>Logset name</p>
        /// </summary>
        [JsonProperty("LogsetName")]
        public string LogsetName{ get; set; }

        /// <summary>
        /// <p>Log topic id</p><p><a href="https://www.tencentcloud.com/document/product/614/41035?from_cn_redirect=1">Log topic document</a></p>
        /// </summary>
        [JsonProperty("TopicId")]
        public string TopicId{ get; set; }

        /// <summary>
        /// <p>Log topic name</p>
        /// </summary>
        [JsonProperty("TopicName")]
        public string TopicName{ get; set; }

        /// <summary>
        /// <p>Metric topic id</p><p><a href="https://www.tencentcloud.com/document/product/614/90328?from_cn_redirect=1">Metric topic document</a></p>
        /// </summary>
        [JsonProperty("MetricTopicId")]
        public string MetricTopicId{ get; set; }

        /// <summary>
        /// <p>Metric topic name</p>
        /// </summary>
        [JsonProperty("MetricTopicName")]
        public string MetricTopicName{ get; set; }

        /// <summary>
        /// <p>Bound machine group id</p><p><a href="https://www.tencentcloud.com/document/product/614/17412?from_cn_redirect=1">Machine group document</a></p>
        /// </summary>
        [JsonProperty("MachineGroupId")]
        public string MachineGroupId{ get; set; }

        /// <summary>
        /// <p>Machine group name</p>
        /// </summary>
        [JsonProperty("MachineGroupName")]
        public string MachineGroupName{ get; set; }

        /// <summary>
        /// <p>Collection configuration id. Application log</p><p><a href="https://www.tencentcloud.com/document/product/614/33494?from_cn_redirect=1">Collection overview document</a> - <a href="https://www.tencentcloud.com/document/product/614/57497?from_cn_redirect=1">LogListener collection configuration import</a></p>
        /// </summary>
        [JsonProperty("AppLogConfigId")]
        public string AppLogConfigId{ get; set; }

        /// <summary>
        /// <p>Collection configuration name. Application log</p>
        /// </summary>
        [JsonProperty("AppLogConfigName")]
        public string AppLogConfigName{ get; set; }

        /// <summary>
        /// <p>Collection configuration id. Session log</p><p><a href="https://www.tencentcloud.com/document/product/614/33494?from_cn_redirect=1">Collection overview document</a> - <a href="https://www.tencentcloud.com/document/product/614/57497?from_cn_redirect=1">LogListener collection configuration import</a></p>
        /// </summary>
        [JsonProperty("SessionLogConfigId")]
        public string SessionLogConfigId{ get; set; }

        /// <summary>
        /// <p>Collection configuration name. Session log</p>
        /// </summary>
        [JsonProperty("SessionLogConfigName")]
        public string SessionLogConfigName{ get; set; }

        /// <summary>
        /// <p>trace topic ID</p>
        /// </summary>
        [JsonProperty("TraceTopicId")]
        public string TraceTopicId{ get; set; }

        /// <summary>
        /// <p>trace topic name</p>
        /// </summary>
        [JsonProperty("TraceTopicName")]
        public string TraceTopicName{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "LogsetId", this.LogsetId);
            this.SetParamSimple(map, prefix + "LogsetName", this.LogsetName);
            this.SetParamSimple(map, prefix + "TopicId", this.TopicId);
            this.SetParamSimple(map, prefix + "TopicName", this.TopicName);
            this.SetParamSimple(map, prefix + "MetricTopicId", this.MetricTopicId);
            this.SetParamSimple(map, prefix + "MetricTopicName", this.MetricTopicName);
            this.SetParamSimple(map, prefix + "MachineGroupId", this.MachineGroupId);
            this.SetParamSimple(map, prefix + "MachineGroupName", this.MachineGroupName);
            this.SetParamSimple(map, prefix + "AppLogConfigId", this.AppLogConfigId);
            this.SetParamSimple(map, prefix + "AppLogConfigName", this.AppLogConfigName);
            this.SetParamSimple(map, prefix + "SessionLogConfigId", this.SessionLogConfigId);
            this.SetParamSimple(map, prefix + "SessionLogConfigName", this.SessionLogConfigName);
            this.SetParamSimple(map, prefix + "TraceTopicId", this.TraceTopicId);
            this.SetParamSimple(map, prefix + "TraceTopicName", this.TraceTopicName);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

