/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Tcss.V20201101.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeVirusScanConfigResponse : AbstractModel
    {
        
        /// <summary>
        /// Enable Regular Scanning
        /// </summary>
        [JsonProperty("EnableScan")]
        public bool? EnableScan{ get; set; }

        /// <summary>
        /// Detection Interval in Days
        /// </summary>
        [JsonProperty("Cycle")]
        public ulong? Cycle{ get; set; }

        /// <summary>
        /// Scan start time
        /// </summary>
        [JsonProperty("BeginScanAt")]
        public string BeginScanAt{ get; set; }

        /// <summary>
        /// Timeout Duration (Hours)
        /// </summary>
        [JsonProperty("Timeout")]
        public ulong? Timeout{ get; set; }

        /// <summary>
        /// SCAN_NODE: Scanning node
        /// SCAN CONTAINER
        /// </summary>
        [JsonProperty("ScanRangeType")]
        public string ScanRangeType{ get; set; }

        /// <summary>
        /// Container ID or Node ID in Custom Scan Range 
        /// </summary>
        [JsonProperty("ScanIDs")]
        public ScanRangeInfo[] ScanIDs{ get; set; }

        /// <summary>
        /// Custom Excluded or Scanned Address
        /// </summary>
        [JsonProperty("ScanPath")]
        public string[] ScanPath{ get; set; }

        /// <summary>
        /// Scan path mode:
        /// SCAN_PATH_ALL: All paths.
        /// SCAN_PATH_DEFAULT: Default path
        /// SCAN_PATH_USER_DEFINE: User-defined path
        /// </summary>
        [JsonProperty("ScanPathMode")]
        public string ScanPathMode{ get; set; }

        /// <summary>
        /// true: including path
        /// Default value: false. Excluded path.
        /// </summary>
        [JsonProperty("IsIncludePath")]
        public bool? IsIncludePath{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "EnableScan", this.EnableScan);
            this.SetParamSimple(map, prefix + "Cycle", this.Cycle);
            this.SetParamSimple(map, prefix + "BeginScanAt", this.BeginScanAt);
            this.SetParamSimple(map, prefix + "Timeout", this.Timeout);
            this.SetParamSimple(map, prefix + "ScanRangeType", this.ScanRangeType);
            this.SetParamArrayObj(map, prefix + "ScanIDs.", this.ScanIDs);
            this.SetParamArraySimple(map, prefix + "ScanPath.", this.ScanPath);
            this.SetParamSimple(map, prefix + "ScanPathMode", this.ScanPathMode);
            this.SetParamSimple(map, prefix + "IsIncludePath", this.IsIncludePath);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

