/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Tcss.V20201101.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeImageDenyRuleSummaryResponse : AbstractModel
    {
        
        /// <summary>
        /// Total Number of Image Interception Rules (Disabled and Enabled)
        /// </summary>
        [JsonProperty("RuleTotalCount")]
        public ulong? RuleTotalCount{ get; set; }

        /// <summary>
        /// Number of Enabled Image Interception Rules
        /// </summary>
        [JsonProperty("EnabledRuleCount")]
        public ulong? EnabledRuleCount{ get; set; }

        /// <summary>
        /// Number of Image Interception Rules During Observation
        /// </summary>
        [JsonProperty("ObservedRuleCount")]
        public ulong? ObservedRuleCount{ get; set; }

        /// <summary>
        /// Number of Effective Image Blocking Rules
        /// </summary>
        [JsonProperty("EffectiveRuleCount")]
        public ulong? EffectiveRuleCount{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "RuleTotalCount", this.RuleTotalCount);
            this.SetParamSimple(map, prefix + "EnabledRuleCount", this.EnabledRuleCount);
            this.SetParamSimple(map, prefix + "ObservedRuleCount", this.ObservedRuleCount);
            this.SetParamSimple(map, prefix + "EffectiveRuleCount", this.EffectiveRuleCount);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

