/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Tcss.V20201101.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeVulLevelSummaryResponse : AbstractModel
    {
        
        /// <summary>
        /// Number of high-risk vulnerabilities
        /// </summary>
        [JsonProperty("HighLevelVulCount")]
        public long? HighLevelVulCount{ get; set; }

        /// <summary>
        /// Number of medium-risk vulnerabilities
        /// </summary>
        [JsonProperty("MediumLevelVulCount")]
        public long? MediumLevelVulCount{ get; set; }

        /// <summary>
        /// Number of low-risk vulnerabilities
        /// </summary>
        [JsonProperty("LowLevelVulCount")]
        public long? LowLevelVulCount{ get; set; }

        /// <summary>
        /// Number of critical vulnerabilities
        /// </summary>
        [JsonProperty("CriticalLevelVulCount")]
        public long? CriticalLevelVulCount{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "HighLevelVulCount", this.HighLevelVulCount);
            this.SetParamSimple(map, prefix + "MediumLevelVulCount", this.MediumLevelVulCount);
            this.SetParamSimple(map, prefix + "LowLevelVulCount", this.LowLevelVulCount);
            this.SetParamSimple(map, prefix + "CriticalLevelVulCount", this.CriticalLevelVulCount);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

