/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Tcss.V20201101.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeImageAuthorizedInfoResponse : AbstractModel
    {
        
        /// <summary>
        /// Total number of valid image licenses
        /// </summary>
        [JsonProperty("TotalAuthorizedCnt")]
        public ulong? TotalAuthorizedCnt{ get; set; }

        /// <summary>
        /// Number of used image licenses
        /// </summary>
        [JsonProperty("UsedAuthorizedCnt")]
        public ulong? UsedAuthorizedCnt{ get; set; }

        /// <summary>
        /// Number of images with scan enabled
        /// </summary>
        [JsonProperty("ScannedImageCnt")]
        public ulong? ScannedImageCnt{ get; set; }

        /// <summary>
        /// Number of images with scan not enabled
        /// </summary>
        [JsonProperty("NotScannedImageCnt")]
        public ulong? NotScannedImageCnt{ get; set; }

        /// <summary>
        /// Number of local images with scan not enabled
        /// </summary>
        [JsonProperty("NotScannedLocalImageCnt")]
        public ulong? NotScannedLocalImageCnt{ get; set; }

        /// <summary>
        /// 
        /// </summary>
        [JsonProperty("TrialAuthorizedCnt")]
        public ulong? TrialAuthorizedCnt{ get; set; }

        /// <summary>
        /// 
        /// </summary>
        [JsonProperty("UsedTrialAuthorizedCnt")]
        public ulong? UsedTrialAuthorizedCnt{ get; set; }

        /// <summary>
        /// 
        /// </summary>
        [JsonProperty("PurchasedAuthorizedCnt")]
        public ulong? PurchasedAuthorizedCnt{ get; set; }

        /// <summary>
        /// 
        /// </summary>
        [JsonProperty("UsedPurchasedAuthorizedCnt")]
        public ulong? UsedPurchasedAuthorizedCnt{ get; set; }

        /// <summary>
        /// 
        /// </summary>
        [JsonProperty("CanApplyFreeImageAuthorize")]
        public bool? CanApplyFreeImageAuthorize{ get; set; }

        /// <summary>
        /// Image scanning billing information.
        /// </summary>
        [JsonProperty("ImageScanInquireInfo")]
        public ImageScanInquireInfo ImageScanInquireInfo{ get; set; }

        /// <summary>
        /// Number of duplicate images (local images and repository images).
        /// </summary>
        [JsonProperty("RepeatImageIdCnt")]
        public ulong? RepeatImageIdCnt{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "TotalAuthorizedCnt", this.TotalAuthorizedCnt);
            this.SetParamSimple(map, prefix + "UsedAuthorizedCnt", this.UsedAuthorizedCnt);
            this.SetParamSimple(map, prefix + "ScannedImageCnt", this.ScannedImageCnt);
            this.SetParamSimple(map, prefix + "NotScannedImageCnt", this.NotScannedImageCnt);
            this.SetParamSimple(map, prefix + "NotScannedLocalImageCnt", this.NotScannedLocalImageCnt);
            this.SetParamSimple(map, prefix + "TrialAuthorizedCnt", this.TrialAuthorizedCnt);
            this.SetParamSimple(map, prefix + "UsedTrialAuthorizedCnt", this.UsedTrialAuthorizedCnt);
            this.SetParamSimple(map, prefix + "PurchasedAuthorizedCnt", this.PurchasedAuthorizedCnt);
            this.SetParamSimple(map, prefix + "UsedPurchasedAuthorizedCnt", this.UsedPurchasedAuthorizedCnt);
            this.SetParamSimple(map, prefix + "CanApplyFreeImageAuthorize", this.CanApplyFreeImageAuthorize);
            this.SetParamObj(map, prefix + "ImageScanInquireInfo.", this.ImageScanInquireInfo);
            this.SetParamSimple(map, prefix + "RepeatImageIdCnt", this.RepeatImageIdCnt);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

