/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Cynosdb.V20190107.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class CalculateBackupSaveSecExpiresResponse : AbstractModel
    {
        
        /// <summary>
        /// Total number of backup files that will be deleted
        /// </summary>
        [JsonProperty("WillDeleteBackupFileCount")]
        public long? WillDeleteBackupFileCount{ get; set; }

        /// <summary>
        /// Backup file list to be deleted
        /// </summary>
        [JsonProperty("WillDeleteBackupFiles")]
        public WillDeleteItem[] WillDeleteBackupFiles{ get; set; }

        /// <summary>
        /// Total files of binlogs that will be deleted
        /// </summary>
        [JsonProperty("WillDeleteBinlogFileCount")]
        public long? WillDeleteBinlogFileCount{ get; set; }

        /// <summary>
        /// Binlog file list to be deleted
        /// </summary>
        [JsonProperty("WillDeleteBinlogFiles")]
        public WillDeleteItem[] WillDeleteBinlogFiles{ get; set; }

        /// <summary>
        /// Total Redolog files to be deleted
        /// </summary>
        [JsonProperty("WillDeleteRedoLogFileCount")]
        public long? WillDeleteRedoLogFileCount{ get; set; }

        /// <summary>
        /// List of Redolog files that will be deleted
        /// </summary>
        [JsonProperty("WillDeleteRedoLogFiles")]
        public WillDeleteItem[] WillDeleteRedoLogFiles{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "WillDeleteBackupFileCount", this.WillDeleteBackupFileCount);
            this.SetParamArrayObj(map, prefix + "WillDeleteBackupFiles.", this.WillDeleteBackupFiles);
            this.SetParamSimple(map, prefix + "WillDeleteBinlogFileCount", this.WillDeleteBinlogFileCount);
            this.SetParamArrayObj(map, prefix + "WillDeleteBinlogFiles.", this.WillDeleteBinlogFiles);
            this.SetParamSimple(map, prefix + "WillDeleteRedoLogFileCount", this.WillDeleteRedoLogFileCount);
            this.SetParamArrayObj(map, prefix + "WillDeleteRedoLogFiles.", this.WillDeleteRedoLogFiles);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

