/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Cynosdb.V20190107.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeClusterStorageAutoExpandResponse : AbstractModel
    {
        
        /// <summary>
        /// <p>Storage utilization threshold</p>
        /// </summary>
        [JsonProperty("StorageUsageThreshold")]
        public long? StorageUsageThreshold{ get; set; }

        /// <summary>
        /// <p>Scaling increment</p>
        /// </summary>
        [JsonProperty("ExpandStep")]
        public long? ExpandStep{ get; set; }

        /// <summary>
        /// <p>Maximum storage capacity limit</p>
        /// </summary>
        [JsonProperty("MaxStorageLimit")]
        public long? MaxStorageLimit{ get; set; }

        /// <summary>
        /// <p>Whether to enable: yes-enabled, no-disabled</p>
        /// </summary>
        [JsonProperty("StorageAutoExpand")]
        public string StorageAutoExpand{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "StorageUsageThreshold", this.StorageUsageThreshold);
            this.SetParamSimple(map, prefix + "ExpandStep", this.ExpandStep);
            this.SetParamSimple(map, prefix + "MaxStorageLimit", this.MaxStorageLimit);
            this.SetParamSimple(map, prefix + "StorageAutoExpand", this.StorageAutoExpand);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

