/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Cynosdb.V20190107.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeBackupOverviewResponse : AbstractModel
    {
        
        /// <summary>
        /// Total Backup Capacity
        /// </summary>
        [JsonProperty("BackupTotalVolume")]
        public float? BackupTotalVolume{ get; set; }

        /// <summary>
        /// Backup snapshot capacity
        /// </summary>
        [JsonProperty("BackupSnapshotVolume")]
        public float? BackupSnapshotVolume{ get; set; }

        /// <summary>
        /// Backup logical capacity
        /// </summary>
        [JsonProperty("BackupLogicVolume")]
        public float? BackupLogicVolume{ get; set; }

        /// <summary>
        /// Total Log Capacity
        /// </summary>
        [JsonProperty("LogTotalVolume")]
        public float? LogTotalVolume{ get; set; }

        /// <summary>
        /// binlog capacity
        /// </summary>
        [JsonProperty("LogBinlogVolume")]
        public float? LogBinlogVolume{ get; set; }

        /// <summary>
        /// Redo log capacity
        /// </summary>
        [JsonProperty("LogRedoLogVolume")]
        public float? LogRedoLogVolume{ get; set; }

        /// <summary>
        /// Total Cross-Region Backup Capacity
        /// </summary>
        [JsonProperty("CrossTotalVolume")]
        public float? CrossTotalVolume{ get; set; }

        /// <summary>
        /// Cross-Region Backup Capacity
        /// </summary>
        [JsonProperty("CrossRegionBackupVolume")]
        public float? CrossRegionBackupVolume{ get; set; }

        /// <summary>
        /// Cross-regional log capacity
        /// </summary>
        [JsonProperty("CrossRegionLogVolume")]
        public float? CrossRegionLogVolume{ get; set; }

        /// <summary>
        /// Backup capacity details
        /// </summary>
        [JsonProperty("BackupVolumeInfos")]
        public BackupVolumeInfo[] BackupVolumeInfos{ get; set; }

        /// <summary>
        /// Cross-region backup capacity details
        /// </summary>
        [JsonProperty("CrossRegionBackupVolumeInfos")]
        public BackupVolumeInfo[] CrossRegionBackupVolumeInfos{ get; set; }

        /// <summary>
        /// Cross-region information
        /// </summary>
        [JsonProperty("CrossRegions")]
        public string[] CrossRegions{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "BackupTotalVolume", this.BackupTotalVolume);
            this.SetParamSimple(map, prefix + "BackupSnapshotVolume", this.BackupSnapshotVolume);
            this.SetParamSimple(map, prefix + "BackupLogicVolume", this.BackupLogicVolume);
            this.SetParamSimple(map, prefix + "LogTotalVolume", this.LogTotalVolume);
            this.SetParamSimple(map, prefix + "LogBinlogVolume", this.LogBinlogVolume);
            this.SetParamSimple(map, prefix + "LogRedoLogVolume", this.LogRedoLogVolume);
            this.SetParamSimple(map, prefix + "CrossTotalVolume", this.CrossTotalVolume);
            this.SetParamSimple(map, prefix + "CrossRegionBackupVolume", this.CrossRegionBackupVolume);
            this.SetParamSimple(map, prefix + "CrossRegionLogVolume", this.CrossRegionLogVolume);
            this.SetParamArrayObj(map, prefix + "BackupVolumeInfos.", this.BackupVolumeInfos);
            this.SetParamArrayObj(map, prefix + "CrossRegionBackupVolumeInfos.", this.CrossRegionBackupVolumeInfos);
            this.SetParamArraySimple(map, prefix + "CrossRegions.", this.CrossRegions);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

