/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Intlpartnersmgt.V20220928.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeCustomerVoucherUsageDetailsResponse : AbstractModel
    {
        
        /// <summary>
        /// Voucher information details
        /// </summary>
        [JsonProperty("Data")]
        public UsageDetail[] Data{ get; set; }

        /// <summary>
        /// Customer UIN
        /// </summary>
        [JsonProperty("CustomerUin")]
        public long? CustomerUin{ get; set; }

        /// <summary>
        /// Voucher ID.
        /// </summary>
        [JsonProperty("VoucherId")]
        public long? VoucherId{ get; set; }

        /// <summary>
        /// Total voucher amount
        /// </summary>
        [JsonProperty("TotalAmount")]
        public float? TotalAmount{ get; set; }

        /// <summary>
        /// Voucher balance
        /// </summary>
        [JsonProperty("RemainAmount")]
        public float? RemainAmount{ get; set; }

        /// <summary>
        /// Total number of records
        /// </summary>
        [JsonProperty("TotalRecordsCount")]
        public long? TotalRecordsCount{ get; set; }

        /// <summary>
        /// Voucher Usage Month
        /// </summary>
        [JsonProperty("Month")]
        public string Month{ get; set; }

        /// <summary>
        /// Number of records in the current month
        /// </summary>
        [JsonProperty("RecordsCountByMonth")]
        public long? RecordsCountByMonth{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamArrayObj(map, prefix + "Data.", this.Data);
            this.SetParamSimple(map, prefix + "CustomerUin", this.CustomerUin);
            this.SetParamSimple(map, prefix + "VoucherId", this.VoucherId);
            this.SetParamSimple(map, prefix + "TotalAmount", this.TotalAmount);
            this.SetParamSimple(map, prefix + "RemainAmount", this.RemainAmount);
            this.SetParamSimple(map, prefix + "TotalRecordsCount", this.TotalRecordsCount);
            this.SetParamSimple(map, prefix + "Month", this.Month);
            this.SetParamSimple(map, prefix + "RecordsCountByMonth", this.RecordsCountByMonth);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

