/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Cdc.V20201214.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeDedicatedClusterOverviewResponse : AbstractModel
    {
        
        /// <summary>
        /// Number of CVMs
        /// </summary>
        [JsonProperty("CvmCount")]
        public ulong? CvmCount{ get; set; }

        /// <summary>
        /// Number of hosts
        /// </summary>
        [JsonProperty("HostCount")]
        public ulong? HostCount{ get; set; }

        /// <summary>
        /// VPN channel status 
        /// Note: The returned value of this field may be null, indicating that no valid value is obtained.
        /// </summary>
        [JsonProperty("VpnConnectionState")]
        public string VpnConnectionState{ get; set; }

        /// <summary>
        /// VPN gateway monitoring data 
        /// Note: The returned value of this field may be null, indicating that no valid value is obtained.
        /// </summary>
        [JsonProperty("VpngwBandwidthData")]
        public VpngwBandwidthData VpngwBandwidthData{ get; set; }

        /// <summary>
        /// Local gateway information 
        /// Note: The returned value of this field may be null, indicating that no valid value is obtained.
        /// </summary>
        [JsonProperty("LocalNetInfo")]
        public LocalNetInfo LocalNetInfo{ get; set; }

        /// <summary>
        /// VPN gateway channel monitoring data 
        /// Note: The returned value of this field may be null, indicating that no valid value is obtained.
        /// </summary>
        [JsonProperty("VpnConnectionBandwidthData")]
        public VpngwBandwidthData[] VpnConnectionBandwidthData{ get; set; }

        /// <summary>
        /// 
        /// </summary>
        [JsonProperty("HostDetailInfo")]
        public HostDetailInfo[] HostDetailInfo{ get; set; }

        /// <summary>
        /// 
        /// </summary>
        [JsonProperty("HostStandbyCount")]
        public ulong? HostStandbyCount{ get; set; }

        /// <summary>
        /// 
        /// </summary>
        [JsonProperty("HostNormalCount")]
        public ulong? HostNormalCount{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "CvmCount", this.CvmCount);
            this.SetParamSimple(map, prefix + "HostCount", this.HostCount);
            this.SetParamSimple(map, prefix + "VpnConnectionState", this.VpnConnectionState);
            this.SetParamObj(map, prefix + "VpngwBandwidthData.", this.VpngwBandwidthData);
            this.SetParamObj(map, prefix + "LocalNetInfo.", this.LocalNetInfo);
            this.SetParamArrayObj(map, prefix + "VpnConnectionBandwidthData.", this.VpnConnectionBandwidthData);
            this.SetParamArrayObj(map, prefix + "HostDetailInfo.", this.HostDetailInfo);
            this.SetParamSimple(map, prefix + "HostStandbyCount", this.HostStandbyCount);
            this.SetParamSimple(map, prefix + "HostNormalCount", this.HostNormalCount);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

