/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Ssm.V20190923.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeSupportedProductsResponse : AbstractModel
    {
        
        /// <summary>
        /// List of all supported Tencent Cloud products.
        /// The correspondence between each cloud product and secrets type is as follows:When `SecretType` is 1, the list of supported cloud products includes: Mysql, Tdsql-mysql, Tdsql_C_Mysql;When `SecretType` is 2, the supported product list is: Cvm;When `SecretType` is 3, the supported product list is: Cam (To use this function, you need to contact the cloud assistant to activate the allowlist separately);When `SecretType` is 4, the supported product list is: Redis.
        /// </summary>
        [JsonProperty("Products")]
        public string[] Products{ get; set; }

        /// <summary>
        /// Number of supported services
        /// </summary>
        [JsonProperty("TotalCount")]
        public long? TotalCount{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamArraySimple(map, prefix + "Products.", this.Products);
            this.SetParamSimple(map, prefix + "TotalCount", this.TotalCount);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

