/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Tdmq.V20200217.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class ExportRocketMQMessageDetailResponse : AbstractModel
    {
        
        /// <summary>
        /// Message ID
        /// </summary>
        [JsonProperty("MsgId")]
        public string MsgId{ get; set; }

        /// <summary>
        /// Message Generation Timestamp
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("BornTimestamp")]
        public long? BornTimestamp{ get; set; }

        /// <summary>
        /// Message Storage Timestamp
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("StoreTimestamp")]
        public long? StoreTimestamp{ get; set; }

        /// <summary>
        /// Message Production Client Address
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("BornHost")]
        public string BornHost{ get; set; }

        /// <summary>
        /// Message Tag
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("MsgTag")]
        public string MsgTag{ get; set; }

        /// <summary>
        /// Message key
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("MsgKey")]
        public string MsgKey{ get; set; }

        /// <summary>
        /// Message Attributes
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("Properties")]
        public string Properties{ get; set; }

        /// <summary>
        /// Message Retry Count
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("ReConsumeTimes")]
        public ulong? ReConsumeTimes{ get; set; }

        /// <summary>
        /// Base64 Encoded String
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("MsgBody")]
        public string MsgBody{ get; set; }

        /// <summary>
        /// CRC32 Code of Message Content
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("MsgBodyCRC")]
        public long? MsgBodyCRC{ get; set; }

        /// <summary>
        /// Specifies the message body size (unit K).
        /// Does not return messages when above 2048.
        /// </summary>
        [JsonProperty("MsgBodySize")]
        public ulong? MsgBodySize{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "MsgId", this.MsgId);
            this.SetParamSimple(map, prefix + "BornTimestamp", this.BornTimestamp);
            this.SetParamSimple(map, prefix + "StoreTimestamp", this.StoreTimestamp);
            this.SetParamSimple(map, prefix + "BornHost", this.BornHost);
            this.SetParamSimple(map, prefix + "MsgTag", this.MsgTag);
            this.SetParamSimple(map, prefix + "MsgKey", this.MsgKey);
            this.SetParamSimple(map, prefix + "Properties", this.Properties);
            this.SetParamSimple(map, prefix + "ReConsumeTimes", this.ReConsumeTimes);
            this.SetParamSimple(map, prefix + "MsgBody", this.MsgBody);
            this.SetParamSimple(map, prefix + "MsgBodyCRC", this.MsgBodyCRC);
            this.SetParamSimple(map, prefix + "MsgBodySize", this.MsgBodySize);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

