/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Mongodb.V20190725.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeBackupRulesResponse : AbstractModel
    {
        
        /// <summary>
        /// Retention period for backup data, in days.
        /// </summary>
        [JsonProperty("BackupSaveTime")]
        public ulong? BackupSaveTime{ get; set; }

        /// <summary>
        /// Backup frequency. Backup interval in hours. Value: 12, 24.
        /// </summary>
        [JsonProperty("BackupFrequency")]
        public long? BackupFrequency{ get; set; }

        /// <summary>
        /// Automatic backup start time.
        /// </summary>
        [JsonProperty("BackupTime")]
        public ulong? BackupTime{ get; set; }

        /// <summary>
        /// Backup mode.
        /// - 0: logical backup.
        /// - 1: physical backup.
        /// -3: Snapshot backup.
        /// **Description**:
        /// 1. The General Edition instance supports logical and physical backup. The Cloud Disk Edition instance supports physical and snapshot backup, but does not support logical backup currently.
        /// 2. Physical backup is not supported when storage encryption is enabled for the instance.
        /// </summary>
        [JsonProperty("BackupMethod")]
        public ulong? BackupMethod{ get; set; }

        /// <summary>
        /// Day of week for backup, 0-6, separated by commas
        /// </summary>
        [JsonProperty("ActiveWeekdays")]
        public string ActiveWeekdays{ get; set; }

        /// <summary>
        /// Long-term backup period. weekly - by week, monthly - by month, empty means not enabled.
        /// </summary>
        [JsonProperty("LongTermInterval")]
        public string LongTermInterval{ get; set; }

        /// <summary>
        /// Date of long-term backup, week 0-6, month 1-31
        /// </summary>
        [JsonProperty("LongTermActiveDays")]
        public string LongTermActiveDays{ get; set; }

        /// <summary>
        /// Long-term backup retention period
        /// </summary>
        [JsonProperty("LongTermExpiredDays")]
        public long? LongTermExpiredDays{ get; set; }

        /// <summary>
        /// Incremental backup retention period
        /// </summary>
        [JsonProperty("OplogExpiredDays")]
        public long? OplogExpiredDays{ get; set; }

        /// <summary>
        /// Backup version. 0 - Old backup method, 1 - Advanced backup.
        /// </summary>
        [JsonProperty("BackupVersion")]
        public long? BackupVersion{ get; set; }

        /// <summary>
        /// Backup size
        /// </summary>
        [JsonProperty("BackupTotalSize")]
        public BackupTotalSize BackupTotalSize{ get; set; }

        /// <summary>
        /// alarm limit
        /// </summary>
        [JsonProperty("AlertThreshold")]
        public long? AlertThreshold{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "BackupSaveTime", this.BackupSaveTime);
            this.SetParamSimple(map, prefix + "BackupFrequency", this.BackupFrequency);
            this.SetParamSimple(map, prefix + "BackupTime", this.BackupTime);
            this.SetParamSimple(map, prefix + "BackupMethod", this.BackupMethod);
            this.SetParamSimple(map, prefix + "ActiveWeekdays", this.ActiveWeekdays);
            this.SetParamSimple(map, prefix + "LongTermInterval", this.LongTermInterval);
            this.SetParamSimple(map, prefix + "LongTermActiveDays", this.LongTermActiveDays);
            this.SetParamSimple(map, prefix + "LongTermExpiredDays", this.LongTermExpiredDays);
            this.SetParamSimple(map, prefix + "OplogExpiredDays", this.OplogExpiredDays);
            this.SetParamSimple(map, prefix + "BackupVersion", this.BackupVersion);
            this.SetParamObj(map, prefix + "BackupTotalSize.", this.BackupTotalSize);
            this.SetParamSimple(map, prefix + "AlertThreshold", this.AlertThreshold);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

