/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Mongodb.V20190725.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeDBInstanceParamTplDetailResponse : AbstractModel
    {
        
        /// <summary>
        /// Enumeration class parameter details list.
        /// </summary>
        [JsonProperty("InstanceEnumParams")]
        public InstanceEnumParam[] InstanceEnumParams{ get; set; }

        /// <summary>
        /// Integer parameter detail list.
        /// </summary>
        [JsonProperty("InstanceIntegerParams")]
        public InstanceIntegerParam[] InstanceIntegerParams{ get; set; }

        /// <summary>
        /// Text parameter details list.
        /// </summary>
        [JsonProperty("InstanceTextParams")]
        public InstanceTextParam[] InstanceTextParams{ get; set; }

        /// <summary>
        /// Multi-value parameter details list.
        /// </summary>
        [JsonProperty("InstanceMultiParams")]
        public InstanceMultiParam[] InstanceMultiParams{ get; set; }

        /// <summary>
        /// Total number of parameters.
        /// </summary>
        [JsonProperty("TotalCount")]
        public long? TotalCount{ get; set; }

        /// <summary>
        /// Instance version supported by the template.
        /// - MONGO_36_WT: Version of the MongoDB 3.6 WiredTiger storage engine.
        /// - MONGO_40_WT: Version of the MongoDB 4.0 WiredTiger storage engine.
        /// - MONGO_42_WT: Version of the MongoDB 4.2 WiredTiger storage engine.
        /// - MONGO_44_WT: Version of the MongoDB 4.4 WiredTiger storage engine.
        /// - MONGO_50_WT: Version of the MongoDB 5.0 WiredTiger storage engine.
        /// - MONGO_60_WT: version of the MongoDB 6.0 WiredTiger storage engine.
        /// - MONGO_70_WT: version of the MongoDB 7.0 WiredTiger storage engine.
        /// - MONGO_80_WT: version of the MongoDB 8.0 WiredTiger storage engine.
        /// </summary>
        [JsonProperty("MongoVersion")]
        public string MongoVersion{ get; set; }

        /// <summary>
        /// Template adapts to cluster type.
        /// - REPLSET: replica set instance.
        /// - SHARD: shard instance.
        /// -STANDALONE: Single-node instance.
        /// </summary>
        [JsonProperty("ClusterType")]
        public string ClusterType{ get; set; }

        /// <summary>
        /// Parameter template name.
        /// </summary>
        [JsonProperty("TplName")]
        public string TplName{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamArrayObj(map, prefix + "InstanceEnumParams.", this.InstanceEnumParams);
            this.SetParamArrayObj(map, prefix + "InstanceIntegerParams.", this.InstanceIntegerParams);
            this.SetParamArrayObj(map, prefix + "InstanceTextParams.", this.InstanceTextParams);
            this.SetParamArrayObj(map, prefix + "InstanceMultiParams.", this.InstanceMultiParams);
            this.SetParamSimple(map, prefix + "TotalCount", this.TotalCount);
            this.SetParamSimple(map, prefix + "MongoVersion", this.MongoVersion);
            this.SetParamSimple(map, prefix + "ClusterType", this.ClusterType);
            this.SetParamSimple(map, prefix + "TplName", this.TplName);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

