/*
 * Copyright (c) 2018 THL A29 Limited, a Tencent company. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Trabbit.V20230418.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeRabbitMQServerlessInstanceResponse : AbstractModel
    {
        
        /// <summary>
        /// Cluster information.
        /// </summary>
        [JsonProperty("ClusterInfo")]
        public RabbitMQClusterInfo ClusterInfo{ get; set; }

        /// <summary>
        /// Specifies the cluster specification information.
        /// </summary>
        [JsonProperty("ClusterSpecInfo")]
        public RabbitMQClusterSpecInfo ClusterSpecInfo{ get; set; }

        /// <summary>
        /// Specifies the quota information of the vhost.
        /// </summary>
        [JsonProperty("VirtualHostQuota")]
        public VirtualHostQuota VirtualHostQuota{ get; set; }

        /// <summary>
        /// Specifies the exchange quota information.
        /// </summary>
        [JsonProperty("ExchangeQuota")]
        public ExchangeQuota ExchangeQuota{ get; set; }

        /// <summary>
        /// Specifies the quota information of the queue.
        /// </summary>
        [JsonProperty("QueueQuota")]
        public QueueQuota QueueQuota{ get; set; }

        /// <summary>
        /// Network information.
        /// </summary>
        [JsonProperty("ClusterNetInfo")]
        public RabbitMQServerlessAccessInfo ClusterNetInfo{ get; set; }

        /// <summary>
        /// Public network allowlist information.
        /// </summary>
        [JsonProperty("ClusterWhiteListInfo")]
        public RabbitMQServerlessWhiteListInfo ClusterWhiteListInfo{ get; set; }

        /// <summary>
        /// Specifies the quota information of the user.
        /// </summary>
        [JsonProperty("UserQuota")]
        public UserQuota UserQuota{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamObj(map, prefix + "ClusterInfo.", this.ClusterInfo);
            this.SetParamObj(map, prefix + "ClusterSpecInfo.", this.ClusterSpecInfo);
            this.SetParamObj(map, prefix + "VirtualHostQuota.", this.VirtualHostQuota);
            this.SetParamObj(map, prefix + "ExchangeQuota.", this.ExchangeQuota);
            this.SetParamObj(map, prefix + "QueueQuota.", this.QueueQuota);
            this.SetParamObj(map, prefix + "ClusterNetInfo.", this.ClusterNetInfo);
            this.SetParamObj(map, prefix + "ClusterWhiteListInfo.", this.ClusterWhiteListInfo);
            this.SetParamObj(map, prefix + "UserQuota.", this.UserQuota);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

