/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Sqlserver.V20180328.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeUpgradeInstanceCheckResponse : AbstractModel
    {
        
        /// <summary>
        /// Whether the configuration adjustment has an impact on the instance. 0 - no; 1 - yes.
        /// </summary>
        [JsonProperty("IsAffect")]
        public long? IsAffect{ get; set; }

        /// <summary>
        /// Whether the configuration adjustment can be executed. 0 - no; 1 - yes.
        /// </summary>
        [JsonProperty("Passed")]
        public long? Passed{ get; set; }

        /// <summary>
        /// Whether the configuration adjustment is a downgrade or an upgrade. Down - downgrade; up - upgrade.
        /// </summary>
        [JsonProperty("ModifyMode")]
        public string ModifyMode{ get; set; }

        /// <summary>
        /// Check item list.
        /// </summary>
        [JsonProperty("CheckItems")]
        public CheckItem[] CheckItems{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "IsAffect", this.IsAffect);
            this.SetParamSimple(map, prefix + "Passed", this.Passed);
            this.SetParamSimple(map, prefix + "ModifyMode", this.ModifyMode);
            this.SetParamArrayObj(map, prefix + "CheckItems.", this.CheckItems);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

