/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Sqlserver.V20180328.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeBackupMonitorResponse : AbstractModel
    {
        
        /// <summary>
        /// Backup trend chart timeline.
        /// </summary>
        [JsonProperty("TimeStamp")]
        public string[] TimeStamp{ get; set; }

        /// <summary>
        /// Free backup space.
        /// </summary>
        [JsonProperty("FreeSpace")]
        public float?[] FreeSpace{ get; set; }

        /// <summary>
        /// Actual total backup space.
        /// </summary>
        [JsonProperty("ActualUsedSpace")]
        public float?[] ActualUsedSpace{ get; set; }

        /// <summary>
        /// Backup space for logs.
        /// </summary>
        [JsonProperty("LogBackupSpace")]
        public float?[] LogBackupSpace{ get; set; }

        /// <summary>
        /// Backup space for data.
        /// </summary>
        [JsonProperty("DataBackupSpace")]
        public float?[] DataBackupSpace{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamArraySimple(map, prefix + "TimeStamp.", this.TimeStamp);
            this.SetParamArraySimple(map, prefix + "FreeSpace.", this.FreeSpace);
            this.SetParamArraySimple(map, prefix + "ActualUsedSpace.", this.ActualUsedSpace);
            this.SetParamArraySimple(map, prefix + "LogBackupSpace.", this.LogBackupSpace);
            this.SetParamArraySimple(map, prefix + "DataBackupSpace.", this.DataBackupSpace);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

