/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Lke.V20231130.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeTokenUsageResponse : AbstractModel
    {
        
        /// <summary>
        /// Total token consumption.
        /// </summary>
        [JsonProperty("TotalTokenUsage")]
        public float? TotalTokenUsage{ get; set; }

        /// <summary>
        /// Input token consumption.
        /// </summary>
        [JsonProperty("InputTokenUsage")]
        public float? InputTokenUsage{ get; set; }

        /// <summary>
        /// Output token consumption.
        /// </summary>
        [JsonProperty("OutputTokenUsage")]
        public float? OutputTokenUsage{ get; set; }

        /// <summary>
        /// Number of API calls.
        /// </summary>
        [JsonProperty("ApiCallStats")]
        public ulong? ApiCallStats{ get; set; }

        /// <summary>
        /// Number of search service calls.
        /// </summary>
        [JsonProperty("SearchUsage")]
        public float? SearchUsage{ get; set; }

        /// <summary>
        /// Number of pages consumed by document parsing.
        /// </summary>
        [JsonProperty("PageUsage")]
        public ulong? PageUsage{ get; set; }

        /// <summary>
        /// Token consumption by splitting.
        /// </summary>
        [JsonProperty("SplitTokenUsage")]
        public float? SplitTokenUsage{ get; set; }

        /// <summary>
        /// Number of Rag retrievals.
        /// </summary>
        [JsonProperty("RagSearchUsage")]
        public float? RagSearchUsage{ get; set; }

        /// <summary>
        /// Number of online searches.
        /// </summary>
        [JsonProperty("InternetSearchUsage")]
        public float? InternetSearchUsage{ get; set; }

        /// <summary>
        /// 
        /// </summary>
        [JsonProperty("DosageTypeLimit")]
        public float? DosageTypeLimit{ get; set; }

        /// <summary>
        /// 
        /// </summary>
        [JsonProperty("DosageTypeCurr")]
        public float? DosageTypeCurr{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "TotalTokenUsage", this.TotalTokenUsage);
            this.SetParamSimple(map, prefix + "InputTokenUsage", this.InputTokenUsage);
            this.SetParamSimple(map, prefix + "OutputTokenUsage", this.OutputTokenUsage);
            this.SetParamSimple(map, prefix + "ApiCallStats", this.ApiCallStats);
            this.SetParamSimple(map, prefix + "SearchUsage", this.SearchUsage);
            this.SetParamSimple(map, prefix + "PageUsage", this.PageUsage);
            this.SetParamSimple(map, prefix + "SplitTokenUsage", this.SplitTokenUsage);
            this.SetParamSimple(map, prefix + "RagSearchUsage", this.RagSearchUsage);
            this.SetParamSimple(map, prefix + "InternetSearchUsage", this.InternetSearchUsage);
            this.SetParamSimple(map, prefix + "DosageTypeLimit", this.DosageTypeLimit);
            this.SetParamSimple(map, prefix + "DosageTypeCurr", this.DosageTypeCurr);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

