/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Lke.V20231130.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeCorpResponse : AbstractModel
    {
        
        /// <summary>
        /// Corporate ID.
        /// </summary>
        [JsonProperty("CorpBizId")]
        public string CorpBizId{ get; set; }

        /// <summary>
        /// Application quota.
        /// </summary>
        [JsonProperty("RobotQuota")]
        public ulong? RobotQuota{ get; set; }

        /// <summary>
        /// Full name of the corporate.
        /// </summary>
        [JsonProperty("FullName")]
        public string FullName{ get; set; }

        /// <summary>
        /// Whether to try out.
        /// </summary>
        [JsonProperty("IsTrial")]
        public bool? IsTrial{ get; set; }

        /// <summary>
        /// Whether the trial has expired.
        /// </summary>
        [JsonProperty("IsTrialExpired")]
        public bool? IsTrialExpired{ get; set; }

        /// <summary>
        /// Quantity of available applications.
        /// </summary>
        [JsonProperty("AvailableAppQuota")]
        public ulong? AvailableAppQuota{ get; set; }

        /// <summary>
        /// Whether custom model configuration is supported.
        /// </summary>
        [JsonProperty("IsSupportCustomModel")]
        public bool? IsSupportCustomModel{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "CorpBizId", this.CorpBizId);
            this.SetParamSimple(map, prefix + "RobotQuota", this.RobotQuota);
            this.SetParamSimple(map, prefix + "FullName", this.FullName);
            this.SetParamSimple(map, prefix + "IsTrial", this.IsTrial);
            this.SetParamSimple(map, prefix + "IsTrialExpired", this.IsTrialExpired);
            this.SetParamSimple(map, prefix + "AvailableAppQuota", this.AvailableAppQuota);
            this.SetParamSimple(map, prefix + "IsSupportCustomModel", this.IsSupportCustomModel);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

