/*
 * Copyright (c) 2018 THL A29 Limited, a Tencent company. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Lke.V20231130.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeAppResponse : AbstractModel
    {
        
        /// <summary>
        /// Application ID.
        /// </summary>
        [JsonProperty("AppBizId")]
        public string AppBizId{ get; set; }

        /// <summary>
        /// Application type; knowledge_qa - knowledge Q&A management; summary - knowledge summary; classifys - knowledge label extraction.
        /// </summary>
        [JsonProperty("AppType")]
        public string AppType{ get; set; }

        /// <summary>
        /// Application type description.
        /// </summary>
        [JsonProperty("AppTypeDesc")]
        public string AppTypeDesc{ get; set; }

        /// <summary>
        /// Application type description.
        /// </summary>
        [JsonProperty("BaseConfig")]
        public BaseConfig BaseConfig{ get; set; }

        /// <summary>
        /// Application configuration.
        /// </summary>
        [JsonProperty("AppConfig")]
        public AppConfig AppConfig{ get; set; }

        /// <summary>
        /// Whether the avatar is under appeal.
        /// </summary>
        [JsonProperty("AvatarInAppeal")]
        public bool? AvatarInAppeal{ get; set; }

        /// <summary>
        /// Whether the role description is under appeal.
        /// </summary>
        [JsonProperty("RoleInAppeal")]
        public bool? RoleInAppeal{ get; set; }

        /// <summary>
        /// Whether the name is under appeal.
        /// </summary>
        [JsonProperty("NameInAppeal")]
        public bool? NameInAppeal{ get; set; }

        /// <summary>
        /// Whether the welcome words are under appeal.
        /// </summary>
        [JsonProperty("GreetingInAppeal")]
        public bool? GreetingInAppeal{ get; set; }

        /// <summary>
        /// Whether the response message for unknown questions is under appeal.
        /// </summary>
        [JsonProperty("BareAnswerInAppeal")]
        public bool? BareAnswerInAppeal{ get; set; }

        /// <summary>
        /// App key of the application.
        /// </summary>
        [JsonProperty("AppKey")]
        public string AppKey{ get; set; }

        /// <summary>
        /// Application status. 1: offline; 2: running; 3: disabled.
        /// </summary>
        [JsonProperty("AppStatus")]
        public ulong? AppStatus{ get; set; }

        /// <summary>
        /// Status description.
        /// </summary>
        [JsonProperty("AppStatusDesc")]
        public string AppStatusDesc{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "AppBizId", this.AppBizId);
            this.SetParamSimple(map, prefix + "AppType", this.AppType);
            this.SetParamSimple(map, prefix + "AppTypeDesc", this.AppTypeDesc);
            this.SetParamObj(map, prefix + "BaseConfig.", this.BaseConfig);
            this.SetParamObj(map, prefix + "AppConfig.", this.AppConfig);
            this.SetParamSimple(map, prefix + "AvatarInAppeal", this.AvatarInAppeal);
            this.SetParamSimple(map, prefix + "RoleInAppeal", this.RoleInAppeal);
            this.SetParamSimple(map, prefix + "NameInAppeal", this.NameInAppeal);
            this.SetParamSimple(map, prefix + "GreetingInAppeal", this.GreetingInAppeal);
            this.SetParamSimple(map, prefix + "BareAnswerInAppeal", this.BareAnswerInAppeal);
            this.SetParamSimple(map, prefix + "AppKey", this.AppKey);
            this.SetParamSimple(map, prefix + "AppStatus", this.AppStatus);
            this.SetParamSimple(map, prefix + "AppStatusDesc", this.AppStatusDesc);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

