/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Mariadb.V20170312.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeDBLogFilesResponse : AbstractModel
    {
        
        /// <summary>
        /// Instance ID in the format of `tdsql-ow728lmc`.
        /// </summary>
        [JsonProperty("InstanceId")]
        public string InstanceId{ get; set; }

        /// <summary>
        /// Requested log type. Valid values: 1 (binlog), 2 (cold backup), 3 (errlog), 4 (slowlog).
        /// </summary>
        [JsonProperty("Type")]
        public ulong? Type{ get; set; }

        /// <summary>
        /// Total number of requested logs
        /// </summary>
        [JsonProperty("Total")]
        public ulong? Total{ get; set; }

        /// <summary>
        /// Information such as `uri`, `length`, and `mtime` (modification time)
        /// </summary>
        [JsonProperty("Files")]
        public LogFileInfo[] Files{ get; set; }

        /// <summary>
        /// For an instance in a VPC, this prefix plus URI can be used as the download address
        /// </summary>
        [JsonProperty("VpcPrefix")]
        public string VpcPrefix{ get; set; }

        /// <summary>
        /// For an instance in a common network, this prefix plus URI can be used as the download address
        /// </summary>
        [JsonProperty("NormalPrefix")]
        public string NormalPrefix{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "InstanceId", this.InstanceId);
            this.SetParamSimple(map, prefix + "Type", this.Type);
            this.SetParamSimple(map, prefix + "Total", this.Total);
            this.SetParamArrayObj(map, prefix + "Files.", this.Files);
            this.SetParamSimple(map, prefix + "VpcPrefix", this.VpcPrefix);
            this.SetParamSimple(map, prefix + "NormalPrefix", this.NormalPrefix);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

