/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Csip.V20221121.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeClusterAssetsResponse : AbstractModel
    {
        
        /// <summary>
        /// List
        /// </summary>
        [JsonProperty("Data")]
        public AssetCluster[] Data{ get; set; }

        /// <summary>
        /// Total number.
        /// </summary>
        [JsonProperty("TotalCount")]
        public long? TotalCount{ get; set; }

        /// <summary>
        /// Cluster Type Enumeration
        /// </summary>
        [JsonProperty("ClusterTypeList")]
        public FilterDataObject[] ClusterTypeList{ get; set; }

        /// <summary>
        /// Cluster Status Enumeration
        /// </summary>
        [JsonProperty("ClusterStatusList")]
        public FilterDataObject[] ClusterStatusList{ get; set; }

        /// <summary>
        /// Component Status Enumeration
        /// </summary>
        [JsonProperty("ComponentStatusList")]
        public FilterDataObject[] ComponentStatusList{ get; set; }

        /// <summary>
        /// VPC Enumeration
        /// </summary>
        [JsonProperty("VpcList")]
        public FilterDataObject[] VpcList{ get; set; }

        /// <summary>
        /// Region Enumeration
        /// </summary>
        [JsonProperty("RegionList")]
        public FilterDataObject[] RegionList{ get; set; }

        /// <summary>
        /// Tenant Enumeration
        /// </summary>
        [JsonProperty("AppIdList")]
        public FilterDataObject[] AppIdList{ get; set; }

        /// <summary>
        /// Cluster protection status enumeration.
        /// </summary>
        [JsonProperty("ProtectStatusList")]
        public FilterDataObject[] ProtectStatusList{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamArrayObj(map, prefix + "Data.", this.Data);
            this.SetParamSimple(map, prefix + "TotalCount", this.TotalCount);
            this.SetParamArrayObj(map, prefix + "ClusterTypeList.", this.ClusterTypeList);
            this.SetParamArrayObj(map, prefix + "ClusterStatusList.", this.ClusterStatusList);
            this.SetParamArrayObj(map, prefix + "ComponentStatusList.", this.ComponentStatusList);
            this.SetParamArrayObj(map, prefix + "VpcList.", this.VpcList);
            this.SetParamArrayObj(map, prefix + "RegionList.", this.RegionList);
            this.SetParamArrayObj(map, prefix + "AppIdList.", this.AppIdList);
            this.SetParamArrayObj(map, prefix + "ProtectStatusList.", this.ProtectStatusList);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

