/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Csip.V20221121.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeSecurityScoreOverviewResponse : AbstractModel
    {
        
        /// <summary>
        /// <p>Security score<br>Value range: [0, 100]</p>
        /// </summary>
        [JsonProperty("Score")]
        public long? Score{ get; set; }

        /// <summary>
        /// <p>Security level<br>Enumeration values:<br>safe: safe (90-100 points)<br>good: good (70-89 points)<br>medium: general (40-69 points)<br>danger: dangerous (0-39 points)</p>
        /// </summary>
        [JsonProperty("Level")]
        public string Level{ get; set; }

        /// <summary>
        /// <p>Score status<br>Enumeration values:<br>success: All data sources are normal<br>partial_error: Some data sources used cache<br>stale: Used the last complete snapshot<br>error: Unable to calculate</p>
        /// </summary>
        [JsonProperty("ScoreStatus")]
        public string ScoreStatus{ get; set; }

        /// <summary>
        /// <p>Initial score<br>Default value: 100</p>
        /// </summary>
        [JsonProperty("InitialScore")]
        public long? InitialScore{ get; set; }

        /// <summary>
        /// <p>Number of categories with risks (it is advisable to process category X risks as soon as possible)</p>
        /// </summary>
        [JsonProperty("RiskCategoryCount")]
        public long? RiskCategoryCount{ get; set; }

        /// <summary>
        /// <p>Total point deduction.</p>
        /// </summary>
        [JsonProperty("DeductScore")]
        public long? DeductScore{ get; set; }

        /// <summary>
        /// <p>Calculation time<br>Parameter format: YYYY-MM-DDTHH:mm:ss+08:00</p>
        /// </summary>
        [JsonProperty("CalculatedAt")]
        public string CalculatedAt{ get; set; }

        /// <summary>
        /// <p>Dimension details, including sub-item point deductions and to-do items</p>
        /// </summary>
        [JsonProperty("Dimensions")]
        public DimensionItem[] Dimensions{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "Score", this.Score);
            this.SetParamSimple(map, prefix + "Level", this.Level);
            this.SetParamSimple(map, prefix + "ScoreStatus", this.ScoreStatus);
            this.SetParamSimple(map, prefix + "InitialScore", this.InitialScore);
            this.SetParamSimple(map, prefix + "RiskCategoryCount", this.RiskCategoryCount);
            this.SetParamSimple(map, prefix + "DeductScore", this.DeductScore);
            this.SetParamSimple(map, prefix + "CalculatedAt", this.CalculatedAt);
            this.SetParamArrayObj(map, prefix + "Dimensions.", this.Dimensions);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

