/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Csip.V20221121.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeCWPScanIpInfoResponse : AbstractModel
    {
        
        /// <summary>
        /// <p>Associated business</p>
        /// </summary>
        [JsonProperty("Bussiness")]
        public string Bussiness{ get; set; }

        /// <summary>
        /// <p>Business characteristic</p>
        /// </summary>
        [JsonProperty("Characteristic")]
        public string Characteristic{ get; set; }

        /// <summary>
        /// <p>Description.</p>
        /// </summary>
        [JsonProperty("Describe")]
        public string Describe{ get; set; }

        /// <summary>
        /// <p>Official announcement</p>
        /// </summary>
        [JsonProperty("Referer")]
        public string Referer{ get; set; }

        /// <summary>
        /// <p>Scan example</p>
        /// </summary>
        [JsonProperty("Demo")]
        public string Demo{ get; set; }

        /// <summary>
        /// <p>Scan target</p>
        /// </summary>
        [JsonProperty("Target")]
        public string Target{ get; set; }

        /// <summary>
        /// <p>Scan target</p>
        /// </summary>
        [JsonProperty("Purpose")]
        public string Purpose{ get; set; }

        /// <summary>
        /// <p>Product copywriting</p>
        /// </summary>
        [JsonProperty("Announcement")]
        public string Announcement{ get; set; }

        /// <summary>
        /// <p>Geographic location</p>
        /// </summary>
        [JsonProperty("Location")]
        public string Location{ get; set; }

        /// <summary>
        /// <p>Associated operator</p>
        /// </summary>
        [JsonProperty("ISP")]
        public string ISP{ get; set; }

        /// <summary>
        /// <p>Whether it belongs to Tencent</p>
        /// </summary>
        [JsonProperty("IsBelongTencent")]
        public bool? IsBelongTencent{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "Bussiness", this.Bussiness);
            this.SetParamSimple(map, prefix + "Characteristic", this.Characteristic);
            this.SetParamSimple(map, prefix + "Describe", this.Describe);
            this.SetParamSimple(map, prefix + "Referer", this.Referer);
            this.SetParamSimple(map, prefix + "Demo", this.Demo);
            this.SetParamSimple(map, prefix + "Target", this.Target);
            this.SetParamSimple(map, prefix + "Purpose", this.Purpose);
            this.SetParamSimple(map, prefix + "Announcement", this.Announcement);
            this.SetParamSimple(map, prefix + "Location", this.Location);
            this.SetParamSimple(map, prefix + "ISP", this.ISP);
            this.SetParamSimple(map, prefix + "IsBelongTencent", this.IsBelongTencent);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

