/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Csip.V20221121.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeDspmIdentifyInfoResponse : AbstractModel
    {
        
        /// <summary>
        /// Identity ID
        /// </summary>
        [JsonProperty("IdentifyId")]
        public string IdentifyId{ get; set; }

        /// <summary>
        /// Identity statistical information
        /// </summary>
        [JsonProperty("IdentifyCount")]
        public DspmIdentifyCount[] IdentifyCount{ get; set; }

        /// <summary>
        /// Application count
        /// </summary>
        [JsonProperty("ApplyOrderCount")]
        public long? ApplyOrderCount{ get; set; }

        /// <summary>
        /// Number of approval forms
        /// </summary>
        [JsonProperty("ApproveOrderCount")]
        public long? ApproveOrderCount{ get; set; }

        /// <summary>
        /// Approved count
        /// </summary>
        [JsonProperty("ApproveHistoryCount")]
        public long? ApproveHistoryCount{ get; set; }

        /// <summary>
        /// Total number of assets
        /// </summary>
        [JsonProperty("AssetCount")]
        public long? AssetCount{ get; set; }

        /// <summary>
        /// Total number of cloud accounts
        /// </summary>
        [JsonProperty("UinAccountCount")]
        public long? UinAccountCount{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "IdentifyId", this.IdentifyId);
            this.SetParamArrayObj(map, prefix + "IdentifyCount.", this.IdentifyCount);
            this.SetParamSimple(map, prefix + "ApplyOrderCount", this.ApplyOrderCount);
            this.SetParamSimple(map, prefix + "ApproveOrderCount", this.ApproveOrderCount);
            this.SetParamSimple(map, prefix + "ApproveHistoryCount", this.ApproveHistoryCount);
            this.SetParamSimple(map, prefix + "AssetCount", this.AssetCount);
            this.SetParamSimple(map, prefix + "UinAccountCount", this.UinAccountCount);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

