/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Csip.V20221121.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeRiskCenterCFGViewCFGRiskListResponse : AbstractModel
    {
        
        /// <summary>
        /// Total number of entries
        /// </summary>
        [JsonProperty("TotalCount")]
        public long? TotalCount{ get; set; }

        /// <summary>
        /// Configuration Risk List from Asset's Perspective
        /// </summary>
        [JsonProperty("Data")]
        public CFGViewCFGRisk[] Data{ get; set; }

        /// <summary>
        /// Status list
        /// </summary>
        [JsonProperty("StatusLists")]
        public FilterDataObject[] StatusLists{ get; set; }

        /// <summary>
        /// Danger Level List
        /// </summary>
        [JsonProperty("LevelLists")]
        public FilterDataObject[] LevelLists{ get; set; }

        /// <summary>
        /// Configuration Name List
        /// </summary>
        [JsonProperty("CFGNameLists")]
        public FilterDataObject[] CFGNameLists{ get; set; }

        /// <summary>
        /// Check Type List
        /// </summary>
        [JsonProperty("CheckTypeLists")]
        public FilterDataObject[] CheckTypeLists{ get; set; }

        /// <summary>
        /// Asset Type List
        /// </summary>
        [JsonProperty("InstanceTypeLists")]
        public FilterDataObject[] InstanceTypeLists{ get; set; }

        /// <summary>
        /// Source List
        /// </summary>
        [JsonProperty("FromLists")]
        public FilterDataObject[] FromLists{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "TotalCount", this.TotalCount);
            this.SetParamArrayObj(map, prefix + "Data.", this.Data);
            this.SetParamArrayObj(map, prefix + "StatusLists.", this.StatusLists);
            this.SetParamArrayObj(map, prefix + "LevelLists.", this.LevelLists);
            this.SetParamArrayObj(map, prefix + "CFGNameLists.", this.CFGNameLists);
            this.SetParamArrayObj(map, prefix + "CheckTypeLists.", this.CheckTypeLists);
            this.SetParamArrayObj(map, prefix + "InstanceTypeLists.", this.InstanceTypeLists);
            this.SetParamArrayObj(map, prefix + "FromLists.", this.FromLists);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

