/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Csip.V20221121.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeAgentConfigSettingResponse : AbstractModel
    {
        
        /// <summary>
        /// <p>Enhancement log mode switch. 0: turn off; 1: turn on (empty if not configured)</p>
        /// </summary>
        [JsonProperty("EnhanceLogMode")]
        public ulong? EnhanceLogMode{ get; set; }

        /// <summary>
        /// <p>Malware POC mode switch. 0: Turn off. 1: Turn on. (Empty if not configured)</p>
        /// </summary>
        [JsonProperty("MalwarePocMode")]
        public ulong? MalwarePocMode{ get; set; }

        /// <summary>
        /// <p>Report source port switch (compatible with old versions). 0: off, 1: on</p>
        /// </summary>
        [JsonProperty("ReportSourcePort")]
        public ulong? ReportSourcePort{ get; set; }

        /// <summary>
        /// <p>List of enabled log collection types, for example, tcp_ingress, tcp_src_port, http_egress, http_ingress, app_access</p>
        /// </summary>
        [JsonProperty("LogCollectSettings")]
        public string[] LogCollectSettings{ get; set; }

        /// <summary>
        /// <p>Asset selection method: all/tag/direct</p>
        /// </summary>
        [JsonProperty("AssetSelectionType")]
        public string AssetSelectionType{ get; set; }

        /// <summary>
        /// <p>Tag ID array used when selecting by tag</p>
        /// </summary>
        [JsonProperty("TagIds")]
        public string[] TagIds{ get; set; }

        /// <summary>
        /// <p>direct selection of the host instance_id list</p>
        /// </summary>
        [JsonProperty("InstanceIDs")]
        public string[] InstanceIDs{ get; set; }

        /// <summary>
        /// <p>Exclusion instance_id list of the host</p>
        /// </summary>
        [JsonProperty("ExcludeInstanceIDs")]
        public string[] ExcludeInstanceIDs{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "EnhanceLogMode", this.EnhanceLogMode);
            this.SetParamSimple(map, prefix + "MalwarePocMode", this.MalwarePocMode);
            this.SetParamSimple(map, prefix + "ReportSourcePort", this.ReportSourcePort);
            this.SetParamArraySimple(map, prefix + "LogCollectSettings.", this.LogCollectSettings);
            this.SetParamSimple(map, prefix + "AssetSelectionType", this.AssetSelectionType);
            this.SetParamArraySimple(map, prefix + "TagIds.", this.TagIds);
            this.SetParamArraySimple(map, prefix + "InstanceIDs.", this.InstanceIDs);
            this.SetParamArraySimple(map, prefix + "ExcludeInstanceIDs.", this.ExcludeInstanceIDs);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

