/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Csip.V20221121.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeCSIPLicenseBindScheduleResponse : AbstractModel
    {
        
        /// <summary>
        /// <p>Task ID.</p>
        /// </summary>
        [JsonProperty("TaskId")]
        public ulong? TaskId{ get; set; }

        /// <summary>
        /// <p>Task status: INIT-initialization / RUNNING-in-progress / DONE-completed / FAILED-failed</p>
        /// </summary>
        [JsonProperty("Status")]
        public string Status{ get; set; }

        /// <summary>
        /// <p>Progress percentage 0-100</p>
        /// </summary>
        [JsonProperty("Schedule")]
        public long? Schedule{ get; set; }

        /// <summary>
        /// <p>Number of all machines (unaffected by filtering)</p>
        /// </summary>
        [JsonProperty("Total")]
        public long? Total{ get; set; }

        /// <summary>
        /// <p>Number of successes</p>
        /// </summary>
        [JsonProperty("SuccessNum")]
        public long? SuccessNum{ get; set; }

        /// <summary>
        /// <p>failure count</p>
        /// </summary>
        [JsonProperty("FailedNum")]
        public long? FailedNum{ get; set; }

        /// <summary>
        /// <p>Failure detail (full, including additional machine information)</p>
        /// </summary>
        [JsonProperty("FailedList")]
        public LicenseBindFailedItem[] FailedList{ get; set; }

        /// <summary>
        /// <p>Detail by machine (affected by Filters and pagination)</p>
        /// </summary>
        [JsonProperty("List")]
        public LicenseBindScheduleItem[] List{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "TaskId", this.TaskId);
            this.SetParamSimple(map, prefix + "Status", this.Status);
            this.SetParamSimple(map, prefix + "Schedule", this.Schedule);
            this.SetParamSimple(map, prefix + "Total", this.Total);
            this.SetParamSimple(map, prefix + "SuccessNum", this.SuccessNum);
            this.SetParamSimple(map, prefix + "FailedNum", this.FailedNum);
            this.SetParamArrayObj(map, prefix + "FailedList.", this.FailedList);
            this.SetParamArrayObj(map, prefix + "List.", this.List);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

