/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Csip.V20221121.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeCheckViewRisksResponse : AbstractModel
    {
        
        /// <summary>
        /// <p>Number of risks from check perspective</p>
        /// </summary>
        [JsonProperty("TotalCount")]
        public long? TotalCount{ get; set; }

        /// <summary>
        /// <p>Risk list in check perspective</p>
        /// </summary>
        [JsonProperty("CheckViewRiskList")]
        public CheckViewRiskItem[] CheckViewRiskList{ get; set; }

        /// <summary>
        /// <p>Tag list of cspm standard from a checking perspective</p>
        /// </summary>
        [JsonProperty("StandardNameList")]
        public StandardItem[] StandardNameList{ get; set; }

        /// <summary>
        /// <p>Asset type collection</p>
        /// </summary>
        [JsonProperty("AssetTypeList")]
        public AttributeOptionSet[] AssetTypeList{ get; set; }

        /// <summary>
        /// <p>Cloud vendor type collection</p>
        /// </summary>
        [JsonProperty("ProviderList")]
        public AttributeOptionSet[] ProviderList{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "TotalCount", this.TotalCount);
            this.SetParamArrayObj(map, prefix + "CheckViewRiskList.", this.CheckViewRiskList);
            this.SetParamArrayObj(map, prefix + "StandardNameList.", this.StandardNameList);
            this.SetParamArrayObj(map, prefix + "AssetTypeList.", this.AssetTypeList);
            this.SetParamArrayObj(map, prefix + "ProviderList.", this.ProviderList);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

