/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Csip.V20221121.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeKeySandboxCredentialResponse : AbstractModel
    {
        
        /// <summary>
        /// Credential ID
        /// </summary>
        [JsonProperty("CredentialId")]
        public string CredentialId{ get; set; }

        /// <summary>
        /// Credential name
        /// </summary>
        [JsonProperty("CredentialName")]
        public string CredentialName{ get; set; }

        /// <summary>
        /// Credential type
        /// Enumeration values:
        /// access: standard key
        /// sts: STS temporary key
        /// </summary>
        [JsonProperty("CredentialType")]
        public string CredentialType{ get; set; }

        /// <summary>
        /// Scope of effective machines
        /// </summary>
        [JsonProperty("CredentialEffectScope")]
        public CredentialEffectScope CredentialEffectScope{ get; set; }

        /// <summary>
        /// Normal key credential data (masked). Returned when CredentialType is access.
        /// Supplemental description: Key is the original text, and Value is the masked value (first 3 and last 4 characters retained, middle replaced by ***).
        /// </summary>
        [JsonProperty("Access")]
        public AccessCredentialOutput[] Access{ get; set; }

        /// <summary>
        /// STS credential data (masked). Returned when CredentialType is sts.
        /// Supplemental description: System is the original text. SecretID and SecretKey are masked values (first 3 and last 4 characters reserved, middle replaced with ***).
        /// </summary>
        [JsonProperty("STS")]
        public STSCredentialOutput STS{ get; set; }

        /// <summary>
        /// Creation time.
        /// Parameter format: YYYY-MM-DDTHH:mm:ssZ (ISO8601 format)
        /// </summary>
        [JsonProperty("CreateTime")]
        public string CreateTime{ get; set; }

        /// <summary>
        /// Update time
        /// Parameter format: YYYY-MM-DDTHH:mm:ssZ (ISO8601 format)
        /// </summary>
        [JsonProperty("UpdateTime")]
        public string UpdateTime{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "CredentialId", this.CredentialId);
            this.SetParamSimple(map, prefix + "CredentialName", this.CredentialName);
            this.SetParamSimple(map, prefix + "CredentialType", this.CredentialType);
            this.SetParamObj(map, prefix + "CredentialEffectScope.", this.CredentialEffectScope);
            this.SetParamArrayObj(map, prefix + "Access.", this.Access);
            this.SetParamObj(map, prefix + "STS.", this.STS);
            this.SetParamSimple(map, prefix + "CreateTime", this.CreateTime);
            this.SetParamSimple(map, prefix + "UpdateTime", this.UpdateTime);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

