/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Csip.V20221121.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeCFWAssetStatisticsResponse : AbstractModel
    {
        
        /// <summary>
        /// Total number of network assets
        /// </summary>
        [JsonProperty("NetworkTotal")]
        public long? NetworkTotal{ get; set; }

        /// <summary>
        /// Asset CLB Quantity
        /// </summary>
        [JsonProperty("ClbTotal")]
        public long? ClbTotal{ get; set; }

        /// <summary>
        /// Number of NATs
        /// </summary>
        [JsonProperty("NatTotal")]
        public long? NatTotal{ get; set; }

        /// <summary>
        /// Number of Public IP Addresses
        /// </summary>
        [JsonProperty("PublicAssetTotal")]
        public long? PublicAssetTotal{ get; set; }

        /// <summary>
        /// Number of hosts
        /// </summary>
        [JsonProperty("CVMAssetTotal")]
        public long? CVMAssetTotal{ get; set; }

        /// <summary>
        /// Configuration risk.
        /// </summary>
        [JsonProperty("CFGTotal")]
        public long? CFGTotal{ get; set; }

        /// <summary>
        /// Port risk.
        /// </summary>
        [JsonProperty("PortTotal")]
        public long? PortTotal{ get; set; }

        /// <summary>
        /// Content risk.
        /// </summary>
        [JsonProperty("WebsiteTotal")]
        public long? WebsiteTotal{ get; set; }

        /// <summary>
        /// Risk service exposure.
        /// </summary>
        [JsonProperty("ServerTotal")]
        public long? ServerTotal{ get; set; }

        /// <summary>
        /// Weak password risk.
        /// </summary>
        [JsonProperty("WeakPasswordTotal")]
        public long? WeakPasswordTotal{ get; set; }

        /// <summary>
        /// Vulnerability risk.
        /// </summary>
        [JsonProperty("VULTotal")]
        public long? VULTotal{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "NetworkTotal", this.NetworkTotal);
            this.SetParamSimple(map, prefix + "ClbTotal", this.ClbTotal);
            this.SetParamSimple(map, prefix + "NatTotal", this.NatTotal);
            this.SetParamSimple(map, prefix + "PublicAssetTotal", this.PublicAssetTotal);
            this.SetParamSimple(map, prefix + "CVMAssetTotal", this.CVMAssetTotal);
            this.SetParamSimple(map, prefix + "CFGTotal", this.CFGTotal);
            this.SetParamSimple(map, prefix + "PortTotal", this.PortTotal);
            this.SetParamSimple(map, prefix + "WebsiteTotal", this.WebsiteTotal);
            this.SetParamSimple(map, prefix + "ServerTotal", this.ServerTotal);
            this.SetParamSimple(map, prefix + "WeakPasswordTotal", this.WeakPasswordTotal);
            this.SetParamSimple(map, prefix + "VULTotal", this.VULTotal);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

