/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Csip.V20221121.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeCVMAssetsResponse : AbstractModel
    {
        
        /// <summary>
        /// Total number.
        /// </summary>
        [JsonProperty("Total")]
        public ulong? Total{ get; set; }

        /// <summary>
        /// Machine list
        /// </summary>
        [JsonProperty("Data")]
        public CVMAssetVO[] Data{ get; set; }

        /// <summary>
        /// Region list
        /// </summary>
        [JsonProperty("RegionList")]
        public FilterDataObject[] RegionList{ get; set; }

        /// <summary>
        /// Protection status
        /// </summary>
        [JsonProperty("DefenseStatusList")]
        public FilterDataObject[] DefenseStatusList{ get; set; }

        /// <summary>
        /// VPC Enumeration
        /// </summary>
        [JsonProperty("VpcList")]
        public FilterDataObject[] VpcList{ get; set; }

        /// <summary>
        /// Asset Type Enumeration
        /// </summary>
        [JsonProperty("AssetTypeList")]
        public FilterDataObject[] AssetTypeList{ get; set; }

        /// <summary>
        /// Operating System Enumeration
        /// </summary>
        [JsonProperty("SystemTypeList")]
        public FilterDataObject[] SystemTypeList{ get; set; }

        /// <summary>
        /// IP List
        /// </summary>
        [JsonProperty("IpTypeList")]
        public FilterDataObject[] IpTypeList{ get; set; }

        /// <summary>
        /// AppID List
        /// </summary>
        [JsonProperty("AppIdList")]
        public FilterDataObject[] AppIdList{ get; set; }

        /// <summary>
        /// Availability Zone List
        /// </summary>
        [JsonProperty("ZoneList")]
        public FilterDataObject[] ZoneList{ get; set; }

        /// <summary>
        /// OS List
        /// </summary>
        [JsonProperty("OsList")]
        public FilterDataObject[] OsList{ get; set; }

        /// <summary>
        /// Mapping of asset type and instance type.
        /// </summary>
        [JsonProperty("AssetMapInstanceTypeList")]
        public AssetInstanceTypeMap[] AssetMapInstanceTypeList{ get; set; }

        /// <summary>
        /// Public network private network enumeration.
        /// </summary>
        [JsonProperty("PublicPrivateAttr")]
        public FilterDataObject[] PublicPrivateAttr{ get; set; }

        /// <summary>
        /// Host protection status.
        /// </summary>
        [JsonProperty("ProtectStatusList")]
        public FilterDataObject[] ProtectStatusList{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "Total", this.Total);
            this.SetParamArrayObj(map, prefix + "Data.", this.Data);
            this.SetParamArrayObj(map, prefix + "RegionList.", this.RegionList);
            this.SetParamArrayObj(map, prefix + "DefenseStatusList.", this.DefenseStatusList);
            this.SetParamArrayObj(map, prefix + "VpcList.", this.VpcList);
            this.SetParamArrayObj(map, prefix + "AssetTypeList.", this.AssetTypeList);
            this.SetParamArrayObj(map, prefix + "SystemTypeList.", this.SystemTypeList);
            this.SetParamArrayObj(map, prefix + "IpTypeList.", this.IpTypeList);
            this.SetParamArrayObj(map, prefix + "AppIdList.", this.AppIdList);
            this.SetParamArrayObj(map, prefix + "ZoneList.", this.ZoneList);
            this.SetParamArrayObj(map, prefix + "OsList.", this.OsList);
            this.SetParamArrayObj(map, prefix + "AssetMapInstanceTypeList.", this.AssetMapInstanceTypeList);
            this.SetParamArrayObj(map, prefix + "PublicPrivateAttr.", this.PublicPrivateAttr);
            this.SetParamArrayObj(map, prefix + "ProtectStatusList.", this.ProtectStatusList);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

