/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Csip.V20221121.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeExposureTrendResponse : AbstractModel
    {
        
        /// <summary>
        /// Expose periodic trend count statistics.
        /// </summary>
        [JsonProperty("ExposeTrendList")]
        public ExposeTrendItem[] ExposeTrendList{ get; set; }

        /// <summary>
        /// Statistics of newly-added exposure cycles
        /// </summary>
        [JsonProperty("ExposeIncrement")]
        public ulong? ExposeIncrement{ get; set; }

        /// <summary>
        /// Number of fully open instances in the last 24 hours.
        /// </summary>
        [JsonProperty("OpenCount")]
        public ulong? OpenCount{ get; set; }

        /// <summary>
        /// Number of restricted accesses in the last 24 hours
        /// </summary>
        [JsonProperty("AclCount")]
        public ulong? AclCount{ get; set; }

        /// <summary>
        /// Number of failures to access in the last 1 day (24h)
        /// </summary>
        [JsonProperty("CloseCount")]
        public ulong? CloseCount{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamArrayObj(map, prefix + "ExposeTrendList.", this.ExposeTrendList);
            this.SetParamSimple(map, prefix + "ExposeIncrement", this.ExposeIncrement);
            this.SetParamSimple(map, prefix + "OpenCount", this.OpenCount);
            this.SetParamSimple(map, prefix + "AclCount", this.AclCount);
            this.SetParamSimple(map, prefix + "CloseCount", this.CloseCount);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

