/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Csip.V20221121.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeClusterDetailResponse : AbstractModel
    {
        
        /// <summary>
        /// <p>Cluster basic information</p>
        /// </summary>
        [JsonProperty("ClusterBaseInfo")]
        public ClusterListItem ClusterBaseInfo{ get; set; }

        /// <summary>
        /// <p>Runtime component.</p>
        /// </summary>
        [JsonProperty("RuntimeComponent")]
        public string RuntimeComponent{ get; set; }

        /// <summary>
        /// <p>master ip</p>
        /// </summary>
        [JsonProperty("MasterIP")]
        public string MasterIP{ get; set; }

        /// <summary>
        /// <p>Number of nodes</p>
        /// </summary>
        [JsonProperty("NodeCount")]
        public ulong? NodeCount{ get; set; }

        /// <summary>
        /// <p>Number of namespaces</p>
        /// </summary>
        [JsonProperty("NamespaceCount")]
        public ulong? NamespaceCount{ get; set; }

        /// <summary>
        /// <p>Number of pods</p>
        /// </summary>
        [JsonProperty("PodCount")]
        public ulong? PodCount{ get; set; }

        /// <summary>
        /// <p>Number of containers</p>
        /// </summary>
        [JsonProperty("ContainerCount")]
        public ulong? ContainerCount{ get; set; }

        /// <summary>
        /// <p>Number of services</p>
        /// </summary>
        [JsonProperty("ServiceCount")]
        public ulong? ServiceCount{ get; set; }

        /// <summary>
        /// <p>Number of ingresses</p>
        /// </summary>
        [JsonProperty("IngressCount")]
        public ulong? IngressCount{ get; set; }

        /// <summary>
        /// <p>Number of images.</p>
        /// </summary>
        [JsonProperty("ImageCount")]
        public ulong? ImageCount{ get; set; }

        /// <summary>
        /// <p>Number of system components</p>
        /// </summary>
        [JsonProperty("SystemComponentCount")]
        public ulong? SystemComponentCount{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamObj(map, prefix + "ClusterBaseInfo.", this.ClusterBaseInfo);
            this.SetParamSimple(map, prefix + "RuntimeComponent", this.RuntimeComponent);
            this.SetParamSimple(map, prefix + "MasterIP", this.MasterIP);
            this.SetParamSimple(map, prefix + "NodeCount", this.NodeCount);
            this.SetParamSimple(map, prefix + "NamespaceCount", this.NamespaceCount);
            this.SetParamSimple(map, prefix + "PodCount", this.PodCount);
            this.SetParamSimple(map, prefix + "ContainerCount", this.ContainerCount);
            this.SetParamSimple(map, prefix + "ServiceCount", this.ServiceCount);
            this.SetParamSimple(map, prefix + "IngressCount", this.IngressCount);
            this.SetParamSimple(map, prefix + "ImageCount", this.ImageCount);
            this.SetParamSimple(map, prefix + "SystemComponentCount", this.SystemComponentCount);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

