/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Csip.V20221121.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeNotifySettingAkResponse : AbstractModel
    {
        
        /// <summary>
        /// <p>Alarm type/severity (Type: AbnBehavior - abnormal behavior, LeakDetect - leakage detection; Severity: 1 - notification, 2 - low risk, 3 - medium risk, 4 - high risk, 5 - critical)</p>
        /// </summary>
        [JsonProperty("Alert")]
        public LevelOption[] Alert{ get; set; }

        /// <summary>
        /// <p>Alarm notification granularity</p><p>Enumeration values:</p><ul><li>0: Push by alert aggregation</li><li>1: Push by call record</li></ul>
        /// </summary>
        [JsonProperty("AlertGranularity")]
        public long? AlertGranularity{ get; set; }

        /// <summary>
        /// <p>Asset event</p><p>Enumeration value:</p><ul><li>NewAk: newly-added AK</li></ul>
        /// </summary>
        [JsonProperty("Asset")]
        public string[] Asset{ get; set; }

        /// <summary>
        /// <p>Notification start time</p><p>Parameter format: hh:mm:ss</p>
        /// </summary>
        [JsonProperty("BeginTime")]
        public string BeginTime{ get; set; }

        /// <summary>
        /// <p>Notification end time</p><p>Parameter format: hh:mm:ss</p>
        /// </summary>
        [JsonProperty("EndTime")]
        public string EndTime{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamArrayObj(map, prefix + "Alert.", this.Alert);
            this.SetParamSimple(map, prefix + "AlertGranularity", this.AlertGranularity);
            this.SetParamArraySimple(map, prefix + "Asset.", this.Asset);
            this.SetParamSimple(map, prefix + "BeginTime", this.BeginTime);
            this.SetParamSimple(map, prefix + "EndTime", this.EndTime);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

