/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Csip.V20221121.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeImageRegistryAssetOverviewResponse : AbstractModel
    {
        
        /// <summary>
        /// <p>Total number of images</p>
        /// </summary>
        [JsonProperty("ImageCnt")]
        public ulong? ImageCnt{ get; set; }

        /// <summary>
        /// <p>Scanned image count</p>
        /// </summary>
        [JsonProperty("ImageScannedCnt")]
        public ulong? ImageScannedCnt{ get; set; }

        /// <summary>
        /// <p>Number of components</p>
        /// </summary>
        [JsonProperty("ComponentCnt")]
        public ulong? ComponentCnt{ get; set; }

        /// <summary>
        /// <p>Number of vulnerabilities</p>
        /// </summary>
        [JsonProperty("VulCnt")]
        public ulong? VulCnt{ get; set; }

        /// <summary>
        /// <p>Number of trojans</p>
        /// </summary>
        [JsonProperty("VirusCnt")]
        public ulong? VirusCnt{ get; set; }

        /// <summary>
        /// <p>Number of sensitive information entries.</p>
        /// </summary>
        [JsonProperty("SensitiveCnt")]
        public ulong? SensitiveCnt{ get; set; }

        /// <summary>
        /// <p>Number of scheduled scan configurations</p>
        /// </summary>
        [JsonProperty("TimedScanTaskConfigCnt")]
        public ulong? TimedScanTaskConfigCnt{ get; set; }

        /// <summary>
        /// <p>Total quota</p>
        /// </summary>
        [JsonProperty("TotalQuota")]
        public ulong? TotalQuota{ get; set; }

        /// <summary>
        /// <p>Used quota</p>
        /// </summary>
        [JsonProperty("UsedQuota")]
        public ulong? UsedQuota{ get; set; }

        /// <summary>
        /// <p>Remaining quota</p>
        /// </summary>
        [JsonProperty("RemainingQuota")]
        public ulong? RemainingQuota{ get; set; }

        /// <summary>
        /// <p>Trial use quota</p>
        /// </summary>
        [JsonProperty("TrialQuota")]
        public ulong? TrialQuota{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "ImageCnt", this.ImageCnt);
            this.SetParamSimple(map, prefix + "ImageScannedCnt", this.ImageScannedCnt);
            this.SetParamSimple(map, prefix + "ComponentCnt", this.ComponentCnt);
            this.SetParamSimple(map, prefix + "VulCnt", this.VulCnt);
            this.SetParamSimple(map, prefix + "VirusCnt", this.VirusCnt);
            this.SetParamSimple(map, prefix + "SensitiveCnt", this.SensitiveCnt);
            this.SetParamSimple(map, prefix + "TimedScanTaskConfigCnt", this.TimedScanTaskConfigCnt);
            this.SetParamSimple(map, prefix + "TotalQuota", this.TotalQuota);
            this.SetParamSimple(map, prefix + "UsedQuota", this.UsedQuota);
            this.SetParamSimple(map, prefix + "RemainingQuota", this.RemainingQuota);
            this.SetParamSimple(map, prefix + "TrialQuota", this.TrialQuota);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

