/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Csip.V20221121.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeAssetTagAttributesResponse : AbstractModel
    {
        
        /// <summary>
        /// <p>Filter conditions.</p>
        /// </summary>
        [JsonProperty("FilterConditions")]
        public FilterDataObject[] FilterConditions{ get; set; }

        /// <summary>
        /// <p>Common properties of tagging policy</p>
        /// </summary>
        [JsonProperty("TaggingAttributes")]
        public FilterDataObject[] TaggingAttributes{ get; set; }

        /// <summary>
        /// <p>Existing tag key list</p>
        /// </summary>
        [JsonProperty("TagKeyList")]
        public FilterDataObject[] TagKeyList{ get; set; }

        /// <summary>
        /// <p>Selectable color list.</p>
        /// </summary>
        [JsonProperty("ColorOptions")]
        public FilterDataObject[] ColorOptions{ get; set; }

        /// <summary>
        /// <p>Asset type list</p>
        /// </summary>
        [JsonProperty("AssetTypeList")]
        public FilterDataObject[] AssetTypeList{ get; set; }

        /// <summary>
        /// <p>Tag tree</p>
        /// </summary>
        [JsonProperty("TagTree")]
        public AssetTagTreeNode[] TagTree{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamArrayObj(map, prefix + "FilterConditions.", this.FilterConditions);
            this.SetParamArrayObj(map, prefix + "TaggingAttributes.", this.TaggingAttributes);
            this.SetParamArrayObj(map, prefix + "TagKeyList.", this.TagKeyList);
            this.SetParamArrayObj(map, prefix + "ColorOptions.", this.ColorOptions);
            this.SetParamArrayObj(map, prefix + "AssetTypeList.", this.AssetTypeList);
            this.SetParamArrayObj(map, prefix + "TagTree.", this.TagTree);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

