/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Csip.V20221121.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeBaselineOverviewResponse : AbstractModel
    {
        
        /// <summary>
        /// <p>Baseline overview statistics (number of failed items for hosts/clusters and fixes in the past one year).</p>
        /// </summary>
        [JsonProperty("Statistics")]
        public BaselineOverviewStatistic Statistics{ get; set; }

        /// <summary>
        /// <p>Last baseline scan completion time.</p>
        /// </summary>
        [JsonProperty("LatestScanTime")]
        public string LatestScanTime{ get; set; }

        /// <summary>
        /// <p>Whether any periodic scanning is currently enabled. true: on, false: off.</p>
        /// </summary>
        [JsonProperty("EnableCycleScan")]
        public bool? EnableCycleScan{ get; set; }

        /// <summary>
        /// <p>Number of in-progress scan main tasks.</p>
        /// </summary>
        [JsonProperty("ScanningTaskCount")]
        public ulong? ScanningTaskCount{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamObj(map, prefix + "Statistics.", this.Statistics);
            this.SetParamSimple(map, prefix + "LatestScanTime", this.LatestScanTime);
            this.SetParamSimple(map, prefix + "EnableCycleScan", this.EnableCycleScan);
            this.SetParamSimple(map, prefix + "ScanningTaskCount", this.ScanningTaskCount);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

