/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Csip.V20221121.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeKBUpdatableMachineListResponse : AbstractModel
    {
        
        /// <summary>
        /// <p>Host list for patch updates</p>
        /// </summary>
        [JsonProperty("Data")]
        public KBUpdateMachineItem[] Data{ get; set; }

        /// <summary>
        /// <p>Total quantity.</p>
        /// </summary>
        [JsonProperty("TotalCount")]
        public long? TotalCount{ get; set; }

        /// <summary>
        /// <p>Number of hosts that can be repaired in one click</p>
        /// </summary>
        [JsonProperty("FixableCount")]
        public long? FixableCount{ get; set; }

        /// <summary>
        /// <p>Number of hosts that cannot be repaired with one click</p>
        /// </summary>
        [JsonProperty("NotFixableCount")]
        public long? NotFixableCount{ get; set; }

        /// <summary>
        /// <p>KB patch dimensional summary, showing an overview of the repaired patch list</p>
        /// </summary>
        [JsonProperty("KBSummary")]
        public KBFixSummaryItem[] KBSummary{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamArrayObj(map, prefix + "Data.", this.Data);
            this.SetParamSimple(map, prefix + "TotalCount", this.TotalCount);
            this.SetParamSimple(map, prefix + "FixableCount", this.FixableCount);
            this.SetParamSimple(map, prefix + "NotFixableCount", this.NotFixableCount);
            this.SetParamArrayObj(map, prefix + "KBSummary.", this.KBSummary);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

