/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Csip.V20221121.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeAccessKeyRiskDetailResponse : AbstractModel
    {
        
        /// <summary>
        /// Risk list.
        /// </summary>
        [JsonProperty("RiskInfo")]
        public AccessKeyRisk RiskInfo{ get; set; }

        /// <summary>
        /// Total number of CAM policies.
        /// </summary>
        [JsonProperty("CamCount")]
        public long? CamCount{ get; set; }

        /// <summary>
        /// Number of associated alarms for the account.
        /// </summary>
        [JsonProperty("AlarmCount")]
        public long? AlarmCount{ get; set; }

        /// <summary>
        /// Access method 0 API 1 console and API.
        /// </summary>
        [JsonProperty("AccessType")]
        public long? AccessType{ get; set; }

        /// <summary>
        /// Access key Alarm count list.
        /// </summary>
        [JsonProperty("AccessKeyAlarmCount")]
        public AccessKeyAlarmCount[] AccessKeyAlarmCount{ get; set; }

        /// <summary>
        /// Whether operation protection is enabled. valid values: 0 (not enabled), 1 (enabled).
        /// </summary>
        [JsonProperty("ActionFlag")]
        public long? ActionFlag{ get; set; }

        /// <summary>
        /// Whether login protection is enabled. valid values: 0 (not enabled), 1 (enabled).
        /// </summary>
        [JsonProperty("LoginFlag")]
        public long? LoginFlag{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamObj(map, prefix + "RiskInfo.", this.RiskInfo);
            this.SetParamSimple(map, prefix + "CamCount", this.CamCount);
            this.SetParamSimple(map, prefix + "AlarmCount", this.AlarmCount);
            this.SetParamSimple(map, prefix + "AccessType", this.AccessType);
            this.SetParamArrayObj(map, prefix + "AccessKeyAlarmCount.", this.AccessKeyAlarmCount);
            this.SetParamSimple(map, prefix + "ActionFlag", this.ActionFlag);
            this.SetParamSimple(map, prefix + "LoginFlag", this.LoginFlag);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

