/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Csip.V20221121.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class ModifyCspmShardConfigResponse : AbstractModel
    {
        
        /// <summary>
        /// <p>Shared AppID</p>
        /// </summary>
        [JsonProperty("ShardFromAppID")]
        public ulong? ShardFromAppID{ get; set; }

        /// <summary>
        /// <p>Shared switch: 1: On; 2: Off</p>
        /// </summary>
        [JsonProperty("AutoShardStatus")]
        public ulong? AutoShardStatus{ get; set; }

        /// <summary>
        /// <p>Shared AppID set</p>
        /// </summary>
        [JsonProperty("ShardAppIDs")]
        public ulong?[] ShardAppIDs{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "ShardFromAppID", this.ShardFromAppID);
            this.SetParamSimple(map, prefix + "AutoShardStatus", this.AutoShardStatus);
            this.SetParamArraySimple(map, prefix + "ShardAppIDs.", this.ShardAppIDs);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

