/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Csip.V20221121.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class SkillScanItem : AbstractModel
    {
        
        /// <summary>
        /// <p>Skill name</p>
        /// </summary>
        [JsonProperty("SkillName")]
        public string SkillName{ get; set; }

        /// <summary>
        /// <p>Skill description to help understand the primary purpose of the Skill</p>
        /// </summary>
        [JsonProperty("SkillDescription")]
        public string SkillDescription{ get; set; }

        /// <summary>
        /// <p>SHA256 Hash of the ZIP file<br>Parameter format: sha256:&lt;64-bit hex&gt;</p>
        /// </summary>
        [JsonProperty("ContentHash")]
        public string ContentHash{ get; set; }

        /// <summary>
        /// <p>Number of actual files after decompressing the original uploaded ZIP file, which is also the scope of billing. After a successful scan, 1 file is counted as 1 limit.</p>
        /// </summary>
        [JsonProperty("UploadFileCount")]
        public long? UploadFileCount{ get; set; }

        /// <summary>
        /// <p>Comprehensive risk level<br>Enumeration values:<br>malicious: Malicious<br>suspicious: Suspicious<br>benign: Trustworthy</p>
        /// </summary>
        [JsonProperty("RiskLevel")]
        public string RiskLevel{ get; set; }

        /// <summary>
        /// <p>Risk primary tag fusion rule ID (9xxxx), generated by the server from the hit fusion risk tags; empty when benign with no rule hits. The display name can be obtained through RuleCatalog</p>
        /// </summary>
        [JsonProperty("PrimaryRuleID")]
        public string PrimaryRuleID{ get; set; }

        /// <summary>
        /// <p>Comprehensive handling suggestions to guide the caller in prioritizing actions such as decommission, isolation, repair, and recheck. It may be empty in historical results. Return in English when Language=en-US is passed.</p>
        /// </summary>
        [JsonProperty("Mitigation")]
        public string Mitigation{ get; set; }

        /// <summary>
        /// <p>Comprehensive description of risks, summarizing the risks detected this time. Return in English when Language=en-US is passed</p>
        /// </summary>
        [JsonProperty("RiskDescription")]
        public string RiskDescription{ get; set; }

        /// <summary>
        /// <p>Security score value range: [0, 100]. Supplemental description: The higher the score, the more secure.</p>
        /// </summary>
        [JsonProperty("SecurityScore")]
        public long? SecurityScore{ get; set; }

        /// <summary>
        /// <p>Engine version number used for this scan</p>
        /// </summary>
        [JsonProperty("EngineVersion")]
        public long? EngineVersion{ get; set; }

        /// <summary>
        /// <p>Skill capability tag list, describing the capabilities, features, or application scenarios of a Skill. It is not equal to risk tags and does not participate in risk level judgment. When Language=en-US is passed, Name switches to English, and ID remains unchanged</p>
        /// </summary>
        [JsonProperty("CapabilityTags")]
        public SkillCapabilityTag[] CapabilityTags{ get; set; }

        /// <summary>
        /// <p>Complete set of fusion rule directories, including all fusion rule categories (9xxxx). Callers can show category tags based on this without the need to maintain a mapping table locally. Pass Language=en-US to return in English.</p>
        /// </summary>
        [JsonProperty("RuleCatalog")]
        public SkillRuleCatalogItem[] RuleCatalog{ get; set; }

        /// <summary>
        /// <p>Scan result details, grouped by sub-engine. Each element contains ScanType (engine type) and RuleList (hit rule list). The RuleID within the rules uses fusion coding (9xxxx) and can be cross-referenced with RuleCatalog. When Language=en-US is passed, Description returns English text.</p>
        /// </summary>
        [JsonProperty("ScanItems")]
        public SkillScanEngineResult[] ScanItems{ get; set; }

        /// <summary>
        /// <p>Comprehensive security audit report address (pre-signed URL). The valid period is controlled by the request parameter ReportURLExpireHours.</p>
        /// </summary>
        [JsonProperty("ReportURL")]
        public string ReportURL{ get; set; }

        /// <summary>
        /// <p>Scan completion time. It has a value only when Status=SUCCESS.<br>Parameter format: YYYY-MM-DDTHH:mm:ssZ (ISO8601 format)</p>
        /// </summary>
        [JsonProperty("ScannedAt")]
        public string ScannedAt{ get; set; }

        /// <summary>
        /// <p>Task creation time. It has a value only when Status=SCANNING<br>Parameter format: YYYY-MM-DDTHH:mm:ssZ (ISO8601 format)</p>
        /// </summary>
        [JsonProperty("CreatedAt")]
        public string CreatedAt{ get; set; }

        /// <summary>
        /// <p>Failure time. It has a value only when Status=FAILED<br>Parameter format: YYYY-MM-DDTHH:mm:ssZ (ISO8601 format)</p>
        /// </summary>
        [JsonProperty("FailedAt")]
        public string FailedAt{ get; set; }

        /// <summary>
        /// <p>Failure reason description. It only has a value when Status=FAILED.</p>
        /// </summary>
        [JsonProperty("Message")]
        public string Message{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "SkillName", this.SkillName);
            this.SetParamSimple(map, prefix + "SkillDescription", this.SkillDescription);
            this.SetParamSimple(map, prefix + "ContentHash", this.ContentHash);
            this.SetParamSimple(map, prefix + "UploadFileCount", this.UploadFileCount);
            this.SetParamSimple(map, prefix + "RiskLevel", this.RiskLevel);
            this.SetParamSimple(map, prefix + "PrimaryRuleID", this.PrimaryRuleID);
            this.SetParamSimple(map, prefix + "Mitigation", this.Mitigation);
            this.SetParamSimple(map, prefix + "RiskDescription", this.RiskDescription);
            this.SetParamSimple(map, prefix + "SecurityScore", this.SecurityScore);
            this.SetParamSimple(map, prefix + "EngineVersion", this.EngineVersion);
            this.SetParamArrayObj(map, prefix + "CapabilityTags.", this.CapabilityTags);
            this.SetParamArrayObj(map, prefix + "RuleCatalog.", this.RuleCatalog);
            this.SetParamArrayObj(map, prefix + "ScanItems.", this.ScanItems);
            this.SetParamSimple(map, prefix + "ReportURL", this.ReportURL);
            this.SetParamSimple(map, prefix + "ScannedAt", this.ScannedAt);
            this.SetParamSimple(map, prefix + "CreatedAt", this.CreatedAt);
            this.SetParamSimple(map, prefix + "FailedAt", this.FailedAt);
            this.SetParamSimple(map, prefix + "Message", this.Message);
        }
    }
}

