/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Antiddos.V20250903.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeDDoSBlockRecordsResponse : AbstractModel
    {
        
        /// <summary>
        /// <p>Total number of block and unblock records.</p>
        /// </summary>
        [JsonProperty("TotalCount")]
        public ulong? TotalCount{ get; set; }

        /// <summary>
        /// <p>Unblock record.</p>
        /// </summary>
        [JsonProperty("BlockRecords")]
        public DDoSBlockRecord[] BlockRecords{ get; set; }

        /// <summary>
        /// <p>Quota information of the number of unblocking times.</p>
        /// </summary>
        [JsonProperty("UnblockQuotaInfo")]
        public DDoSUnblockQuota UnblockQuotaInfo{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "TotalCount", this.TotalCount);
            this.SetParamArrayObj(map, prefix + "BlockRecords.", this.BlockRecords);
            this.SetParamObj(map, prefix + "UnblockQuotaInfo.", this.UnblockQuotaInfo);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

