/*
 * Copyright (c) 2018 THL A29 Limited, a Tencent company. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Waf.V20180125.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeAttackOverviewResponse : AbstractModel
    {
        
        /// <summary>
        /// Total number of access requests
        /// </summary>
        [JsonProperty("AccessCount")]
        public ulong? AccessCount{ get; set; }

        /// <summary>
        /// Total web attacks
        /// </summary>
        [JsonProperty("AttackCount")]
        public ulong? AttackCount{ get; set; }

        /// <summary>
        /// Total number of access controls
        /// </summary>
        [JsonProperty("ACLCount")]
        public ulong? ACLCount{ get; set; }

        /// <summary>
        /// Total CC attacks
        /// </summary>
        [JsonProperty("CCCount")]
        public ulong? CCCount{ get; set; }

        /// <summary>
        /// Total bot attack count
        /// </summary>
        [JsonProperty("BotCount")]
        public ulong? BotCount{ get; set; }

        /// <summary>
        /// Total API assets
        /// </summary>
        [JsonProperty("ApiAssetsCount")]
        public ulong? ApiAssetsCount{ get; set; }

        /// <summary>
        /// Number of API risk events
        /// 
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("ApiRiskEventCount")]
        public ulong? ApiRiskEventCount{ get; set; }

        /// <summary>
        /// Total number of blocklisted IP addresses.
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("IPBlackCount")]
        public ulong? IPBlackCount{ get; set; }

        /// <summary>
        /// Total number of tamper-proof items
        /// 
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("TamperCount")]
        public ulong? TamperCount{ get; set; }

        /// <summary>
        /// Total number of information leaks
        /// 
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("LeakCount")]
        public ulong? LeakCount{ get; set; }

        /// <summary>
        /// Weekly proportion of API risk events.
        /// 
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("ApiRiskEventCircleCount")]
        public long? ApiRiskEventCircleCount{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "AccessCount", this.AccessCount);
            this.SetParamSimple(map, prefix + "AttackCount", this.AttackCount);
            this.SetParamSimple(map, prefix + "ACLCount", this.ACLCount);
            this.SetParamSimple(map, prefix + "CCCount", this.CCCount);
            this.SetParamSimple(map, prefix + "BotCount", this.BotCount);
            this.SetParamSimple(map, prefix + "ApiAssetsCount", this.ApiAssetsCount);
            this.SetParamSimple(map, prefix + "ApiRiskEventCount", this.ApiRiskEventCount);
            this.SetParamSimple(map, prefix + "IPBlackCount", this.IPBlackCount);
            this.SetParamSimple(map, prefix + "TamperCount", this.TamperCount);
            this.SetParamSimple(map, prefix + "LeakCount", this.LeakCount);
            this.SetParamSimple(map, prefix + "ApiRiskEventCircleCount", this.ApiRiskEventCircleCount);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

