/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Wedata.V20210820.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DeleteIntegrationTaskResponse : AbstractModel
    {
        
        /// <summary>
        /// Task Deletion Success or Failure Indicator
        /// </summary>
        [JsonProperty("Data")]
        public bool? Data{ get; set; }

        /// <summary>
        /// Task Deletion Success or Failure Indicator
        /// 0 indicates deletion was successful
        /// 1 indicates failure, see DeleteErrInfo for the reason
        /// 100 indicates running or suspend task can't be deleted, the reason will also be written in DeleteErrInfo
        /// Note: This field may return null, indicating that no valid value can be obtained.
        /// </summary>
        [JsonProperty("DeleteFlag")]
        public long? DeleteFlag{ get; set; }

        /// <summary>
        /// Reason for Deletion Failure
        /// Note: This field may return null, indicating that no valid value can be obtained.
        /// </summary>
        [JsonProperty("DeleteErrInfo")]
        public string DeleteErrInfo{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "Data", this.Data);
            this.SetParamSimple(map, prefix + "DeleteFlag", this.DeleteFlag);
            this.SetParamSimple(map, prefix + "DeleteErrInfo", this.DeleteErrInfo);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

