/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Wedata.V20210820.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeIntegrationStatisticsResponse : AbstractModel
    {
        
        /// <summary>
        /// Total Tasks
        /// Note: This field may return null, indicating that no valid value can be obtained.
        /// </summary>
        [JsonProperty("TotalTask")]
        public long? TotalTask{ get; set; }

        /// <summary>
        /// Number of Production Tasks
        /// Note: This field may return null, indicating that no valid value can be obtained.
        /// </summary>
        [JsonProperty("ProdTask")]
        public long? ProdTask{ get; set; }

        /// <summary>
        /// Number of Development Tasks
        /// Note: This field may return null, indicating that no valid value can be obtained.
        /// </summary>
        [JsonProperty("DevTask")]
        public long? DevTask{ get; set; }

        /// <summary>
        /// Total Number of Reads
        /// Note: This field may return null, indicating that no valid value can be obtained.
        /// </summary>
        [JsonProperty("TotalReadRecords")]
        public long? TotalReadRecords{ get; set; }

        /// <summary>
        /// Total Number of Writes
        /// Note: This field may return null, indicating that no valid value can be obtained.
        /// </summary>
        [JsonProperty("TotalWriteRecords")]
        public long? TotalWriteRecords{ get; set; }

        /// <summary>
        /// Total Number of Dirty Data Entries
        /// Note: This field may return null, indicating that no valid value can be obtained.
        /// </summary>
        [JsonProperty("TotalErrorRecords")]
        public long? TotalErrorRecords{ get; set; }

        /// <summary>
        /// Total Number of Alarm Events
        /// Note: This field may return null, indicating that no valid value can be obtained.
        /// </summary>
        [JsonProperty("TotalAlarmEvent")]
        public long? TotalAlarmEvent{ get; set; }

        /// <summary>
        /// Daily Increase in Reads
        /// Note: This field may return null, indicating that no valid value can be obtained.
        /// </summary>
        [JsonProperty("IncreaseReadRecords")]
        public long? IncreaseReadRecords{ get; set; }

        /// <summary>
        /// Daily Increase in Writes
        /// Note: This field may return null, indicating that no valid value can be obtained.
        /// </summary>
        [JsonProperty("IncreaseWriteRecords")]
        public long? IncreaseWriteRecords{ get; set; }

        /// <summary>
        /// Daily Increase in Dirty Data Entries
        /// Note: This field may return null, indicating that no valid value can be obtained.
        /// </summary>
        [JsonProperty("IncreaseErrorRecords")]
        public long? IncreaseErrorRecords{ get; set; }

        /// <summary>
        /// Daily Increase in Alarm Events
        /// Note: This field may return null, indicating that no valid value can be obtained.
        /// </summary>
        [JsonProperty("IncreaseAlarmEvent")]
        public long? IncreaseAlarmEvent{ get; set; }

        /// <summary>
        /// Alarm Event Statistics
        /// Note: This field may return null, indicating that no valid value can be obtained.
        /// </summary>
        [JsonProperty("AlarmEvent")]
        public string AlarmEvent{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "TotalTask", this.TotalTask);
            this.SetParamSimple(map, prefix + "ProdTask", this.ProdTask);
            this.SetParamSimple(map, prefix + "DevTask", this.DevTask);
            this.SetParamSimple(map, prefix + "TotalReadRecords", this.TotalReadRecords);
            this.SetParamSimple(map, prefix + "TotalWriteRecords", this.TotalWriteRecords);
            this.SetParamSimple(map, prefix + "TotalErrorRecords", this.TotalErrorRecords);
            this.SetParamSimple(map, prefix + "TotalAlarmEvent", this.TotalAlarmEvent);
            this.SetParamSimple(map, prefix + "IncreaseReadRecords", this.IncreaseReadRecords);
            this.SetParamSimple(map, prefix + "IncreaseWriteRecords", this.IncreaseWriteRecords);
            this.SetParamSimple(map, prefix + "IncreaseErrorRecords", this.IncreaseErrorRecords);
            this.SetParamSimple(map, prefix + "IncreaseAlarmEvent", this.IncreaseAlarmEvent);
            this.SetParamSimple(map, prefix + "AlarmEvent", this.AlarmEvent);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

