/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Wedata.V20210820.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeRealTimeTaskMetricOverviewResponse : AbstractModel
    {
        
        /// <summary>
        /// Total Read Records
        /// </summary>
        [JsonProperty("TotalRecordNumOfRead")]
        public ulong? TotalRecordNumOfRead{ get; set; }

        /// <summary>
        /// Total Read Bytes
        /// </summary>
        [JsonProperty("TotalRecordByteNumOfRead")]
        public ulong? TotalRecordByteNumOfRead{ get; set; }

        /// <summary>
        /// Total Write Records
        /// </summary>
        [JsonProperty("TotalRecordNumOfWrite")]
        public ulong? TotalRecordNumOfWrite{ get; set; }

        /// <summary>
        /// Total Write Bytes Unit: bytes
        /// </summary>
        [JsonProperty("TotalRecordByteNumOfWrite")]
        public ulong? TotalRecordByteNumOfWrite{ get; set; }

        /// <summary>
        /// Total Dirty Record Data
        /// </summary>
        [JsonProperty("TotalDirtyRecordNum")]
        public ulong? TotalDirtyRecordNum{ get; set; }

        /// <summary>
        /// Total Dirty Bytes Unit: bytes
        /// </summary>
        [JsonProperty("TotalDirtyRecordByte")]
        public ulong? TotalDirtyRecordByte{ get; set; }

        /// <summary>
        /// Execution Duration Unit: s
        /// </summary>
        [JsonProperty("TotalDuration")]
        public ulong? TotalDuration{ get; set; }

        /// <summary>
        /// Start Running Time
        /// </summary>
        [JsonProperty("BeginRunTime")]
        public string BeginRunTime{ get; set; }

        /// <summary>
        /// Current Running Time
        /// </summary>
        [JsonProperty("EndRunTime")]
        public string EndRunTime{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "TotalRecordNumOfRead", this.TotalRecordNumOfRead);
            this.SetParamSimple(map, prefix + "TotalRecordByteNumOfRead", this.TotalRecordByteNumOfRead);
            this.SetParamSimple(map, prefix + "TotalRecordNumOfWrite", this.TotalRecordNumOfWrite);
            this.SetParamSimple(map, prefix + "TotalRecordByteNumOfWrite", this.TotalRecordByteNumOfWrite);
            this.SetParamSimple(map, prefix + "TotalDirtyRecordNum", this.TotalDirtyRecordNum);
            this.SetParamSimple(map, prefix + "TotalDirtyRecordByte", this.TotalDirtyRecordByte);
            this.SetParamSimple(map, prefix + "TotalDuration", this.TotalDuration);
            this.SetParamSimple(map, prefix + "BeginRunTime", this.BeginRunTime);
            this.SetParamSimple(map, prefix + "EndRunTime", this.EndRunTime);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

