/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Cfg.V20210820.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeActionFieldConfigListResponse : AbstractModel
    {
        
        /// <summary>
        /// List of general filed configuration parameters
        /// </summary>
        [JsonProperty("Common")]
        public ActionFieldConfigResult[] Common{ get; set; }

        /// <summary>
        /// List of action filed configuration parameters
        /// </summary>
        [JsonProperty("Results")]
        public ActionFieldConfigResult[] Results{ get; set; }

        /// <summary>
        /// Information on the decommissioned resource
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("ResourceOffline")]
        public ResourceOffline[] ResourceOffline{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamArrayObj(map, prefix + "Common.", this.Common);
            this.SetParamArrayObj(map, prefix + "Results.", this.Results);
            this.SetParamArrayObj(map, prefix + "ResourceOffline.", this.ResourceOffline);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

