/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Vod.V20180717.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class ApplyUploadResponse : AbstractModel
    {
        
        /// <summary>
        /// Bucket for uploading the API URL bucket_name.
        /// </summary>
        [JsonProperty("StorageBucket")]
        public string StorageBucket{ get; set; }

        /// <summary>
        /// Storage campus for uploading the Host Region of the port.
        /// </summary>
        [JsonProperty("StorageRegion")]
        public string StorageRegion{ get; set; }

        /// <summary>
        /// VOD session for confirmation of API parameters VodSessionKey.
        /// </summary>
        [JsonProperty("VodSessionKey")]
        public string VodSessionKey{ get; set; }

        /// <summary>
        /// Media storage path for the object key (Key) used by the upload API to store media.
        /// </summary>
        [JsonProperty("MediaStoragePath")]
        public string MediaStoragePath{ get; set; }

        /// <summary>
        /// Cover storage path for uploading the object Key of the cover via API.
        /// </summary>
        [JsonProperty("CoverStoragePath")]
        public string CoverStoragePath{ get; set; }

        /// <summary>
        /// Temporary credentials for uploading API permission verification.
        /// </summary>
        [JsonProperty("TempCertificate")]
        public TempCertificate TempCertificate{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "StorageBucket", this.StorageBucket);
            this.SetParamSimple(map, prefix + "StorageRegion", this.StorageRegion);
            this.SetParamSimple(map, prefix + "VodSessionKey", this.VodSessionKey);
            this.SetParamSimple(map, prefix + "MediaStoragePath", this.MediaStoragePath);
            this.SetParamSimple(map, prefix + "CoverStoragePath", this.CoverStoragePath);
            this.SetParamObj(map, prefix + "TempCertificate.", this.TempCertificate);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

