/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Vod.V20180717.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class MediaDeleteItem : AbstractModel
    {
        
        /// <summary>
        /// <p>The specified deletion part. If this field is not filled in, the parameter is invalid. Optional values:</p><li>OriginalFiles (delete the original file. Once deleted, you cannot initiate any video processing operations such as transcoding or publishing on WeChat);</li><li>TranscodeFiles (delete transcoded files);</li><li>AdaptiveDynamicStreamingFiles (delete adaptive bitrate stream files);</li><li>WechatPublishFiles (delete files published on WeChat);</li><li>WechatMiniProgramPublishFiles (delete WeChat Mini Program publishing files).</li><li>MpsAiMediaAiAnalysisFiles (delete AI analysis products generated by ProcessMediaByMPS).</li><li>MpsAiMediaSmartEraseFiles (delete intelligent erasure products generated by ProcessMediaByMPS).</li><li>MpsAiMediaSmartSubtitleFiles (delete smart subtitling products generated by ProcessMediaByMPS).</li><font color="red">Note:</font> <li>When the value is OriginalFiles, the cover file carried during file upload will be deleted;</li><li>When the value is TranscodeFiles, the cover file generated by media processing will be deleted.</li>
        /// </summary>
        [JsonProperty("Type")]
        public string Type{ get; set; }

        /// <summary>
        /// <p>Delete the video template ID of the type specified by the Type parameter. For template definition, see <a href="https://www.tencentcloud.com/document/product/266/33478?from_cn_redirect=1#.3Cspan-id-.3D-.22zm.22-.3E.3C.2Fspan.3E.E8.BD.AC.E7.A0.81.E6.A8.A1.E6.9D.BF">Transcoding Template</a>.<br>Default value: 0, which means to delete all videos of the type specified by the Type parameter.</p>
        /// </summary>
        [JsonProperty("Definition")]
        public long? Definition{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "Type", this.Type);
            this.SetParamSimple(map, prefix + "Definition", this.Definition);
        }
    }
}

