/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Ssl.V20191205.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeCertificateBindResourceTaskDetailResponse : AbstractModel
    {
        
        /// <summary>
        /// <p>clb resource detail</p>
        /// </summary>
        [JsonProperty("CLB")]
        public ClbInstanceList[] CLB{ get; set; }

        /// <summary>
        /// <p>cdn resource detail</p>
        /// </summary>
        [JsonProperty("CDN")]
        public CdnInstanceList[] CDN{ get; set; }

        /// <summary>
        /// <p>waf resource detail</p>
        /// </summary>
        [JsonProperty("WAF")]
        public WafInstanceList[] WAF{ get; set; }

        /// <summary>
        /// <p>Associate ddos resource detail</p>
        /// </summary>
        [JsonProperty("DDOS")]
        public DdosInstanceList[] DDOS{ get; set; }

        /// <summary>
        /// <p>Associate live resource detail</p>
        /// </summary>
        [JsonProperty("LIVE")]
        public LiveInstanceList[] LIVE{ get; set; }

        /// <summary>
        /// <p>vod resource detail</p>
        /// </summary>
        [JsonProperty("VOD")]
        public VODInstanceList[] VOD{ get; set; }

        /// <summary>
        /// <p>tke resource detail</p>
        /// </summary>
        [JsonProperty("TKE")]
        public TkeInstanceList[] TKE{ get; set; }

        /// <summary>
        /// <p>apigateway resource detail</p>
        /// </summary>
        [JsonProperty("APIGATEWAY")]
        public ApiGatewayInstanceList[] APIGATEWAY{ get; set; }

        /// <summary>
        /// <p>tcb resource detail</p>
        /// </summary>
        [JsonProperty("TCB")]
        public TCBInstanceList[] TCB{ get; set; }

        /// <summary>
        /// <p>Associate teo resource detail</p>
        /// </summary>
        [JsonProperty("TEO")]
        public TeoInstanceList[] TEO{ get; set; }

        /// <summary>
        /// <p>Associate cloud resources async query result: 0 indicates querying, 1 indicates success. 2 indicates an exception. If the status is 1, view the BindResourceResult. If the status is 2, view the Error reason.</p>
        /// </summary>
        [JsonProperty("Status")]
        public ulong? Status{ get; set; }

        /// <summary>
        /// <p>Current result cache time</p>
        /// </summary>
        [JsonProperty("CacheTime")]
        public string CacheTime{ get; set; }

        /// <summary>
        /// <p>Associate tse resource detail</p>
        /// </summary>
        [JsonProperty("TSE")]
        public TSEInstanceList[] TSE{ get; set; }

        /// <summary>
        /// <p>Associated COS resource detail</p>
        /// </summary>
        [JsonProperty("COS")]
        public COSInstanceList[] COS{ get; set; }

        /// <summary>
        /// <p>Associated TDMQ - Rabbit resource detail</p>
        /// </summary>
        [JsonProperty("TDMQ")]
        public TDMQInstanceList[] TDMQ{ get; set; }

        /// <summary>
        /// <p>Associated MQTT resource detail</p>
        /// </summary>
        [JsonProperty("MQTT")]
        public MQTTInstanceList[] MQTT{ get; set; }

        /// <summary>
        /// <p>Associated GAAP resource detail</p>
        /// </summary>
        [JsonProperty("GAAP")]
        public GAAPInstanceList[] GAAP{ get; set; }

        /// <summary>
        /// <p>Associated SCF resource detail</p>
        /// </summary>
        [JsonProperty("SCF")]
        public SCFInstanceList[] SCF{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamArrayObj(map, prefix + "CLB.", this.CLB);
            this.SetParamArrayObj(map, prefix + "CDN.", this.CDN);
            this.SetParamArrayObj(map, prefix + "WAF.", this.WAF);
            this.SetParamArrayObj(map, prefix + "DDOS.", this.DDOS);
            this.SetParamArrayObj(map, prefix + "LIVE.", this.LIVE);
            this.SetParamArrayObj(map, prefix + "VOD.", this.VOD);
            this.SetParamArrayObj(map, prefix + "TKE.", this.TKE);
            this.SetParamArrayObj(map, prefix + "APIGATEWAY.", this.APIGATEWAY);
            this.SetParamArrayObj(map, prefix + "TCB.", this.TCB);
            this.SetParamArrayObj(map, prefix + "TEO.", this.TEO);
            this.SetParamSimple(map, prefix + "Status", this.Status);
            this.SetParamSimple(map, prefix + "CacheTime", this.CacheTime);
            this.SetParamArrayObj(map, prefix + "TSE.", this.TSE);
            this.SetParamArrayObj(map, prefix + "COS.", this.COS);
            this.SetParamArrayObj(map, prefix + "TDMQ.", this.TDMQ);
            this.SetParamArrayObj(map, prefix + "MQTT.", this.MQTT);
            this.SetParamArrayObj(map, prefix + "GAAP.", this.GAAP);
            this.SetParamArrayObj(map, prefix + "SCF.", this.SCF);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

