/*
 * Copyright (c) 2018 THL A29 Limited, a Tencent company. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Ssl.V20191205.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeHostUpdateRecordDetailResponse : AbstractModel
    {
        
        /// <summary>
        /// If the total number cannot be obtained, return 0.
        /// Note: this field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("TotalCount")]
        public long? TotalCount{ get; set; }

        /// <summary>
        /// Certificate deployment record list; returns an empty array if no value is obtained.
        /// Note: this field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("RecordDetailList")]
        public UpdateRecordDetails[] RecordDetailList{ get; set; }

        /// <summary>
        /// Total number of successes; returns 0 if unavailable.
        /// Note: this field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("SuccessTotalCount")]
        public long? SuccessTotalCount{ get; set; }

        /// <summary>
        /// Total number of failures. if it cannot be obtained, return 0.
        /// Note: this field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("FailedTotalCount")]
        public long? FailedTotalCount{ get; set; }

        /// <summary>
        /// Total number of deployments in progress; returns 0 if unavailable.
        /// Note: this field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("RunningTotalCount")]
        public long? RunningTotalCount{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "TotalCount", this.TotalCount);
            this.SetParamArrayObj(map, prefix + "RecordDetailList.", this.RecordDetailList);
            this.SetParamSimple(map, prefix + "SuccessTotalCount", this.SuccessTotalCount);
            this.SetParamSimple(map, prefix + "FailedTotalCount", this.FailedTotalCount);
            this.SetParamSimple(map, prefix + "RunningTotalCount", this.RunningTotalCount);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

