/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Emr.V20190103.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeClusterFlowStatusDetailResponse : AbstractModel
    {
        
        /// <summary>
        /// Task step details
        /// 
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("StageDetails")]
        public StageInfoDetail[] StageDetails{ get; set; }

        /// <summary>
        /// Task parameters.
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("FlowDesc")]
        public FlowParamsDesc[] FlowDesc{ get; set; }

        /// <summary>
        /// Task name.
        /// </summary>
        [JsonProperty("FlowName")]
        public string FlowName{ get; set; }

        /// <summary>
        /// Overall task flow progress.
        /// Example: 0.8.
        /// </summary>
        [JsonProperty("FlowTotalProgress")]
        public float? FlowTotalProgress{ get; set; }

        /// <summary>
        /// Overall process status definition.
        /// 0: initializing.
        /// 1: running.
        /// 2: completed.
        /// 3: completed (with skipped steps).
        /// -1: failed.
        /// -3: blocked.
        /// </summary>
        [JsonProperty("FlowTotalStatus")]
        public long? FlowTotalStatus{ get; set; }

        /// <summary>
        /// Additional process information.
        /// This parameter is returned when NeedExtraDetail is true.
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("FlowExtraDetail")]
        public FlowExtraDetail[] FlowExtraDetail{ get; set; }

        /// <summary>
        /// Flow description.
        /// </summary>
        [JsonProperty("FlowInfo")]
        public string FlowInfo{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamArrayObj(map, prefix + "StageDetails.", this.StageDetails);
            this.SetParamArrayObj(map, prefix + "FlowDesc.", this.FlowDesc);
            this.SetParamSimple(map, prefix + "FlowName", this.FlowName);
            this.SetParamSimple(map, prefix + "FlowTotalProgress", this.FlowTotalProgress);
            this.SetParamSimple(map, prefix + "FlowTotalStatus", this.FlowTotalStatus);
            this.SetParamArrayObj(map, prefix + "FlowExtraDetail.", this.FlowExtraDetail);
            this.SetParamSimple(map, prefix + "FlowInfo", this.FlowInfo);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

