/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Emr.V20190103.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeGlobalConfigResponse : AbstractModel
    {
        
        /// <summary>
        /// Whether the resource scheduling feature is enabled.
        /// </summary>
        [JsonProperty("EnableResourceSchedule")]
        public bool? EnableResourceSchedule{ get; set; }

        /// <summary>
        /// Currently effective resource scheduler.
        /// </summary>
        [JsonProperty("ActiveScheduler")]
        public string ActiveScheduler{ get; set; }

        /// <summary>
        /// Information of the fair scheduler.
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("CapacityGlobalConfig")]
        public CapacityGlobalConfig CapacityGlobalConfig{ get; set; }

        /// <summary>
        /// Information of the capacity scheduler.
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("FairGlobalConfig")]
        public FairGlobalConfig FairGlobalConfig{ get; set; }

        /// <summary>
        /// Latest resource scheduler.
        /// </summary>
        [JsonProperty("Scheduler")]
        public string Scheduler{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "EnableResourceSchedule", this.EnableResourceSchedule);
            this.SetParamSimple(map, prefix + "ActiveScheduler", this.ActiveScheduler);
            this.SetParamObj(map, prefix + "CapacityGlobalConfig.", this.CapacityGlobalConfig);
            this.SetParamObj(map, prefix + "FairGlobalConfig.", this.FairGlobalConfig);
            this.SetParamSimple(map, prefix + "Scheduler", this.Scheduler);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

