/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Redis.V20180412.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeSSLStatusResponse : AbstractModel
    {
        
        /// <summary>
        /// <p>SSL certificate download address.</p>
        /// </summary>
        [JsonProperty("CertDownloadUrl")]
        public string CertDownloadUrl{ get; set; }

        /// <summary>
        /// <p>Certificate download link expiration time.</p>
        /// </summary>
        [JsonProperty("UrlExpiredTime")]
        public string UrlExpiredTime{ get; set; }

        /// <summary>
        /// <p>Flag whether the instance enables SSL feature.</p><ul><li>true: enable.</li><li>false: disable.</li></ul>
        /// </summary>
        [JsonProperty("SSLConfig")]
        public bool? SSLConfig{ get; set; }

        /// <summary>
        /// <p>Flag whether the instance supports SSL feature.</p><ul><li>true: support.</li><li>false: unsupported.</li></ul>
        /// </summary>
        [JsonProperty("FeatureSupport")]
        public bool? FeatureSupport{ get; set; }

        /// <summary>
        /// <p>Describes the SSL configuration status.</p><ul><li>1: Configuration in progress.</li><li>2: Configured successfully.</li></ul>
        /// </summary>
        [JsonProperty("Status")]
        public long? Status{ get; set; }

        /// <summary>
        /// <p>Address type.</p><p>Enumeration value:</p><ul><li>0: Unlimited.</li><li>1: Private IPv4 address.</li><li>2: Private IPv6 address.</li><li>3: Public network.</li><li>-1: Unspecified.</li></ul>
        /// </summary>
        [JsonProperty("AddressType")]
        public long? AddressType{ get; set; }

        /// <summary>
        /// <p>Current encrypted connection address</p>
        /// </summary>
        [JsonProperty("EncryptAddress")]
        public string EncryptAddress{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "CertDownloadUrl", this.CertDownloadUrl);
            this.SetParamSimple(map, prefix + "UrlExpiredTime", this.UrlExpiredTime);
            this.SetParamSimple(map, prefix + "SSLConfig", this.SSLConfig);
            this.SetParamSimple(map, prefix + "FeatureSupport", this.FeatureSupport);
            this.SetParamSimple(map, prefix + "Status", this.Status);
            this.SetParamSimple(map, prefix + "AddressType", this.AddressType);
            this.SetParamSimple(map, prefix + "EncryptAddress", this.EncryptAddress);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

