/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Redis.V20180412.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeBandwidthRangeResponse : AbstractModel
    {
        
        /// <summary>
        /// <p>Standard bandwidth. The bandwidth allocated by the system to each node when purchasing instances.</p>Measurement unit: MB/s.
        /// </summary>
        [JsonProperty("BaseBandwidth")]
        public long? BaseBandwidth{ get; set; }

        /// <summary>
        /// <p>Refers to the additional bandwidth of the instance. When the standard bandwidth cannot meet needs, users can manually add bandwidth.</p><ul><li>When read-only replicas are enabled, total instance bandwidth = additional bandwidth * shard quantity + standard bandwidth * shard quantity * Max ([number of read-only replicas, 1]). Shard quantity in standard architecture = 1.</li><li>When read-only replicas are not enabled, total instance bandwidth = additional bandwidth * shard quantity + standard bandwidth * shard quantity. Shard quantity in standard architecture = 1.</li></ul>Unit: MB/s.
        /// </summary>
        [JsonProperty("AddBandwidth")]
        public long? AddBandwidth{ get; set; }

        /// <summary>
        /// <p>Minimum set for additional bandwidth.</p> Unit: MB/s.
        /// </summary>
        [JsonProperty("MinAddBandwidth")]
        public long? MinAddBandwidth{ get; set; }

        /// <summary>
        /// <p>Set upper limit for additional bandwidth.</p> Measurement unit: MB/s.
        /// </summary>
        [JsonProperty("MaxAddBandwidth")]
        public long? MaxAddBandwidth{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "BaseBandwidth", this.BaseBandwidth);
            this.SetParamSimple(map, prefix + "AddBandwidth", this.AddBandwidth);
            this.SetParamSimple(map, prefix + "MinAddBandwidth", this.MinAddBandwidth);
            this.SetParamSimple(map, prefix + "MaxAddBandwidth", this.MaxAddBandwidth);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

