/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Facefusion.V20220927.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class SubmitVideoFaceFusionJobResponse : AbstractModel
    {
        
        /// <summary>
        /// Job ID of the video face fusion task
        /// </summary>
        [JsonProperty("JobId")]
        public string JobId{ get; set; }

        /// <summary>
        /// Estimated processing time of the video face fusion task, in seconds
        /// </summary>
        [JsonProperty("EstimatedProcessTime")]
        public float? EstimatedProcessTime{ get; set; }

        /// <summary>
        /// Estimated processing time of the video face fusion task, in seconds
        /// </summary>
        [JsonProperty("JobQueueLength")]
        public long? JobQueueLength{ get; set; }

        /// <summary>
        /// Inappropriate content recognition result. The element order of this array is the same as that of mergeinfo in the request, with a one-to-one relationship.
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("ReviewResultSet")]
        public FuseFaceReviewResult[] ReviewResultSet{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "JobId", this.JobId);
            this.SetParamSimple(map, prefix + "EstimatedProcessTime", this.EstimatedProcessTime);
            this.SetParamSimple(map, prefix + "JobQueueLength", this.JobQueueLength);
            this.SetParamArrayObj(map, prefix + "ReviewResultSet.", this.ReviewResultSet);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

