/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Car.V20220110.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeApplicationProjectAdvancedConfigResponse : AbstractModel
    {
        
        /// <summary>
        /// Application startup parameters.
        /// 
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("ApplicationParams")]
        public string ApplicationParams{ get; set; }

        /// <summary>
        /// Resolution, in the format of widthxheight, such as 1920x1080.Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("Resolution")]
        public string Resolution{ get; set; }

        /// <summary>
        /// Frame rate. Valid values: 0, 30, 60.Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("FPS")]
        public long? FPS{ get; set; }

        /// <summary>
        /// Minimum bitrate, in Mbps.Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("MinBitrate")]
        public long? MinBitrate{ get; set; }

        /// <summary>
        /// Maximum bitrate, in Mbps.Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("MaxBitrate")]
        public long? MaxBitrate{ get; set; }

        /// <summary>
        /// Waiting time for application pre-launch.Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("PreloadDuration")]
        public string PreloadDuration{ get; set; }

        /// <summary>
        /// Waiting time for reconnection.Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("ReconnectTimeout")]
        public string ReconnectTimeout{ get; set; }

        /// <summary>
        /// Upstream audio options.DisableMixIntoStreamPush: not mixing upstream audio in streaming.Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("UpstreamAudioOption")]
        public string UpstreamAudioOption{ get; set; }

        /// <summary>
        /// Video encoding configuration.Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("VideoEncodeConfig")]
        public VideoEncodeConfig VideoEncodeConfig{ get; set; }

        /// <summary>
        /// Upper limit of the XR application resolution.If the project concurrency type is L or L2, the upper limit is 5000; if the project concurrency type is XL2, the upper limit is 6000.Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("XRMaxWidth")]
        public ulong? XRMaxWidth{ get; set; }

        /// <summary>
        /// Background image information.Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("BackgroundImage")]
        public BackgroundImage BackgroundImage{ get; set; }

        /// <summary>
        /// Disabled code list.Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("DisableVideoCodecs")]
        public string[] DisableVideoCodecs{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "ApplicationParams", this.ApplicationParams);
            this.SetParamSimple(map, prefix + "Resolution", this.Resolution);
            this.SetParamSimple(map, prefix + "FPS", this.FPS);
            this.SetParamSimple(map, prefix + "MinBitrate", this.MinBitrate);
            this.SetParamSimple(map, prefix + "MaxBitrate", this.MaxBitrate);
            this.SetParamSimple(map, prefix + "PreloadDuration", this.PreloadDuration);
            this.SetParamSimple(map, prefix + "ReconnectTimeout", this.ReconnectTimeout);
            this.SetParamSimple(map, prefix + "UpstreamAudioOption", this.UpstreamAudioOption);
            this.SetParamObj(map, prefix + "VideoEncodeConfig.", this.VideoEncodeConfig);
            this.SetParamSimple(map, prefix + "XRMaxWidth", this.XRMaxWidth);
            this.SetParamObj(map, prefix + "BackgroundImage.", this.BackgroundImage);
            this.SetParamArraySimple(map, prefix + "DisableVideoCodecs.", this.DisableVideoCodecs);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

