/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Tke.V20180525.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeReservedInstanceUtilizationRateResponse : AbstractModel
    {
        
        /// <summary>
        /// Usage Rate of Reserved Coupons 
        /// </summary>
        [JsonProperty("UtilizationRateSet")]
        public ReservedInstanceUtilizationRate[] UtilizationRateSet{ get; set; }

        /// <summary>
        /// Total number of pay-as-you-go Pods
        /// </summary>
        [JsonProperty("PodNum")]
        public ulong? PodNum{ get; set; }

        /// <summary>
        ///  Pod Deduction Rate by Reserved Coupons
        /// </summary>
        [JsonProperty("PodRate")]
        public float? PodRate{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamArrayObj(map, prefix + "UtilizationRateSet.", this.UtilizationRateSet);
            this.SetParamSimple(map, prefix + "PodNum", this.PodNum);
            this.SetParamSimple(map, prefix + "PodRate", this.PodRate);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

