/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Cdb.V20170320.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeProxySupportParamResponse : AbstractModel
    {
        
        /// <summary>
        /// Proxy supports the maximum version
        /// </summary>
        [JsonProperty("ProxyVersion")]
        public string ProxyVersion{ get; set; }

        /// <summary>
        /// Whether connection pool is supported
        /// </summary>
        [JsonProperty("SupportPool")]
        public bool? SupportPool{ get; set; }

        /// <summary>
        /// Minimum value of the connection pool
        /// </summary>
        [JsonProperty("PoolMin")]
        public ulong? PoolMin{ get; set; }

        /// <summary>
        /// Maximum value of connection pool
        /// </summary>
        [JsonProperty("PoolMax")]
        public ulong? PoolMax{ get; set; }

        /// <summary>
        /// Whether transaction split is supported
        /// </summary>
        [JsonProperty("SupportTransSplit")]
        public bool? SupportTransSplit{ get; set; }

        /// <summary>
        /// Minimum proxy version that supports connection pool
        /// </summary>
        [JsonProperty("SupportPoolMinVersion")]
        public string SupportPoolMinVersion{ get; set; }

        /// <summary>
        /// Minimum proxy version supporting transaction split
        /// </summary>
        [JsonProperty("SupportTransSplitMinVersion")]
        public string SupportTransSplitMinVersion{ get; set; }

        /// <summary>
        /// Whether setting as read-only is supported.
        /// </summary>
        [JsonProperty("SupportReadOnly")]
        public bool? SupportReadOnly{ get; set; }

        /// <summary>
        /// Whether to automatically balance the load
        /// </summary>
        [JsonProperty("SupportAutoLoadBalance")]
        public bool? SupportAutoLoadBalance{ get; set; }

        /// <summary>
        /// Whether support access mode
        /// </summary>
        [JsonProperty("SupportAccessMode")]
        public bool? SupportAccessMode{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "ProxyVersion", this.ProxyVersion);
            this.SetParamSimple(map, prefix + "SupportPool", this.SupportPool);
            this.SetParamSimple(map, prefix + "PoolMin", this.PoolMin);
            this.SetParamSimple(map, prefix + "PoolMax", this.PoolMax);
            this.SetParamSimple(map, prefix + "SupportTransSplit", this.SupportTransSplit);
            this.SetParamSimple(map, prefix + "SupportPoolMinVersion", this.SupportPoolMinVersion);
            this.SetParamSimple(map, prefix + "SupportTransSplitMinVersion", this.SupportTransSplitMinVersion);
            this.SetParamSimple(map, prefix + "SupportReadOnly", this.SupportReadOnly);
            this.SetParamSimple(map, prefix + "SupportAutoLoadBalance", this.SupportAutoLoadBalance);
            this.SetParamSimple(map, prefix + "SupportAccessMode", this.SupportAccessMode);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

