/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Cdb.V20170320.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeDataBackupOverviewResponse : AbstractModel
    {
        
        /// <summary>
        /// Total capacity of data backups in bytes in the current region (including automatic backups and manual backups).
        /// </summary>
        [JsonProperty("DataBackupVolume")]
        public long? DataBackupVolume{ get; set; }

        /// <summary>
        /// Total number of data backups in the current region.
        /// </summary>
        [JsonProperty("DataBackupCount")]
        public long? DataBackupCount{ get; set; }

        /// <summary>
        /// Total capacity of automatic backups in the current region.
        /// </summary>
        [JsonProperty("AutoBackupVolume")]
        public long? AutoBackupVolume{ get; set; }

        /// <summary>
        /// Total number of automatic backups in the current region.
        /// </summary>
        [JsonProperty("AutoBackupCount")]
        public long? AutoBackupCount{ get; set; }

        /// <summary>
        /// Total capacity of manual backups in the current region.
        /// </summary>
        [JsonProperty("ManualBackupVolume")]
        public long? ManualBackupVolume{ get; set; }

        /// <summary>
        /// Total number of manual backups in the current region.
        /// </summary>
        [JsonProperty("ManualBackupCount")]
        public long? ManualBackupCount{ get; set; }

        /// <summary>
        /// Total capacity of remote backups
        /// </summary>
        [JsonProperty("RemoteBackupVolume")]
        public long? RemoteBackupVolume{ get; set; }

        /// <summary>
        /// Total number of remote backups
        /// </summary>
        [JsonProperty("RemoteBackupCount")]
        public long? RemoteBackupCount{ get; set; }

        /// <summary>
        /// Total capacity of archive backups in the current region
        /// </summary>
        [JsonProperty("DataBackupArchiveVolume")]
        public long? DataBackupArchiveVolume{ get; set; }

        /// <summary>
        /// Total number of archive backups in the current region
        /// </summary>
        [JsonProperty("DataBackupArchiveCount")]
        public long? DataBackupArchiveCount{ get; set; }

        /// <summary>
        /// Total backup capacity of standard storage in current region
        /// </summary>
        [JsonProperty("DataBackupStandbyVolume")]
        public long? DataBackupStandbyVolume{ get; set; }

        /// <summary>
        /// Total number of standard storage backups in current region
        /// </summary>
        [JsonProperty("DataBackupStandbyCount")]
        public long? DataBackupStandbyCount{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "DataBackupVolume", this.DataBackupVolume);
            this.SetParamSimple(map, prefix + "DataBackupCount", this.DataBackupCount);
            this.SetParamSimple(map, prefix + "AutoBackupVolume", this.AutoBackupVolume);
            this.SetParamSimple(map, prefix + "AutoBackupCount", this.AutoBackupCount);
            this.SetParamSimple(map, prefix + "ManualBackupVolume", this.ManualBackupVolume);
            this.SetParamSimple(map, prefix + "ManualBackupCount", this.ManualBackupCount);
            this.SetParamSimple(map, prefix + "RemoteBackupVolume", this.RemoteBackupVolume);
            this.SetParamSimple(map, prefix + "RemoteBackupCount", this.RemoteBackupCount);
            this.SetParamSimple(map, prefix + "DataBackupArchiveVolume", this.DataBackupArchiveVolume);
            this.SetParamSimple(map, prefix + "DataBackupArchiveCount", this.DataBackupArchiveCount);
            this.SetParamSimple(map, prefix + "DataBackupStandbyVolume", this.DataBackupStandbyVolume);
            this.SetParamSimple(map, prefix + "DataBackupStandbyCount", this.DataBackupStandbyCount);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

