/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Tdmysql.V20211122.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeInstanceDataReservedSpaceResponse : AbstractModel
    {
        
        /// <summary>
        /// <p>Actual reserved ratio (%, per node)</p>
        /// </summary>
        [JsonProperty("ReservedRate")]
        public float? ReservedRate{ get; set; }

        /// <summary>
        /// <p>Actual reserved space in GB (single node)</p><p>Unit: GB</p>
        /// </summary>
        [JsonProperty("ReservedSpaceGB")]
        public float? ReservedSpaceGB{ get; set; }

        /// <summary>
        /// <p>Available user space in GB (per node)</p><p>Unit: GB</p>
        /// </summary>
        [JsonProperty("UsableSpaceGB")]
        public float? UsableSpaceGB{ get; set; }

        /// <summary>
        /// <p>true=earlier version (&lt;21.6.4.0), value from the old parameter tdstore_enter_readonly_threshold; false=new version</p>
        /// </summary>
        [JsonProperty("IsLegacy")]
        public bool? IsLegacy{ get; set; }

        /// <summary>
        /// <p>Kernel version number</p>
        /// </summary>
        [JsonProperty("KernelVersion")]
        public string KernelVersion{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "ReservedRate", this.ReservedRate);
            this.SetParamSimple(map, prefix + "ReservedSpaceGB", this.ReservedSpaceGB);
            this.SetParamSimple(map, prefix + "UsableSpaceGB", this.UsableSpaceGB);
            this.SetParamSimple(map, prefix + "IsLegacy", this.IsLegacy);
            this.SetParamSimple(map, prefix + "KernelVersion", this.KernelVersion);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

