/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Ccc.V20200210.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeCallInMetricsResponse : AbstractModel
    {
        
        /// <summary>
        /// Timestamp.
        /// </summary>
        [JsonProperty("Timestamp")]
        public long? Timestamp{ get; set; }

        /// <summary>
        /// Overall metrics.
        /// </summary>
        [JsonProperty("TotalMetrics")]
        public CallInMetrics TotalMetrics{ get; set; }

        /// <summary>
        /// Circuit dimension metrics.
        /// </summary>
        [JsonProperty("NumberMetrics")]
        public CallInNumberMetrics[] NumberMetrics{ get; set; }

        /// <summary>
        /// Skill group dimension metrics.
        /// </summary>
        [JsonProperty("SkillGroupMetrics")]
        public CallInSkillGroupMetrics[] SkillGroupMetrics{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "Timestamp", this.Timestamp);
            this.SetParamObj(map, prefix + "TotalMetrics.", this.TotalMetrics);
            this.SetParamArrayObj(map, prefix + "NumberMetrics.", this.NumberMetrics);
            this.SetParamArrayObj(map, prefix + "SkillGroupMetrics.", this.SkillGroupMetrics);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

