/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Ccc.V20200210.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeTelCallInfoResponse : AbstractModel
    {
        
        /// <summary>
        /// <P>Minutes consumed by outbound package</p>.
        /// </summary>
        [JsonProperty("TelCallOutCount")]
        public long? TelCallOutCount{ get; set; }

        /// <summary>
        /// <P>Minutes consumed by inbound package</p>.
        /// </summary>
        [JsonProperty("TelCallInCount")]
        public long? TelCallInCount{ get; set; }

        /// <summary>
        /// <P>Number of agent usage statistics</p>.
        /// </summary>
        [JsonProperty("SeatUsedCount")]
        public long? SeatUsedCount{ get; set; }

        /// <summary>
        /// <P>Minutes consumed by audio package</p>.
        /// </summary>
        [JsonProperty("VoipCallInCount")]
        [System.Obsolete]
        public long? VoipCallInCount{ get; set; }

        /// <summary>
        /// <P>Minutes consumed by audio package</p>.
        /// </summary>
        [JsonProperty("VOIPCallInCount")]
        public long? VOIPCallInCount{ get; set; }

        /// <summary>
        /// <P>Minutes consumed by offline speech-to-text package</p>.
        /// </summary>
        [JsonProperty("AsrOfflineCount")]
        public long? AsrOfflineCount{ get; set; }

        /// <summary>
        /// <P>Minutes consumed by real-time speech-to-text package</p>.
        /// </summary>
        [JsonProperty("AsrRealtimeCount")]
        public long? AsrRealtimeCount{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "TelCallOutCount", this.TelCallOutCount);
            this.SetParamSimple(map, prefix + "TelCallInCount", this.TelCallInCount);
            this.SetParamSimple(map, prefix + "SeatUsedCount", this.SeatUsedCount);
            this.SetParamSimple(map, prefix + "VoipCallInCount", this.VoipCallInCount);
            this.SetParamSimple(map, prefix + "VOIPCallInCount", this.VOIPCallInCount);
            this.SetParamSimple(map, prefix + "AsrOfflineCount", this.AsrOfflineCount);
            this.SetParamSimple(map, prefix + "AsrRealtimeCount", this.AsrRealtimeCount);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

