/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Apm.V20210622.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeApmServiceMetricResponse : AbstractModel
    {
        
        /// <summary>
        /// List of application metrics.
        /// </summary>
        [JsonProperty("ServiceMetricList")]
        public ApmServiceMetric[] ServiceMetricList{ get; set; }

        /// <summary>
        /// Number of applications meeting the filtering conditions.
        /// </summary>
        [JsonProperty("TotalCount")]
        public long? TotalCount{ get; set; }

        /// <summary>
        /// Warning of the abnormal number of applications.
        /// </summary>
        [JsonProperty("WarningErrorCount")]
        public long? WarningErrorCount{ get; set; }

        /// <summary>
        /// Total number of applications.
        /// </summary>
        [JsonProperty("ApplicationCount")]
        public long? ApplicationCount{ get; set; }

        /// <summary>
        /// Page number.
        /// </summary>
        [JsonProperty("Page")]
        public long? Page{ get; set; }

        /// <summary>
        /// Page size.
        /// </summary>
        [JsonProperty("PageSize")]
        public long? PageSize{ get; set; }

        /// <summary>
        /// Indicates the number of abnormal applications.
        /// </summary>
        [JsonProperty("ErrorCount")]
        public long? ErrorCount{ get; set; }

        /// <summary>
        /// Warning of the number of applications.
        /// </summary>
        [JsonProperty("WarningCount")]
        public long? WarningCount{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamArrayObj(map, prefix + "ServiceMetricList.", this.ServiceMetricList);
            this.SetParamSimple(map, prefix + "TotalCount", this.TotalCount);
            this.SetParamSimple(map, prefix + "WarningErrorCount", this.WarningErrorCount);
            this.SetParamSimple(map, prefix + "ApplicationCount", this.ApplicationCount);
            this.SetParamSimple(map, prefix + "Page", this.Page);
            this.SetParamSimple(map, prefix + "PageSize", this.PageSize);
            this.SetParamSimple(map, prefix + "ErrorCount", this.ErrorCount);
            this.SetParamSimple(map, prefix + "WarningCount", this.WarningCount);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

