/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Aiart.V20221229.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class ChangeClothesRequest : AbstractModel
    {
        
        /// <summary>
        /// URL of the model image.
        /// Image restrictions: The single-edge resolution must be less than 3,000 and greater than 512, and the size after Base64 encoding must be less than 8 MB.
        /// Input requirements:
        /// 1. It is recommended to input a frontal model image that at least fully shows the model's body (whole body, upper body or lower body) and avoids large-angle body deflections or complex poses.
        /// 2. It is recommended to input a 3:4 ratio image for better generation effect.
        /// 3. It is recommended to keep the category of the original clothes in the model image and the category of the replaced clothes the same, or to keep the original clothes' coverage on the model's body equal to or less than the replaced clothes'. (For example, if you need to change the model to wear shorts, the model in the original input image should also wear shorts instead of long pants.) Otherwise, the generation effect will be impaired.
        /// </summary>
        [JsonProperty("ModelUrl")]
        public string ModelUrl{ get; set; }

        /// <summary>
        /// URL of the clothes image.
        /// Image restrictions: single-side resolution less than 3000 and greater than 512, less than 8MB after conversion to Base64 string.
        /// Input requirements:
        /// It is recommended to input a complete front-facing flat image of the clothes, containing only one garment in the image. The type of the clothes supports Upper-body, Lower-body and Dress, and you can choose one from the three. The algorithm will change the model's clothes based on the input model image and the input clothes image.
        /// </summary>
        [JsonProperty("ClothesUrl")]
        public string ClothesUrl{ get; set; }

        /// <summary>
        /// Type of the clothes, which needs to be consistent with the input clothes image.
        /// Supported value:
        /// Upper-body
        /// Lower-body
        /// Dress
        /// </summary>
        [JsonProperty("ClothesType")]
        public string ClothesType{ get; set; }

        /// <summary>
        /// Switch indicating whether to add a logo to the generated image. Default value: 1.
        /// 1: add logo
        /// 0: do not add logo
        /// Other values: add logo
        /// It is recommended to use an obvious logo to indicate that the image result is generated by AI.
        /// </summary>
        [JsonProperty("LogoAdd")]
        public long? LogoAdd{ get; set; }

        /// <summary>
        /// Logo content settings.
        /// By default, the text "Generated by AI" is added to the bottom right corner of the generated image. You can also use other logo.
        /// </summary>
        [JsonProperty("LogoParam")]
        public LogoParam LogoParam{ get; set; }

        /// <summary>
        /// Image return method (base64 or url).
        /// You can specify only one method. Default value: base64.
        /// The URL is valid for 1 hour.
        /// It is recommended to choose url when the generated image resolution is large. Using base64 may cause return failure due to the image being too large.
        /// </summary>
        [JsonProperty("RspImgType")]
        public string RspImgType{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "ModelUrl", this.ModelUrl);
            this.SetParamSimple(map, prefix + "ClothesUrl", this.ClothesUrl);
            this.SetParamSimple(map, prefix + "ClothesType", this.ClothesType);
            this.SetParamSimple(map, prefix + "LogoAdd", this.LogoAdd);
            this.SetParamObj(map, prefix + "LogoParam.", this.LogoParam);
            this.SetParamSimple(map, prefix + "RspImgType", this.RspImgType);
        }
    }
}

