/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Hunyuan.V20230901.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class SubmitConvert3DFormatJobRequest : AbstractModel
    {
        
        /// <summary>
        /// 3D file URL address. The model file size should be less than 200MB;
        /// Supports 3D file inputs in FBX, OBJ, and GLB formats;
        /// For the OBJ format, a compressed package URL must be uploaded, containing URLs for the obj and mtl 3D model files, as well as texture maps;
        /// It is recommended to upload OBJ models generated by HY-3D.
        /// </summary>
        [JsonProperty("File")]
        public InputFile3D File{ get; set; }

        /// <summary>
        /// Returns the 3D file format. valid values:
        /// STL, USDZ, FBX, MP4, GIF;
        /// Example value: STL.
        /// </summary>
        [JsonProperty("Format")]
        public string Format{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamObj(map, prefix + "File.", this.File);
            this.SetParamSimple(map, prefix + "Format", this.Format);
        }
    }
}

