/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Hunyuan.V20230901.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class Submit3DSmartTopologyJobRequest : AbstractModel
    {
        
        /// <summary>
        /// Source 3D file model link
        /// Reference value:glb,obj
        /// One of the file formats is required.
        /// Url: file size cannot exceed 200MB.
        /// 3D model requirements: complex models and topologized models do not support face reduction. recommended input is non-topologized high-poly models, such as those generated by hunyuan 3d. high applicability categories include hard surface, game character, prop, daily objects.
        /// </summary>
        [JsonProperty("File3D")]
        public InputFile3D File3D{ get; set; }

        /// <summary>
        /// Polygon type, indicates the model surface is composed of grid components, defaults to triangle
        /// Reference value:
        /// triangle: triangle face
        /// quadrilateral: triangular and quadrilateral mixed face
        /// </summary>
        [JsonProperty("PolygonType")]
        public string PolygonType{ get; set; }

        /// <summary>
        /// Reduction level bit type
        /// valid values: high, medium, low
        /// </summary>
        [JsonProperty("FaceLevel")]
        public string FaceLevel{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamObj(map, prefix + "File3D.", this.File3D);
            this.SetParamSimple(map, prefix + "PolygonType", this.PolygonType);
            this.SetParamSimple(map, prefix + "FaceLevel", this.FaceLevel);
        }
    }
}

