/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Hunyuan.V20230901.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class SubmitHunyuan3DPartJobRequest : AbstractModel
    {
        
        /// <summary>
        /// Recommends inputting 3D models generated by AIGC
        /// Recommended file size not greater than 200MB
        /// Face count not greater than 1,500,000
        /// Only supports FBX format
        /// </summary>
        [JsonProperty("File")]
        public InputFile3D File{ get; set; }

        /// <summary>
        /// <p>Model component segmentation data;<br>The format is a JSON string, e.g., {"MeshName_part_1":{"face_ids":[1,2,3..],"color":"#FF805C"}}.<br>Here, `face_ids` is an integer array representing the set of face IDs for the segment, and `color` specifies the color.</p>
        /// </summary>
        [JsonProperty("PartSegmentationInfo")]
        public string PartSegmentationInfo{ get; set; }

        /// <summary>
        /// <p>Determines whether component generation is performed in a step-by-step manner.<br>When enabled, providing the original model allows for the generation of a model containing segmentation information, along with the corresponding segmentation data. Users can then edit this information before submitting the segmented model and data to proceed with the component generation process.<br>This parameter is disabled by default.</p>
        /// </summary>
        [JsonProperty("EnableStagedGeneration")]
        public bool? EnableStagedGeneration{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamObj(map, prefix + "File.", this.File);
            this.SetParamSimple(map, prefix + "PartSegmentationInfo", this.PartSegmentationInfo);
            this.SetParamSimple(map, prefix + "EnableStagedGeneration", this.EnableStagedGeneration);
        }
    }
}

