/*
 * Copyright (c) 2018 THL A29 Limited, a Tencent company. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Cwp.V20180228.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeAssetRecentMachineInfoResponse : AbstractModel
    {
        
        /// <summary>
        /// List of total assets
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("TotalList")]
        public AssetKeyVal[] TotalList{ get; set; }

        /// <summary>
        /// List of online assets
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("LiveList")]
        public AssetKeyVal[] LiveList{ get; set; }

        /// <summary>
        /// List of offline assets
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("OfflineList")]
        public AssetKeyVal[] OfflineList{ get; set; }

        /// <summary>
        /// List of risky assets
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("RiskList")]
        public AssetKeyVal[] RiskList{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamArrayObj(map, prefix + "TotalList.", this.TotalList);
            this.SetParamArrayObj(map, prefix + "LiveList.", this.LiveList);
            this.SetParamArrayObj(map, prefix + "OfflineList.", this.OfflineList);
            this.SetParamArrayObj(map, prefix + "RiskList.", this.RiskList);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

