/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Cwp.V20180228.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeAssetHostTotalCountResponse : AbstractModel
    {
        
        /// <summary>
        /// Number of individual resources
        /// system: resource monitoring
        /// account: account
        /// port: port
        /// process: process
        /// app: application software
        /// database: database
        /// webapp: Web application
        /// webframe: Web framework
        /// webservice: Web service
        /// weblocation: Web site
        /// systempackage: system installation package
        /// jar: jar package
        /// initservice: startup service
        /// env: environment variable
        /// coremodule: kernel module
        /// </summary>
        [JsonProperty("Types")]
        public AssetKeyVal[] Types{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamArrayObj(map, prefix + "Types.", this.Types);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

