/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Cwp.V20180228.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeAssetTypeTopResponse : AbstractModel
    {
        
        /// <summary>
        /// Top 5 accounts
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("User")]
        public AssetKeyVal[] User{ get; set; }

        /// <summary>
        /// Top 5 ports
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("Port")]
        public AssetKeyVal[] Port{ get; set; }

        /// <summary>
        /// Top 5 processes
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("Process")]
        public AssetKeyVal[] Process{ get; set; }

        /// <summary>
        /// Top 5 software
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("Software")]
        public AssetKeyVal[] Software{ get; set; }

        /// <summary>
        /// Top 5 databases
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("Database")]
        public AssetKeyVal[] Database{ get; set; }

        /// <summary>
        /// Top 5 web applications
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("WebApp")]
        public AssetKeyVal[] WebApp{ get; set; }

        /// <summary>
        /// Top 5 web sites
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("WebLocation")]
        public AssetKeyVal[] WebLocation{ get; set; }

        /// <summary>
        /// Top 5 web frameworks
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("WebFrame")]
        public AssetKeyVal[] WebFrame{ get; set; }

        /// <summary>
        /// Top 5 web services
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("WebService")]
        public AssetKeyVal[] WebService{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamArrayObj(map, prefix + "User.", this.User);
            this.SetParamArrayObj(map, prefix + "Port.", this.Port);
            this.SetParamArrayObj(map, prefix + "Process.", this.Process);
            this.SetParamArrayObj(map, prefix + "Software.", this.Software);
            this.SetParamArrayObj(map, prefix + "Database.", this.Database);
            this.SetParamArrayObj(map, prefix + "WebApp.", this.WebApp);
            this.SetParamArrayObj(map, prefix + "WebLocation.", this.WebLocation);
            this.SetParamArrayObj(map, prefix + "WebFrame.", this.WebFrame);
            this.SetParamArrayObj(map, prefix + "WebService.", this.WebService);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

