/*
 * Copyright (c) 2018 THL A29 Limited, a Tencent company. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Cwp.V20180228.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeAttackStatisticsResponse : AbstractModel
    {
        
        /// <summary>
        /// Total Number of Attacks
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("PendingAttackCount")]
        public ulong? PendingAttackCount{ get; set; }

        /// <summary>
        /// Total Attack Attempts
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("PendingTryAttackCount")]
        public ulong? PendingTryAttackCount{ get; set; }

        /// <summary>
        /// Total Number of Successful Attacks
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("PendingSuccAttackCount")]
        public ulong? PendingSuccAttackCount{ get; set; }

        /// <summary>
        /// Number of New Attacks Today
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("PendingNewAttackCount")]
        public ulong? PendingNewAttackCount{ get; set; }

        /// <summary>
        /// Total Number of Assets Under Attack
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("AttackedAssetCount")]
        public ulong? AttackedAssetCount{ get; set; }

        /// <summary>
        /// Number of New Attacked Assets Today
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("NewAttackedAssetCount")]
        public ulong? NewAttackedAssetCount{ get; set; }

        /// <summary>
        /// Total Number of Attacked Ports
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("AttackedPortCount")]
        public ulong? AttackedPortCount{ get; set; }

        /// <summary>
        /// Number of New Attacked Ports Today
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("NewAttackedPortCount")]
        public ulong? NewAttackedPortCount{ get; set; }

        /// <summary>
        /// Total Number of Attack Source IPs
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("AttackSrcIpCount")]
        public ulong? AttackSrcIpCount{ get; set; }

        /// <summary>
        /// Number of New Attacking Source IPs Today
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("NewAttackSrcIpCount")]
        public ulong? NewAttackSrcIpCount{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "PendingAttackCount", this.PendingAttackCount);
            this.SetParamSimple(map, prefix + "PendingTryAttackCount", this.PendingTryAttackCount);
            this.SetParamSimple(map, prefix + "PendingSuccAttackCount", this.PendingSuccAttackCount);
            this.SetParamSimple(map, prefix + "PendingNewAttackCount", this.PendingNewAttackCount);
            this.SetParamSimple(map, prefix + "AttackedAssetCount", this.AttackedAssetCount);
            this.SetParamSimple(map, prefix + "NewAttackedAssetCount", this.NewAttackedAssetCount);
            this.SetParamSimple(map, prefix + "AttackedPortCount", this.AttackedPortCount);
            this.SetParamSimple(map, prefix + "NewAttackedPortCount", this.NewAttackedPortCount);
            this.SetParamSimple(map, prefix + "AttackSrcIpCount", this.AttackSrcIpCount);
            this.SetParamSimple(map, prefix + "NewAttackSrcIpCount", this.NewAttackSrcIpCount);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

