/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Cwp.V20180228.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeMachineRiskCntResponse : AbstractModel
    {
        
        /// <summary>
        /// Cross-region log-in
        /// </summary>
        [JsonProperty("HostLogin")]
        public ulong? HostLogin{ get; set; }

        /// <summary>
        /// Password cracking
        /// </summary>
        [JsonProperty("BruteAttack")]
        public ulong? BruteAttack{ get; set; }

        /// <summary>
        /// Malicious request
        /// </summary>
        [JsonProperty("MaliciousRequest")]
        public ulong? MaliciousRequest{ get; set; }

        /// <summary>
        /// Reverse Shell
        /// </summary>
        [JsonProperty("ReverseShell")]
        public ulong? ReverseShell{ get; set; }

        /// <summary>
        /// High-risk command
        /// </summary>
        [JsonProperty("Bash")]
        public ulong? Bash{ get; set; }

        /// <summary>
        /// Local privilege escalation
        /// </summary>
        [JsonProperty("PrivilegeEscalation")]
        public ulong? PrivilegeEscalation{ get; set; }

        /// <summary>
        /// Trojan
        /// </summary>
        [JsonProperty("Malware")]
        public ulong? Malware{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "HostLogin", this.HostLogin);
            this.SetParamSimple(map, prefix + "BruteAttack", this.BruteAttack);
            this.SetParamSimple(map, prefix + "MaliciousRequest", this.MaliciousRequest);
            this.SetParamSimple(map, prefix + "ReverseShell", this.ReverseShell);
            this.SetParamSimple(map, prefix + "Bash", this.Bash);
            this.SetParamSimple(map, prefix + "PrivilegeEscalation", this.PrivilegeEscalation);
            this.SetParamSimple(map, prefix + "Malware", this.Malware);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

