/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Cwp.V20180228.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeMachineRegionsResponse : AbstractModel
    {
        
        /// <summary>
        /// List of Cloud Virtual Machine regions
        /// </summary>
        [JsonProperty("CVM")]
        public RegionInfo[] CVM{ get; set; }

        /// <summary>
        /// List of BM machine regions
        /// </summary>
        [JsonProperty("BM")]
        public RegionInfo[] BM{ get; set; }

        /// <summary>
        /// List of Lighthouse regions
        /// </summary>
        [JsonProperty("LH")]
        public RegionInfo[] LH{ get; set; }

        /// <summary>
        /// List of Edge Computing Machine regions
        /// </summary>
        [JsonProperty("ECM")]
        public RegionInfo[] ECM{ get; set; }

        /// <summary>
        /// List of Hybrid Cloud regions
        /// </summary>
        [JsonProperty("Other")]
        public RegionInfo[] Other{ get; set; }

        /// <summary>
        /// List of all regions (including above regions)
        /// </summary>
        [JsonProperty("ALL")]
        public RegionInfo[] ALL{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamArrayObj(map, prefix + "CVM.", this.CVM);
            this.SetParamArrayObj(map, prefix + "BM.", this.BM);
            this.SetParamArrayObj(map, prefix + "LH.", this.LH);
            this.SetParamArrayObj(map, prefix + "ECM.", this.ECM);
            this.SetParamArrayObj(map, prefix + "Other.", this.Other);
            this.SetParamArrayObj(map, prefix + "ALL.", this.ALL);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

