/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Cwp.V20180228.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeBanStatusResponse : AbstractModel
    {
        
        /// <summary>
        /// <p>(Deprecated) Blocking switch status: 0 -- Off; 1 -- Advanced blocking; 2 -- Basic blocking (blocks only blacklisted IPs in the intelligence database)</p>
        /// </summary>
        [JsonProperty("Status")]
        public ulong? Status{ get; set; }

        /// <summary>
        /// <p>Whether to show pop-up prompts. false: disabled; true: enabled</p>
        /// </summary>
        [JsonProperty("ShowTips")]
        public bool? ShowTips{ get; set; }

        /// <summary>
        /// <p>Whether to enable intelligent allowlisting mode</p>
        /// </summary>
        [JsonProperty("OpenSmartMode")]
        public bool? OpenSmartMode{ get; set; }

        /// <summary>
        /// <p>Whether to enable threat-intelligence IP blocking</p>
        /// </summary>
        [JsonProperty("BanBlackIp")]
        public bool? BanBlackIp{ get; set; }

        /// <summary>
        /// <p>Whether to enable vulnerability-related IP blocking</p>
        /// </summary>
        [JsonProperty("BanVulIp")]
        public bool? BanVulIp{ get; set; }

        /// <summary>
        /// <p>Whether to enable rule blocking</p>
        /// </summary>
        [JsonProperty("BanByRule")]
        public bool? BanByRule{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "Status", this.Status);
            this.SetParamSimple(map, prefix + "ShowTips", this.ShowTips);
            this.SetParamSimple(map, prefix + "OpenSmartMode", this.OpenSmartMode);
            this.SetParamSimple(map, prefix + "BanBlackIp", this.BanBlackIp);
            this.SetParamSimple(map, prefix + "BanVulIp", this.BanVulIp);
            this.SetParamSimple(map, prefix + "BanByRule", this.BanByRule);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

