/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Cwp.V20180228.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeVulHostCountScanTimeResponse : AbstractModel
    {
        
        /// <summary>
        /// Total number of vulnerabilities
        /// </summary>
        [JsonProperty("TotalVulCount")]
        public ulong? TotalVulCount{ get; set; }

        /// <summary>
        /// Number of hosts affected by vulnerabilities
        /// </summary>
        [JsonProperty("VulHostCount")]
        public ulong? VulHostCount{ get; set; }

        /// <summary>
        /// Scan time
        /// </summary>
        [JsonProperty("ScanTime")]
        public string ScanTime{ get; set; }

        /// <summary>
        /// Whether the detection is carried out for the first time
        /// </summary>
        [JsonProperty("IfFirstScan")]
        public bool? IfFirstScan{ get; set; }

        /// <summary>
        /// ID of the ongoing task. The value is 0 if no such task exists.
        /// </summary>
        [JsonProperty("TaskId")]
        public ulong? TaskId{ get; set; }

        /// <summary>
        /// Last vulnerability fixing time
        /// </summary>
        [JsonProperty("LastFixTime")]
        public string LastFixTime{ get; set; }

        /// <summary>
        /// Whether vulnerabilities supporting automatic fixing exist
        /// </summary>
        [JsonProperty("hadAutoFixVul")]
        public bool? hadAutoFixVul{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "TotalVulCount", this.TotalVulCount);
            this.SetParamSimple(map, prefix + "VulHostCount", this.VulHostCount);
            this.SetParamSimple(map, prefix + "ScanTime", this.ScanTime);
            this.SetParamSimple(map, prefix + "IfFirstScan", this.IfFirstScan);
            this.SetParamSimple(map, prefix + "TaskId", this.TaskId);
            this.SetParamSimple(map, prefix + "LastFixTime", this.LastFixTime);
            this.SetParamSimple(map, prefix + "hadAutoFixVul", this.hadAutoFixVul);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

