/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Cwp.V20180228.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeLoginTypeGlobalConfResponse : AbstractModel
    {
        
        /// <summary>
        /// Whether anti-uninstall is enabled <li>0 No</li> <li>1 Yes</li> <li>9 Not set, same as 0 means not enabled</li>
        /// </summary>
        [JsonProperty("Enable")]
        public ulong? Enable{ get; set; }

        /// <summary>
        /// Scope <li>0 Selected host</li> <li>1 All hosts</li>
        /// </summary>
        [JsonProperty("Scope")]
        public ulong? Scope{ get; set; }

        /// <summary>
        /// Selected host configuration count
        /// </summary>
        [JsonProperty("IncludeHostCount")]
        public ulong? IncludeHostCount{ get; set; }

        /// <summary>
        /// Deselect host configuration count
        /// </summary>
        [JsonProperty("ExcludeHostCount")]
        public ulong? ExcludeHostCount{ get; set; }

        /// <summary>
        /// Select quuid configuration list
        /// </summary>
        [JsonProperty("IncludeQuuid")]
        public string[] IncludeQuuid{ get; set; }

        /// <summary>
        /// Exclude quuid configuration list
        /// </summary>
        [JsonProperty("ExcludeQuuid")]
        public string[] ExcludeQuuid{ get; set; }

        /// <summary>
        /// Number of Machines Enabled
        /// </summary>
        [JsonProperty("EnableCount")]
        public ulong? EnableCount{ get; set; }

        /// <summary>
        /// Number of inactive machines
        /// </summary>
        [JsonProperty("DisableCount")]
        public ulong? DisableCount{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "Enable", this.Enable);
            this.SetParamSimple(map, prefix + "Scope", this.Scope);
            this.SetParamSimple(map, prefix + "IncludeHostCount", this.IncludeHostCount);
            this.SetParamSimple(map, prefix + "ExcludeHostCount", this.ExcludeHostCount);
            this.SetParamArraySimple(map, prefix + "IncludeQuuid.", this.IncludeQuuid);
            this.SetParamArraySimple(map, prefix + "ExcludeQuuid.", this.ExcludeQuuid);
            this.SetParamSimple(map, prefix + "EnableCount", this.EnableCount);
            this.SetParamSimple(map, prefix + "DisableCount", this.DisableCount);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

