/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Cwp.V20180228.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeVulTrendResponse : AbstractModel
    {
        
        /// <summary>
        /// Number of vulnerability exploitation attacks in the past six months
        /// </summary>
        [JsonProperty("VulEventCount")]
        public ulong? VulEventCount{ get; set; }

        /// <summary>
        /// Number of new vulnerability exploitation attacks in the past six months
        /// </summary>
        [JsonProperty("IncreaseVulEventCount")]
        public ulong? IncreaseVulEventCount{ get; set; }

        /// <summary>
        /// Notable vulnerabilities attacked in the past six months
        /// </summary>
        [JsonProperty("HotVulCount")]
        public ulong? HotVulCount{ get; set; }

        /// <summary>
        /// New notable vulnerabilities attacked in the past six months
        /// </summary>
        [JsonProperty("IncreaseHotVulCount")]
        public ulong? IncreaseHotVulCount{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "VulEventCount", this.VulEventCount);
            this.SetParamSimple(map, prefix + "IncreaseVulEventCount", this.IncreaseVulEventCount);
            this.SetParamSimple(map, prefix + "HotVulCount", this.HotVulCount);
            this.SetParamSimple(map, prefix + "IncreaseHotVulCount", this.IncreaseHotVulCount);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

