/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Cwp.V20180228.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeSecurityEventsCntResponse : AbstractModel
    {
        
        /// <summary>
        /// Trojan file-related risk event
        /// </summary>
        [JsonProperty("Malware")]
        public SecurityEventInfo Malware{ get; set; }

        /// <summary>
        /// Log-in audit-related risk event
        /// </summary>
        [JsonProperty("HostLogin")]
        public SecurityEventInfo HostLogin{ get; set; }

        /// <summary>
        /// Password cracking-related risk event
        /// </summary>
        [JsonProperty("BruteAttack")]
        public SecurityEventInfo BruteAttack{ get; set; }

        /// <summary>
        /// Malicious request-related risk event
        /// </summary>
        [JsonProperty("RiskDns")]
        public SecurityEventInfo RiskDns{ get; set; }

        /// <summary>
        /// High-risk command-related risk event
        /// </summary>
        [JsonProperty("Bash")]
        public SecurityEventInfo Bash{ get; set; }

        /// <summary>
        /// Local privilege escalation-related risk event
        /// </summary>
        [JsonProperty("PrivilegeRules")]
        public SecurityEventInfo PrivilegeRules{ get; set; }

        /// <summary>
        /// Reverse Shell-related risk event
        /// </summary>
        [JsonProperty("ReverseShell")]
        public SecurityEventInfo ReverseShell{ get; set; }

        /// <summary>
        /// Application vulnerability-related risk event
        /// </summary>
        [JsonProperty("SysVul")]
        public SecurityEventInfo SysVul{ get; set; }

        /// <summary>
        /// Web application vulnerability-related risk event
        /// </summary>
        [JsonProperty("WebVul")]
        public SecurityEventInfo WebVul{ get; set; }

        /// <summary>
        /// Emergency vulnerability-related risk event
        /// </summary>
        [JsonProperty("EmergencyVul")]
        public SecurityEventInfo EmergencyVul{ get; set; }

        /// <summary>
        /// Security baseline-related risk event
        /// </summary>
        [JsonProperty("BaseLine")]
        public SecurityEventInfo BaseLine{ get; set; }

        /// <summary>
        /// Attack detection-related risk event
        /// </summary>
        [JsonProperty("AttackLogs")]
        public SecurityEventInfo AttackLogs{ get; set; }

        /// <summary>
        /// Number of affected machines
        /// </summary>
        [JsonProperty("EffectMachineCount")]
        public ulong? EffectMachineCount{ get; set; }

        /// <summary>
        /// Total of number of events
        /// </summary>
        [JsonProperty("EventsCount")]
        public ulong? EventsCount{ get; set; }

        /// <summary>
        /// Total of Windows system vulnerability events
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("WindowVul")]
        public SecurityEventInfo WindowVul{ get; set; }

        /// <summary>
        /// Total of Linux system vulnerability events
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("LinuxVul")]
        public SecurityEventInfo LinuxVul{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamObj(map, prefix + "Malware.", this.Malware);
            this.SetParamObj(map, prefix + "HostLogin.", this.HostLogin);
            this.SetParamObj(map, prefix + "BruteAttack.", this.BruteAttack);
            this.SetParamObj(map, prefix + "RiskDns.", this.RiskDns);
            this.SetParamObj(map, prefix + "Bash.", this.Bash);
            this.SetParamObj(map, prefix + "PrivilegeRules.", this.PrivilegeRules);
            this.SetParamObj(map, prefix + "ReverseShell.", this.ReverseShell);
            this.SetParamObj(map, prefix + "SysVul.", this.SysVul);
            this.SetParamObj(map, prefix + "WebVul.", this.WebVul);
            this.SetParamObj(map, prefix + "EmergencyVul.", this.EmergencyVul);
            this.SetParamObj(map, prefix + "BaseLine.", this.BaseLine);
            this.SetParamObj(map, prefix + "AttackLogs.", this.AttackLogs);
            this.SetParamSimple(map, prefix + "EffectMachineCount", this.EffectMachineCount);
            this.SetParamSimple(map, prefix + "EventsCount", this.EventsCount);
            this.SetParamObj(map, prefix + "WindowVul.", this.WindowVul);
            this.SetParamObj(map, prefix + "LinuxVul.", this.LinuxVul);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

