/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Cwp.V20180228.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribePatchInfoResponse : AbstractModel
    {
        
        /// <summary>
        /// kb No.
        /// </summary>
        [JsonProperty("KbNo")]
        public string KbNo{ get; set; }

        /// <summary>
        /// kb name
        /// </summary>
        [JsonProperty("PatchName")]
        public string PatchName{ get; set; }

        /// <summary>
        /// kb release date
        /// </summary>
        [JsonProperty("PublishTime")]
        public string PublishTime{ get; set; }

        /// <summary>
        /// Reference link
        /// </summary>
        [JsonProperty("ReferUrl")]
        public string ReferUrl{ get; set; }

        /// <summary>
        /// Number of vulnerabilities
        /// </summary>
        [JsonProperty("VulCount")]
        public ulong? VulCount{ get; set; }

        /// <summary>
        /// List of vulnerability details associated with the patch
        /// </summary>
        [JsonProperty("RelateVulInfoList")]
        public RelateVulInfo[] RelateVulInfoList{ get; set; }

        /// <summary>
        /// Patch ID
        /// </summary>
        [JsonProperty("KbId")]
        public ulong? KbId{ get; set; }

        /// <summary>
        /// Associated vulnerability CveId, multiple IDs split by ","
        /// </summary>
        [JsonProperty("RelateVulCveId")]
        public string RelateVulCveId{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "KbNo", this.KbNo);
            this.SetParamSimple(map, prefix + "PatchName", this.PatchName);
            this.SetParamSimple(map, prefix + "PublishTime", this.PublishTime);
            this.SetParamSimple(map, prefix + "ReferUrl", this.ReferUrl);
            this.SetParamSimple(map, prefix + "VulCount", this.VulCount);
            this.SetParamArrayObj(map, prefix + "RelateVulInfoList.", this.RelateVulInfoList);
            this.SetParamSimple(map, prefix + "KbId", this.KbId);
            this.SetParamSimple(map, prefix + "RelateVulCveId", this.RelateVulCveId);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

