/*
 * Copyright (c) 2018 THL A29 Limited, a Tencent company. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Cwp.V20180228.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeAssetInfoResponse : AbstractModel
    {
        
        /// <summary>
        /// Number of Hosts
        /// </summary>
        [JsonProperty("MachineCount")]
        public ulong? MachineCount{ get; set; }

        /// <summary>
        /// Number of Accounts
        /// </summary>
        [JsonProperty("AccountCount")]
        public ulong? AccountCount{ get; set; }

        /// <summary>
        /// Number of ports
        /// </summary>
        [JsonProperty("PortCount")]
        public ulong? PortCount{ get; set; }

        /// <summary>
        /// Number of Processes
        /// </summary>
        [JsonProperty("ProcessCount")]
        public ulong? ProcessCount{ get; set; }

        /// <summary>
        /// Number of software
        /// </summary>
        [JsonProperty("SoftwareCount")]
        public ulong? SoftwareCount{ get; set; }

        /// <summary>
        /// Number of databases
        /// </summary>
        [JsonProperty("DatabaseCount")]
        public ulong? DatabaseCount{ get; set; }

        /// <summary>
        /// Number of web applications
        /// </summary>
        [JsonProperty("WebAppCount")]
        public ulong? WebAppCount{ get; set; }

        /// <summary>
        /// Number of web frameworks
        /// </summary>
        [JsonProperty("WebFrameCount")]
        public ulong? WebFrameCount{ get; set; }

        /// <summary>
        /// Number of web services
        /// </summary>
        [JsonProperty("WebServiceCount")]
        public ulong? WebServiceCount{ get; set; }

        /// <summary>
        /// Number of web sites
        /// </summary>
        [JsonProperty("WebLocationCount")]
        public ulong? WebLocationCount{ get; set; }

        /// <summary>
        /// New accounts today
        /// </summary>
        [JsonProperty("AccountNewCount")]
        public long? AccountNewCount{ get; set; }

        /// <summary>
        /// New ports today
        /// </summary>
        [JsonProperty("PortNewCount")]
        public long? PortNewCount{ get; set; }

        /// <summary>
        /// New processes today
        /// </summary>
        [JsonProperty("ProcessNewCount")]
        public long? ProcessNewCount{ get; set; }

        /// <summary>
        /// New software today
        /// </summary>
        [JsonProperty("SoftwareNewCount")]
        public long? SoftwareNewCount{ get; set; }

        /// <summary>
        /// New databases today
        /// </summary>
        [JsonProperty("DatabaseNewCount")]
        public long? DatabaseNewCount{ get; set; }

        /// <summary>
        /// New web applications today
        /// </summary>
        [JsonProperty("WebAppNewCount")]
        public long? WebAppNewCount{ get; set; }

        /// <summary>
        /// New web frameworks today
        /// </summary>
        [JsonProperty("WebFrameNewCount")]
        public long? WebFrameNewCount{ get; set; }

        /// <summary>
        /// New web services today
        /// </summary>
        [JsonProperty("WebServiceNewCount")]
        public long? WebServiceNewCount{ get; set; }

        /// <summary>
        /// New web sites today
        /// </summary>
        [JsonProperty("WebLocationNewCount")]
        public long? WebLocationNewCount{ get; set; }

        /// <summary>
        /// New hosts today
        /// </summary>
        [JsonProperty("MachineNewCount")]
        public long? MachineNewCount{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "MachineCount", this.MachineCount);
            this.SetParamSimple(map, prefix + "AccountCount", this.AccountCount);
            this.SetParamSimple(map, prefix + "PortCount", this.PortCount);
            this.SetParamSimple(map, prefix + "ProcessCount", this.ProcessCount);
            this.SetParamSimple(map, prefix + "SoftwareCount", this.SoftwareCount);
            this.SetParamSimple(map, prefix + "DatabaseCount", this.DatabaseCount);
            this.SetParamSimple(map, prefix + "WebAppCount", this.WebAppCount);
            this.SetParamSimple(map, prefix + "WebFrameCount", this.WebFrameCount);
            this.SetParamSimple(map, prefix + "WebServiceCount", this.WebServiceCount);
            this.SetParamSimple(map, prefix + "WebLocationCount", this.WebLocationCount);
            this.SetParamSimple(map, prefix + "AccountNewCount", this.AccountNewCount);
            this.SetParamSimple(map, prefix + "PortNewCount", this.PortNewCount);
            this.SetParamSimple(map, prefix + "ProcessNewCount", this.ProcessNewCount);
            this.SetParamSimple(map, prefix + "SoftwareNewCount", this.SoftwareNewCount);
            this.SetParamSimple(map, prefix + "DatabaseNewCount", this.DatabaseNewCount);
            this.SetParamSimple(map, prefix + "WebAppNewCount", this.WebAppNewCount);
            this.SetParamSimple(map, prefix + "WebFrameNewCount", this.WebFrameNewCount);
            this.SetParamSimple(map, prefix + "WebServiceNewCount", this.WebServiceNewCount);
            this.SetParamSimple(map, prefix + "WebLocationNewCount", this.WebLocationNewCount);
            this.SetParamSimple(map, prefix + "MachineNewCount", this.MachineNewCount);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

