/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Cwp.V20180228.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeSecurityTrendsResponse : AbstractModel
    {
        
        /// <summary>
        /// Array of counted Trojan events
        /// </summary>
        [JsonProperty("Malwares")]
        public SecurityTrend[] Malwares{ get; set; }

        /// <summary>
        /// Array of counted cross-region log-in events
        /// </summary>
        [JsonProperty("NonLocalLoginPlaces")]
        public SecurityTrend[] NonLocalLoginPlaces{ get; set; }

        /// <summary>
        /// Array of counted password cracking events
        /// </summary>
        [JsonProperty("BruteAttacks")]
        public SecurityTrend[] BruteAttacks{ get; set; }

        /// <summary>
        /// Array of counted vulnerabilities
        /// </summary>
        [JsonProperty("Vuls")]
        public SecurityTrend[] Vuls{ get; set; }

        /// <summary>
        /// Array of counted baselines
        /// </summary>
        [JsonProperty("BaseLines")]
        public SecurityTrend[] BaseLines{ get; set; }

        /// <summary>
        /// Array of counted malicious requests
        /// </summary>
        [JsonProperty("MaliciousRequests")]
        public SecurityTrend[] MaliciousRequests{ get; set; }

        /// <summary>
        /// Array of counted high-risk command
        /// </summary>
        [JsonProperty("HighRiskBashs")]
        public SecurityTrend[] HighRiskBashs{ get; set; }

        /// <summary>
        /// Array of counted reverse shell
        /// </summary>
        [JsonProperty("ReverseShells")]
        public SecurityTrend[] ReverseShells{ get; set; }

        /// <summary>
        /// Array of counted local privilege escalation
        /// </summary>
        [JsonProperty("PrivilegeEscalations")]
        public SecurityTrend[] PrivilegeEscalations{ get; set; }

        /// <summary>
        /// Array of counted network attacks
        /// </summary>
        [JsonProperty("CyberAttacks")]
        public SecurityTrend[] CyberAttacks{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamArrayObj(map, prefix + "Malwares.", this.Malwares);
            this.SetParamArrayObj(map, prefix + "NonLocalLoginPlaces.", this.NonLocalLoginPlaces);
            this.SetParamArrayObj(map, prefix + "BruteAttacks.", this.BruteAttacks);
            this.SetParamArrayObj(map, prefix + "Vuls.", this.Vuls);
            this.SetParamArrayObj(map, prefix + "BaseLines.", this.BaseLines);
            this.SetParamArrayObj(map, prefix + "MaliciousRequests.", this.MaliciousRequests);
            this.SetParamArrayObj(map, prefix + "HighRiskBashs.", this.HighRiskBashs);
            this.SetParamArrayObj(map, prefix + "ReverseShells.", this.ReverseShells);
            this.SetParamArrayObj(map, prefix + "PrivilegeEscalations.", this.PrivilegeEscalations);
            this.SetParamArrayObj(map, prefix + "CyberAttacks.", this.CyberAttacks);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

