/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Cwp.V20180228.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class DescribeScreenHostInvasionResponse : AbstractModel
    {
        
        /// <summary>
        /// List of network attack event
        /// </summary>
        [JsonProperty("DefendAttackLog")]
        public ScreenDefendAttackLog[] DefendAttackLog{ get; set; }

        /// <summary>
        /// List of intrusion detection event
        /// </summary>
        [JsonProperty("InvasionEvents")]
        public ScreenInvasion[] InvasionEvents{ get; set; }

        /// <summary>
        /// List of vulnerability event
        /// </summary>
        [JsonProperty("Vul")]
        public ScreenVulInfo[] Vul{ get; set; }

        /// <summary>
        /// List of baseline event
        /// Note: This field may return null, indicating that no valid values can be obtained.
        /// </summary>
        [JsonProperty("Baseline")]
        public ScreenBaselineInfo[] Baseline{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamArrayObj(map, prefix + "DefendAttackLog.", this.DefendAttackLog);
            this.SetParamArrayObj(map, prefix + "InvasionEvents.", this.InvasionEvents);
            this.SetParamArrayObj(map, prefix + "Vul.", this.Vul);
            this.SetParamArrayObj(map, prefix + "Baseline.", this.Baseline);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

