/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Vclm.V20240523.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class SubmitImageToVideoViduJobRequest : AbstractModel
    {
        
        /// <summary>
        /// <p>Whether to use recommended prompts, off by default<br>-true: Yes, the system automatically recommends prompts and uses prompt content to generate video. The number of recommended prompts is 1.<br>-false: No, generate video based on input prompt.<br>Note: Each task consumes 1 more point when recommended prompts are enabled.</p>
        /// </summary>
        [JsonProperty("IsRec")]
        public bool? IsRec{ get; set; }

        /// <summary>
        /// <p>Voice type ID<br>Used to determine the voice type in the video. If left empty, the system will automatically recommend. Optional enumerated values reference list: supported timbre list<br>Voice clone functionality is not currently supported</p>
        /// </summary>
        [JsonProperty("VoiceId")]
        public string VoiceId{ get; set; }

        /// <summary>
        /// <p>Exercise range<br>Default: auto, available values: auto, small, medium, large<br>Note: This parameter does not take effect for q2 and q3 series models.</p>
        /// </summary>
        [JsonProperty("MovementAmplitude")]
        public string MovementAmplitude{ get; set; }

        /// <summary>
        /// <p>bgm</p>
        /// </summary>
        [JsonProperty("Bgm")]
        public bool? Bgm{ get; set; }

        /// <summary>
        /// <p>Audio type, required when audio is true, default is all<br>Note: This parameter currently only supports audio split for q2, q1, and 2.0 series models</p><p>Enumeration value:</p><ul><li>all: Sound effects + voice</li><li>speech_only: Voice only</li><li>sound_effect_only: Sound effects only</li></ul>
        /// </summary>
        [JsonProperty("AudioType")]
        public string AudioType{ get; set; }

        /// <summary>
        /// <p>Metadata identification, a string in json format, passthrough field. You can customize the format or use the example format, for example:<br>{<br>&quot;Label&quot;: &quot;your_label&quot;,<br>&quot;ContentProducer&quot;: &quot;your_content_producer&quot;,<br>&quot;ContentPropagator&quot;: &quot;your_content_propagator&quot;,<br>&quot;ProduceID&quot;: &quot;your_product_id&quot;,<br>&quot;PropagateID&quot;: &quot;your_propagate_id&quot;,<br>&quot;ReservedCode1&quot;: &quot;your_reserved_code1&quot;,<br>&quot;ReservedCode2&quot;: &quot;your_reserved_code2&quot;<br>}<br>If empty, use the metadata identification generated by vidu by default.</p>
        /// </summary>
        [JsonProperty("MetaData")]
        public string MetaData{ get; set; }

        /// <summary>
        /// <p>Callback protocol<br>You need to actively set Callback_url when creating a task. The request method is POST. Upon video generation completion, a Callback request containing the latest task status will be sent to this address. The content structure of the Callback request matches the return format of the query task API.<br>The "status" returned by the Callback includes the following states:</p><ul><li>success Task completed (e.g., if sending fails, Callback three times)</li><li>failed Task failure (e.g., if sending fails, Callback three times)</li></ul>
        /// </summary>
        [JsonProperty("CallbackUrl")]
        public string CallbackUrl{ get; set; }

        /// <summary>
        /// <p>Pass-through parameter<br>Without any processing, only data transmission<br>Note: Up to 1048576 characters</p>
        /// </summary>
        [JsonProperty("Payload")]
        public string Payload{ get; set; }

        /// <summary>
        /// <p>Off-peak mode, defaults to false. Available values:</p><ul><li>true: Generate video in off-peak mode;</li><li>false: Generate video instantly;<br>Note 1: Off-peak mode consumes lower points.<br>Note 2: Tasks submitted in off-peak mode will be processed within 48 hours. Uncompleted tasks will be canceled automatically, and the points of the task will be returned.</li></ul>
        /// </summary>
        [JsonProperty("OffPeak")]
        public bool? OffPeak{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "IsRec", this.IsRec);
            this.SetParamSimple(map, prefix + "VoiceId", this.VoiceId);
            this.SetParamSimple(map, prefix + "MovementAmplitude", this.MovementAmplitude);
            this.SetParamSimple(map, prefix + "Bgm", this.Bgm);
            this.SetParamSimple(map, prefix + "AudioType", this.AudioType);
            this.SetParamSimple(map, prefix + "MetaData", this.MetaData);
            this.SetParamSimple(map, prefix + "CallbackUrl", this.CallbackUrl);
            this.SetParamSimple(map, prefix + "Payload", this.Payload);
            this.SetParamSimple(map, prefix + "OffPeak", this.OffPeak);
        }
    }
}

