/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Ses.V20201002.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class CreateCustomBlacklistResponse : AbstractModel
    {
        
        /// <summary>
        /// Total number of recipients.
        /// </summary>
        [JsonProperty("TotalCount")]
        public ulong? TotalCount{ get; set; }

        /// <summary>
        /// Actual uploaded quantity.
        /// </summary>
        [JsonProperty("ValidCount")]
        public ulong? ValidCount{ get; set; }

        /// <summary>
        /// Data too long quantity.
        /// </summary>
        [JsonProperty("TooLongCount")]
        public ulong? TooLongCount{ get; set; }

        /// <summary>
        /// Repetition count.
        /// </summary>
        [JsonProperty("RepeatCount")]
        public ulong? RepeatCount{ get; set; }

        /// <summary>
        /// Incorrect format count.
        /// </summary>
        [JsonProperty("InvalidCount")]
        public ulong? InvalidCount{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "TotalCount", this.TotalCount);
            this.SetParamSimple(map, prefix + "ValidCount", this.ValidCount);
            this.SetParamSimple(map, prefix + "TooLongCount", this.TooLongCount);
            this.SetParamSimple(map, prefix + "RepeatCount", this.RepeatCount);
            this.SetParamSimple(map, prefix + "InvalidCount", this.InvalidCount);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

