/*
 * Copyright (c) 2018-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TencentCloud.Ses.V20201002.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using TencentCloud.Common;

    public class GetEmailIdentityResponse : AbstractModel
    {
        
        /// <summary>
        /// <p>Validation type. Fixed value: DOMAIN</p>
        /// </summary>
        [JsonProperty("IdentityType")]
        public string IdentityType{ get; set; }

        /// <summary>
        /// <p>Whether verified</p>
        /// </summary>
        [JsonProperty("VerifiedForSendingStatus")]
        public bool? VerifiedForSendingStatus{ get; set; }

        /// <summary>
        /// <p>DNS configuration detail</p>
        /// </summary>
        [JsonProperty("Attributes")]
        public DNSAttributes[] Attributes{ get; set; }

        /// <summary>
        /// <p>dkim key length</p><p>Enumeration value:</p><ul><li>0: 1024</li><li>1: 2048</li><li>2: both</li></ul>
        /// </summary>
        [JsonProperty("DKIMOption")]
        public ulong? DKIMOption{ get; set; }

        /// <summary>
        /// <p>tag</p>
        /// </summary>
        [JsonProperty("TagList")]
        public TagList[] TagList{ get; set; }

        /// <summary>
        /// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId{ get; set; }


        /// <summary>
        /// For internal usage only. DO NOT USE IT.
        /// </summary>
        public override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "IdentityType", this.IdentityType);
            this.SetParamSimple(map, prefix + "VerifiedForSendingStatus", this.VerifiedForSendingStatus);
            this.SetParamArrayObj(map, prefix + "Attributes.", this.Attributes);
            this.SetParamSimple(map, prefix + "DKIMOption", this.DKIMOption);
            this.SetParamArrayObj(map, prefix + "TagList.", this.TagList);
            this.SetParamSimple(map, prefix + "RequestId", this.RequestId);
        }
    }
}

